### ISSUE TITLE
Password Reset Text (Not available with with [wpuf-login])

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#1005]
Greetings,

The **Password Reset Text** works fine inside a Widget. Thanks.
Would love to see this feature also available when using the **[wpuf-login]** inside a page.

Thank you.

**Comment by zamandevs** [comment]
It's already there. Button is different. on shortcode 'Get New Password' and on widget 'Reset Password'.

**Comment by Anticosti** [comment]
My bad. I was talking about this text:
"Please enter your username or email address. You will receive a link to create a new password via email"

This text is only available through the widget and NOT with the shortcode.

Regards,

**Comment by zamandevs** [comment]
Pls, look at [Here](https://prnt.sc/vdpc51) I didn't find what you stated.

**Comment by Anticosti** [comment]
This is exactly what I am looking for (on the left side of your screenshot) but... I don't have this message in the latest Pro version 3.4.1
Curious.

**Comment by zamandevs** [comment]
This is in free version not pro. what is  your free version. mine is latest 3.5.3

**Comment by Anticosti** [comment]
I am also using version 3.5.3 
Curious!?

**Comment by zamandevs** [comment]
Please contact support.
