### ISSUE TITLE
wp-user-frontend-pro/languages/wpuf-pro.pot (empty file)

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#1006]
Loco Translate found this file **wp-user-frontend-pro/languages/wpuf-pro.pot** empty after update from 3.4.0 to 3.4.1

**Comment by zamandevs** [comment]
Happened by mistake. regret for this unacceptable incident. will be in the next release.

**Comment by Anticosti** [comment]
Thank you Zamandevs for confirming.
