### ISSUE TITLE
Unable to access wp-admin as Administrator

### ISSUE THREAD

**Issue by kblizeck** [weDevsOfficial/wp-user-frontend#1017]
Website : http://villageunidev.wpengine.com/
WordPress Version 5.5.1
Plugins : 
- Master Popups : 3.6.0
- WP User Frontend : 5.2.1
- WP User Frontend Pro : 3.1.6
- WPFront User Role Editor : 2.14.4

When I login as an Administrator, I am redirected to the `/login` page, and am unable to access the admin dashboard. I am consistently redirected. If I try to select Dashboard from the Admin bar, I remain on the same `/login` page with a `redirect_to` option added to the URL - http://villageunidev.wpengine.com/login/?redirect_to=https%3A%2F%2Fvillageunidev.wpengine.com%2Fwp-admin%2F

![Screen Shot 2020-11-09 at 2 07 38 PM](https://user-images.githubusercontent.com/9886123/98596647-f2dce880-2294-11eb-8184-1bfeafad81c0.png)

**Comment by hasinur1997** [comment]
@kblizeck You may mistake to write wp-user-frontend version. Whatever I tested it and works properly from my end. Please contact our support.

Thanks.
