### ISSUE TITLE
Users can't edit their post from the frontend

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1021]
**Description:**

**With the hotfix new version of WPUF free- 3.5.5, user can't edit their posts from the frontend**

Case-1: If you create a user from the backend, then they can access and edit their posts from the frontend.
But new users who are registering from the front using WPUF can't manage/edit their post from the frontend.

Case-2:
Also, sometimes an existing user can't edit his new post from the frontend.

**How to reproduce:**
1. Create a new user from the backend and frontend through the WPUF registration form. Then try to edit from the frontend.

**Note**: You can repeat the task with a new user and existing users (IDK the user role does matter or what cause the result is sometimes positive, sometimes negative)

**Video Prove**: 
Please [check this uncut video](https://drive.google.com/file/d/192Fao2vMpGVypPbE-bsjocTpTVOFl1kv/view?usp=sharing) to reproduce closely.

**Site info:**
https://throwbin.io/G56eRxM

Thanks.

**Comment by zamandevs** [comment]
@zamandevs @hasinur1997  @FaraziF  These issues are producing due to phpcs. This is our responsibility to check value properly before PR & should catch on QA at least.

**Comment by Anticosti** [comment]
@zamandevs This is a great Leader attitude. Kudos!
Please Keep up responding quick to such issues.

**Comment by hasinur1997** [comment]
This is issue has been resolved.
