### ISSUE TITLE
Category items issue

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#1034]
**Description:** Admin is unable to delete any specific selection terms amongst the inserted selection terms of the category field

**How to Reproduce the Issue:**

Take a post form and take the category field. Edit the field. 

Next on the right side, click on advanced settings and look for selection terms. Add the category items here. 

Try to remove any specific item from the selection terms that has been inserted. The cursor doesn't appear in between two selection terms. Please check the [screenshot](https://prnt.sc/vywahs).

**Expected behavior:** The cursor should move anywhere and should delete items in between.

**Video**: https://www.loom.com/share/7dca0d8d61124be783aa8bd1cdee7a77

**Version:**

WPUF free 3.5.8

**Comment by zamandevs** [comment]
@shabnam611 Please use the right arrow, left arrow in order to go forward & backward.

**Comment by shabnam611** [comment]
@zamandevs 
okay thank you. A tooltip would be great to tell people that using arrow key is the way to insert in between. Please check the screenshot: https://prnt.sc/w2b1aw
