### ISSUE TITLE
Cannot remove featured image

### ISSUE THREAD

**Issue by Tsjippy** [weDevsOfficial/wp-user-frontend#1036]
When I try to remove the futured image in the frontend I get this error:

I am an on the latest version of wpress

```
Uncaught TypeError: Cannot read property 'constructor' of undefined
    at Ue (swal.min.js:1)
    at window.WPUF_Uploader.removeAttachment (upload.js?ver=2269a50b51039f61789849d0881457b3:197)
```

**Comment by zamandevs** [comment]
@Tsjippy Everything is working fine on both the latest 5.6 & the previous versions. featured image is adding & removing when the user logged in or guest mode. if you still face this please don't hesitate to contact our support.

**Comment by Tsjippy** [comment]
thank you found the bug in my own custom plugin. Fixed now
