### ISSUE TITLE
Post form shortcode preview issues for some fields

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#1038]
**Description**: Once the post form shortcode is inserted by using custom block, the fields look inconsistent.

**How to Reproduce the Issue:** 

Take a post form and add few post form fields. 

Next visit the WP-admin > Pages section and select the WPUF custom block. Take the post form shortcode.

Once the shortcode is added in the page, some inconsistency are seen. 

**Screenshots:** 
Post title: https://prnt.sc/w34kxu
Tags and Text field: https://prnt.sc/w34qsi
Website URL, Email, Country list: https://prnt.sc/w34r6o
Address and Embed field: https://prnt.sc/w34rtc
Steps start field: If added the fields after step start field are not seen anymore. 

**Expected scenario**: all the fields should be inside the container of the form. 

Version: 

WPUF 3.5.9
WordPress 5.6

**Comment by hasinur1997** [comment]
@shabnam611 Couldn't find problem as you describe. @FaraziF, need to test this issue.

**Comment by FaraziF** [comment]
@hasinur1997 & @shabnam611 can't reproduce this issue. please review the video[video](https://www.loom.com/share/556a36624dd943c28a4978aa2d83e5a8)
