### ISSUE TITLE
PHP Deprecated:  join(): Passing glue string after array is deprecated. Swap the parameters in *****wpuf-functions.php on line 1486

### ISSUE THREAD

**Issue by PinkishHue** [weDevsOfficial/wp-user-frontend#1039]
Warning in error log:

`PHP Deprecated:  join(): Passing glue string after array is deprecated. Swap the parameters in /var/sites/*/****/public_html/wp-content/plugins/wp-user-frontend/wpuf-functions.php on line `1486``

**Comment by hasinur1997** [comment]
@PinkishHue Please explain a little more so that we can reproduce it easily.

Thanks.
