### ISSUE TITLE
Warning: DOMXPath::query(): Invalid expression

### ISSUE THREAD

**Issue by ejmatdat** [weDevsOfficial/wp-user-frontend#1040]
I'm getting the errors below when:
the user click activation link in email and the admin click on approve, deny, pending in wp-admin/users. This is while:
WP_DEBUG = true
WP_DEBUG_DISPLAY = true
and
WP_DEBUG = false
WP_DEBUG_DISPLAY = true
I'm running PHP 7.4.9

WordPress debug log: https://drive.google.com/file/d/1nq5WeI0i3UiWXDQ5m0njuWWEe8CCgI_g/view?usp=sharing

Warning: preg_replace(): Compilation failed: invalid range in character class at offset 39 in F:\LARAGON\www\Aabaca\wp-content\plugins\wp-user-frontend-pro\includes\libs\Emogrifier.php on line 1294

Warning: DOMXPath::query(): Invalid expression in F:\LARAGON\www\Aabaca\wp-content\plugins\wp-user-frontend-pro\includes\libs\Emogrifier.php on line 376

Screenshot, Admin/user/ after click on approve, deny, pending: https://drive.google.com/file/d/1G-pMIB-mvo5wof210dMxrieLeocHgA3S/view
Screenshot, Login page after clicking activation link in email: https://drive.google.com/file/d/16CaH-DfB1wiULRomlrXsWalMSdUEgYtA/view?usp=sharing 

I believe this issue was mention before here https://github.com/weDevsOfficial/wp-user-frontend/issues/911

**Comment by hasinur1997** [comment]
Couldn't reproduce the issue. @FaraziF need to test this issue.

**Comment by FaraziF** [comment]
@hasinur1997 I am also unable to reproduce this issue with the expected scenario. @ejmatdat Please contact our support ninja [here](https://wedevs.com/contact)
