### ISSUE TITLE
Taxonomy fields not showing for custom post types

### ISSUE THREAD

**Issue by flosaurus** [weDevsOfficial/wp-user-frontend#1046]
When selecting a custom post type in Post Settings, taxonomies fields (categories and tags) are not proposed/displayed in the form editor.

If selecting a regular post type, taxonomies fields are displayed as expected

**Comment by shabnam611** [comment]
Hello @flosaurus 

Are you using paid version of WPUF? The custom taxonomy for the custom post type will appear if you have the paid version of WPUF activated. 

If you are already using a paid version but you are still facing the issue, please email the support team at support@wedevs.com.

Thank you.

**Comment by flosaurus** [comment]
Thank you for your feedback.
I'm not usingthe paid version indeed. I didn't know the feature was not
part of the default package. I'll look into the paid offer

Cheers

Le mar. 29 déc. 2020 à 12:08, Mushrit Shabnam <notifications@github.com> a
écrit :
