### ISSUE TITLE
duplicates of shortcodes inside the form

### ISSUE THREAD

**Issue by aviHanuka** [weDevsOfficial/wp-user-frontend#1048]
Hi, i have an issue that when I use shortcode inside the form
 I mean i put shortcodes and the y do display, but the issue is there something that makes copy.
Please advice.

**Comment by zamandevs** [comment]
@aviHanuka need more insight. if you please provide how and which point it occurs.

**Comment by aviHanuka** [comment]
Thank you for the replay, I was trying to add a label to each shortcode. so I added the following HTML as part of the shortcode:
<li class="wpuf-el description field-size-large" data-label="custom_field">
 <div class="wpuf-label">
<label for="custom_3545">cusom label</label>
</div>
<div class="wpuf-fields">
 <textarea class="textareafield  wpuf_custom_3545" id="custom_3545" name="custom_description" data-required="no" data-type="textarea" placeholder="" rows="5" cols="25"></textarea>
<span class="wpuf-wordlimit-message wpuf-help"></span> </div></li>

all I wanted was to change the label, because when you use the shortcode inside some form (for instance registration form) the label is : "SHORTCODE".
but I found another way, 
I got to `wp-user-frontend-pro/includes/fields/class-field-shortcode.php`
line 28 - function render - and change it so I can pass part of string inside the shortcode and define the label in that way.

so thank you but I did solve this.

**Comment by zamandevs** [comment]
@aviHanuka Thanks for your contribution. you can open a PR in this regard or we will add this.

**Comment by zamandevs** [comment]
@aviHanuka Will be next released.
