### ISSUE TITLE
Do not change meta_key once it is already filled

### ISSUE THREAD

**Issue by antoinepat** [weDevsOfficial/wp-user-frontend#1050]
When you are editing a field , the meta_key is filled automatically from the label. But it happened a lot of time that my client want the label changed, and if you don't pay attention when you modify the label the meta_key changes and that can lead to issues. Why don't just set meta_key mandatory and do not autofill ? or don't autofill when the field was already saved ?

**Comment by Anticosti** [comment]
Very well explained. I also find this annoying.

**Comment by zamandevs** [comment]
@antoinepat Very thanks for your suggestion. I also find this annoying. will handle this immediately.
