### ISSUE TITLE
Notice when image is uploaded 

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#1054]
Description: If the image is not uploaded for some reason, the notice takes the space of the image and refresh is the only option to remove that notice

How to Reproduce the Issue: 

Take a post form and take a image upload field in the post form. 

Then upload an image which can be blocked by the system. For example, this image: https://drive.google.com/file/d/1P_NpEJQYiMjCkMW4oPKf2xRl91HIvMK6/view

What is the Issue: When we try to upload this image inside the WPUF post form, we are blocked but we have no wayt to remove it without refreshing the page. This is a bad user experience. 

Video: https://www.loom.com/share/3f7c632457e3483984f062c1da6fd844

Expected Scenario: A try again button or close icon would be great so that the user can upload a new picture and try again without refreshing the page. This would be a bad experience to refresh the page if the form is long.

WPUF 3.5.12 and WordPress 5.6

**Comment by telenova-code** [comment]
Yes any development on this would be appreciated. I am experiencing the same problem and designing a fairly long form. Refreshing the page after a failed upload would mean lose all the information already entered which is really not viable
