### ISSUE TITLE
Change the Style of Column Field 

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#1055]
Description: 

Our current column field is not very smart. 

Possible Solution: 

We can follow the style of Gutenberg column block and how they allow the users to add columns in the post form. This way users will be less confused on how to use and will not use in the wrong method. 

We can show the styles like Gutenberg does so that users can easily understand which one they want.

**Comment by anik-fahmid** [comment]
Could be considered if we revamp the current form builder UX.
