### ISSUE TITLE
Not AMP compatible

### ISSUE THREAD

**Issue by ijdk-loop** [weDevsOfficial/wp-user-frontend#1056]
I am using https://wordpress.org/plugins/amp/ plugin in wordpress.
it is working fine with all my plugins without hiccup, except woocommerce. For woocommerce I had to disable content type "product" template and then it was fine.

BUT your plugin is not working with AMP. To make it work, I had to disable content type "page" template and this fully destroys the main advantage and the purpose of AMP.

Please update if any.

**Comment by anik-fahmid** [comment]
Not planning now.
