### ISSUE TITLE
WPUF Login displays blank page

### ISSUE THREAD

**Issue by jayyx2** [weDevsOfficial/wp-user-frontend#1058]
When logging in using a normal user account on the WPUF Ajax Login form, the user is redirected to a blank page. Nothing ever happens. If I refresh the page, I am then logged in as expected. I've tried various different combinations of options changes, all with the same result. Social logins work without this problem.

https://www.loom.com/share/bfba49426bac411a9ed82484af1b8551

**Comment by zamandevs** [comment]
@jayyx2 Insight/further info requires for look into the issue. you can provide A to Z step whats you've done and what happened. or you can contact our [support](https://wedevs.com/) thus we can directly see investigate why this happening. 
Thanks.

**Comment by jayyx2** [comment]
1. Create login page
2. Enable Social Login
3. Login on the login page created, using a non-social login
4. A blank page is displayed after logging in (just like in the video)

I've also created another video, explaining these steps in detail and sent it along to your technical support 16 days ago. Is there any additional details needed? I could setup a dev environment if necessary, just let me know. Thanks!

**Comment by zamandevs** [comment]
@jayyx2 Few things: did you set Redirect After Login page from settings > Login/Registration option. or Default Login Redirect page option from the same settings area or you've empty posts? please recheck these settings and don't hesitate to reply if it still happens or communicate with [Contact](https://wedevs.com/contact)

**Comment by jayyx2** [comment]
I have a support case opened with your support team, and sent them a video showing all of these settings. I manually just tested every combination of those options and the issue still persists. What else do I need to do in order for this issue to be looked at more in-depth?

**Comment by zamandevs** [comment]
@jayyx2 We are sorry for the convenience. when you set redirection as prev page and directly paste login link on URL in this scenario prev URL is empty. handled and fixed on the plugin. will be on next release. 
Thanks for your patience.
