### ISSUE TITLE
Free version registration form is not created automatically

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#1059]
**Description:** 

When a new user installs WPUF, and creates pages from tools section, the shortcode built registration form of the free version is not created along with other pages

**How to Reproduce the Issue:** 

1. Make a fresh WordPress installation
2. Install WPUF and when the setup wizard appears - click on "Not right now"
3. Visit WP-admin > WPUF > Tools > Install WPUF pages
4. Then visit WP-admin > WPUF > Settings > Login/registration and then try to select the registration page https://www.loom.com/share/4adf29d1dc9e49f2a20a492fbd3797c7

**Expected Result**: The registration form needs to be created automatically and needs to be set here: https://prnt.sc/xyd4ew

**Environment details:**

WordPress version 5.6
WPUF free 3.5.12
PHP version 7.4

**Comment by shabnam611** [comment]
@zamandevs @hasinur1997 
is there any update on this issue? We are unable to progress with our onboarding videos if this issue exists

**Comment by hasinur1997** [comment]
@shabnam611 it is not updated yet. We will fix it as soon as possible.

**Comment by elosha** [comment]
Issue is still happening:
1. Installed WPUF
2. Generated page "Registration"
3. Inserted shortcode ``[wpuf-registration]``, according to WPUF _Registration Forms_ backend page, in Gutenberg _Shortcode_ block
4. Turned on login/registration override,
5. Selected "Registration" page as registration page in backend WPUF _Settings_
6. Shortcode is not being rendered, remains as text, while all other WPUF shortcodes work

WP: 6.2
Gutenberg: core
WPUF: 3.6.4
Theme: Fork of twenty-twentytwo 1.3, using Gutenberg templates
