### ISSUE TITLE
Subscription pack not loaded into user

### ISSUE THREAD

**Issue by bazzar701** [weDevsOfficial/wp-user-frontend#1066]
Hello, I am having a problem with WP User Frontend. 
Everytime a user buys a Subscription Pack, it opens the payment page for Stripe, the payment is successful, but the transaction does not appears in the Transaction Page, nor the Subscription Pack is not credited to user profile. 
It doesn't show up in user account or either in user profile in backend. It is all updated using the last version and no changes. Any idea of what is going wrong?

**Comment by zamandevs** [comment]
@bazzar701 Not sure how you faced this trouble. BTW please upgrade to the latest version. everything should be working as expected. still if you face anything wrong don't hesitate to [Contact](https://wedevs.com/contact) with our support.
