### ISSUE TITLE
reCaptcha not included in edit post page

### ISSUE THREAD

**Issue by sandalkoyak** [weDevsOfficial/wp-user-frontend#1069]
I have no trouble when submitting, it's only appear to a problem when I try to **edit** the posts **with attachment** (I was trying to upload a pdf file). When I checked the developer tools, I found "No reCAPTCHA clients exist" in console **ONLY** after I uploaded a pdf for instance.

I believe the reCaptcha client doesn't exist only in EDIT page, hence the problem occurred. Please help.

**Comment by zamandevs** [comment]
@sandalkoyak Please check on the latest version. there shouldn't any issue regarding Recaptcha including 3rd party/multiple integrations. 

Still, if you found something wrong please reach us with more detail.
