### ISSUE TITLE
Sorry, This File Type Is Not Permitted For Security Reasons, using File upload object

### ISSUE THREAD

**Issue by ivoquaio** [weDevsOfficial/wp-user-frontend#1072]
Hi,

I use a file upload object in a WP form (WP user frontend 3.5.13).
when a user try to upload a .zip or .rar file he gets the above message. I've also added the line

define('ALLOW_UNFILTERED_UPLOADS', true);

in wpconfig.php, but it doesn't work.
How to solve this issue? thank you

**Comment by sapayth** [comment]
Hello @ivoquaio,
Please make sure the "Zip Archive" option is selected in WPUF forms > Filed options > Allowed Files
<img width="379" alt="image" src="https://user-images.githubusercontent.com/15567340/163775464-1b4017e6-1549-428b-a3dc-8508639557fd.png">

If the issue still occurs, feel free to notify us.
