### ISSUE TITLE
Avatar upload not working on registration form due to reCaptcha not being loaded

### ISSUE THREAD

**Issue by jayyx2** [weDevsOfficial/wp-user-frontend#1074]
After uploading an image, you can't submit the form because this error is presented in the browser console.

recaptcha__en.js:273 Uncaught Error: No reCAPTCHA clients exist.
    at Array.<anonymous> (recaptcha__en.js:273)
    at recaptcha__en.js:199
    at window.WPUF_Uploader.uploaded (upload.js?ver=5.6.2:183)
    at F.Uploader.i (jquery.min.js?ver=3.5.1:2)
    at F.Uploader.dispatchEvent (plupload.min.js?ver=2.1.9:1)
    at F.Uploader.trigger (moxie.min.js?ver=1.3.5:1)
    at F.s.status.F.UPLOADING.r.state.F.STOPPED.p.onload (plupload.min.js?ver=2.1.9:1)
    at F.<anonymous> (moxie.min.js?ver=1.3.5:1)
    at Array.<anonymous> (moxie.min.js?ver=1.3.5:1)
    at t (moxie.min.js?ver=1.3.5:1)
(anonymous) @ recaptcha__en.js:273
(anonymous) @ recaptcha__en.js:199
uploaded @ upload.js?ver=5.6.2:183
i @ jquery.min.js?ver=3.5.1:2
dispatchEvent @ plupload.min.js?ver=2.1.9:1
trigger @ moxie.min.js?ver=1.3.5:1
s.status.F.UPLOADING.r.state.F.STOPPED.p.onload @ plupload.min.js?ver=2.1.9:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
t @ moxie.min.js?ver=1.3.5:1
inSeries @ moxie.min.js?ver=1.3.5:1
dispatchEvent @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
t @ moxie.min.js?ver=1.3.5:1
inSeries @ moxie.min.js?ver=1.3.5:1
dispatchEvent @ moxie.min.js?ver=1.3.5:1
trigger @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
load (async)
send @ moxie.min.js?ver=1.3.5:1
exec @ moxie.min.js?ver=1.3.5:1
shimExec @ moxie.min.js?ver=1.3.5:1
exec @ moxie.min.js?ver=1.3.5:1
r @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
send @ moxie.min.js?ver=1.3.5:1
g @ plupload.min.js?ver=2.1.9:1
b @ plupload.min.js?ver=2.1.9:1
dispatchEvent @ plupload.min.js?ver=2.1.9:1
trigger @ moxie.min.js?ver=1.3.5:1
r @ plupload.min.js?ver=2.1.9:1
start @ plupload.min.js?ver=2.1.9:1
added @ upload.js?ver=5.6.2:107
i @ jquery.min.js?ver=3.5.1:2
dispatchEvent @ plupload.min.js?ver=2.1.9:1
trigger @ moxie.min.js?ver=1.3.5:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
setTimeout (async)
e @ plupload.min.js?ver=2.1.9:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
t @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
t @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
t @ moxie.min.js?ver=1.3.5:1
inSeries @ moxie.min.js?ver=1.3.5:1
(anonymous) @ plupload.min.js?ver=2.1.9:1
t @ moxie.min.js?ver=1.3.5:1
inSeries @ moxie.min.js?ver=1.3.5:1
addFile @ plupload.min.js?ver=2.1.9:1
e.onchange @ plupload.min.js?ver=2.1.9:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
(anonymous) @ moxie.min.js?ver=1.3.5:1
t @ moxie.min.js?ver=1.3.5:1
inSeries @ moxie.min.js?ver=1.3.5:1
dispatchEvent @ moxie.min.js?ver=1.3.5:1
trigger @ moxie.min.js?ver=1.3.5:1
e @ moxie.min.js?ver=1.3.5:1

You can recreate this easily by trying to upload a photo when in the "Edit Profile" section. Also, if your registration form does not have a reCaptcha added you get this same error when creating a new account.

**Comment by jayyx2** [comment]
`            if ( FileProgress === uploaded ) {
                if ( typeof grecaptcha !== 'undefined' && !grecaptcha.getResponse().length ) {
                    return;
                }

                $(".wpuf-submit-button").removeAttr("disabled");
            }
        },

`

removing lines 183-186 seems to correct the issue, or at least allow a user to update their avatar image.

**Comment by zamandevs** [comment]
Handled on release v3.5.17

**Comment by jayyx2** [comment]
This is not fixed in the latest release. If I comment out this section, it works as expected.

`            if ( FileProgress === uploaded ) {
                //if ( typeof grecaptcha !== 'undefined' && !grecaptcha.getResponse().length ) {
                //    return;
                //}

                $(".wpuf-submit-button").removeAttr("disabled");
            }`
