### ISSUE TITLE
ob_start() repeated twice, could it be a bug?

### ISSUE THREAD

**Issue by Kodooldesign** [weDevsOfficial/wp-user-frontend#1082]
Good morning, 
to solve my problem with the previously reported [wpuf_edit] page, I removed the ob_start() function, in the plugin core in includes/class-frontend-form-post.php at line 50. 
The ob_start() function was repeated twice (line 50 and line 54). 
Now the [wpuf_edit] page also works correctly. 
I use WP in Bedrock with Sage Theme (https://roots.io/sage/); 
I've installed Woocommerce and WPML plus WPUF Pro; 
This is my staging environment: https://staging.nowarc.com
Thank you

**Comment by zamandevs** [comment]
@Kodooldesign It couldn't produce any bug/error. FYI it doesn't matter how many times you wrote ob_start. when it will call ob_get_flush, ob_get_clean etc it will send everything between your first ob_start to flush/clean function into output buffer.
