### ISSUE TITLE
Something went wrong error message showing for unrequired post field and required featured image.

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1083]
**Issue:** 
Something went wrong error message showing for unrequired post field and required featured image.

**How to reproduce:**
1. Create a post form with a Featured image as required
2. Insert another Post Field item (Post Title, Post Content, Post Excerpt) and make it as unrequired
3. Now save the form and publish it, then visit from the frontend
4. Insert a featured image and keep the post field empty. Now try to submit the posting form
5. You will notice that it’s showing the error “Something went wrong.”

**Screenshots:**
Backend view - http://i.prntscr.com/iPHbrGKITly_sYjbhZ0Arw.png
Frontend view - http://i.prntscr.com/PLODgXzqQbyHc4LxdPdEaQ.png

**Expected behavior:**
It should let the user submit the post freely as _Post Field_ fields are not required and save the post with the blank post title (as the slug is auto-generate with post_id)

**Environment info:**
- WordPress latest version 5.7
- WP User Frontend 3.5.15

**Comment by zamandevs** [comment]
@mmarj Post title must be set. this is the only required field if we create new post. so if we fill this everything is fine. please check again and let me know if anything i miss.

**Comment by mmarj** [comment]
But @zamandevs Bhai, WordPress doesn't require the Post Title cause if you leave the Post Title empty, it still creates the post with _(no title)_ and ID as the slug. So how do we justify that?

**Comment by mmarj** [comment]
So if this is intentional for security reasons (_or to avoid spam_), then it's a different thing. However, I'm not sure about those consequences.

**Comment by zamandevs** [comment]
@mmarj Post must have title/content/excerpt & this is also clear in our form.if we want to create form without one of this it will show this message. details [HERE](https://core.trac.wordpress.org/browser/tags/5.8/src/wp-includes/post.php#L3933)
