### ISSUE TITLE
Ajax type category field is showing blank while editing

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#1084]
**Description**: When a post is edited, the ajax category field is showing blank

**How to Reproduce the Issue:**

Take a post form, add ajax catgory field and then submit the post. 

Edit the post from the account page. Then we see the category field is blank. 

**Video**: https://www.loom.com/share/b965b73f4c144d67b5ae9cef76262484

**What to Expect**: The category field should appear while editing exactly like how the user submitted the post. 

Version of WPUF: 3.5.15

**Comment by mmarj** [comment]
Kindly check this issue @itowhid06 Bhai.
