### ISSUE TITLE
Exclusion in category does not work v3.5.15

### ISSUE THREAD

**Issue by kabirbd89** [weDevsOfficial/wp-user-frontend#1089]
In category advanced options, if I select,
**Ajax** in Type 
and 
**Exclude** in Selection Type 
and
select **categoryA** in selection term.

Only the **categoryA** excluded but **not its sub-categories.** All the sub-categories of categoryA show in forms. Exclusion of categoryA supposed to hide categoryA and all its subcat. 

And this issue raises after v3.3.1 update. **v3.3.1 ware ok.**

**Comment by zamandevs** [comment]
@kabirbd89 FYI what you stated above is in line with the exclusion selection type. still, there is room to discuss. but it is designed this way as i know.

**Comment by kabirbd89** [comment]
@zamandevs its remain same in line option with other combination. But in setting window exclusion of catA hide its all subcat. 

ajax is directly connected with category hierarchy so, exclusion should work with category hierarchy as it worked in the previous version (the last known working version I am using is v3.3.1).

**Comment by zamandevs** [comment]
Fixed [HERE](https://github.com/weDevsOfficial/wp-user-frontend/pull/1127)

**Comment by kabirbd89** [comment]
@zamandevs I just updated (Version 3.5.29) once again with hope but exclusion in ajax does not work as expected. I have to roll out to last known working version v3.3.1. 

Can you please take a look at v3.3.1 may be it will help to understand the issue properly.
