### ISSUE TITLE
Missing string for "Select State"

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#1094]
The address field is missing a translation for "Select State" dropdown

**Comment by Anticosti** [comment]
This should not be a big deal to solve...

**Comment by mmarj** [comment]
Hi @Anticosti 
This string is already available on the wpuf-pro.pot file. Here is a screenshot from my Loco Translate editor - (https://ibb.co/kHyByHG) and these are the output:
Form Editor- https://ibb.co/PMv11N6
Form Output- https://ibb.co/mDP9Z8x
Thanks.
