### ISSUE TITLE
Your Subscription Pack is expiring! (automatic email)

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#1095]
Greetings,

Would be nice if you could add the **Name** and **Date** and the **Number of days** _before_ the subscription will expire. Plus a **Thank you for staying with us!**

--- Right now customers receive this:--- 
Dear Subscriber,

Your Subscription Pack is expiring!
Please buy a new subscription pack.

--- Wish they would receive this: ----
Dear **John Doe**,

Your Subscription Pack is expiring in **14** days!
Expiration Date: **2021-05-06**
Please buy a new Subscription Pack.

Thank you for staying with us!

**Comment by zamandevs** [comment]
@Anticosti For this we had an email template where you can set some tags to get your desired format. Please look at [HERE](https://prnt.sc/126i9h3)

**Comment by Anticosti** [comment]
@zamandevs 
Big thanks for this. I really overlooked this great configuration. My bad.
Much appreciated. Kudos!

**Comment by Anticosti** [comment]
@zamandevs 

I did a test. The only part that is not working are shortcodes for dates (Tuesday, July 2020). The day (number) is missing. Wish it would be formatted in a more like international ISO way: YYYY-MM-DD
See below:

---- FRANÇAIS ----
Cher joe,

Votre Pack d'abonnement "iR-3-Special-Sticky" arrive à expiration!
Pack signé, le: Tuesday, July 2020
Échéance du Pack, le: Thursday, January 1970

Veuillez acheter un nouveau Pack d'abonnement: iR-3-Special-Sticky (0)

Merci de rester avec nous.

---- ENGLISH ----
Dear joe,

Your Subscription Pack "iR-3-Special-Sticky" is expiring!
Pack signed: Tuesday, July 2020
Pack ending: Thursday, January 1970

Please buy a new Subscription Pack: iR-3-Special-Sticky (0)

Thank you for staying with us.


---------------------------------
Hope you understand what I mean....?

Cheers,
