### ISSUE TITLE
custom field url validation.

### ISSUE THREAD

**Issue by vinaysudhir** [weDevsOfficial/WP-User-Frontend#11]
Hi
I created a new text box and labeled it URL but by default the only validation criteria available is 
"A validation criteria. User must provide input in that field"
But it is not sufficient for domain name or URL validation, 

something like this may be good to validate

``` php
<?php

 function checkdomainname($Domainname) {
if(getmxrr($Domainname, $MXHost))
{
   return TRUE;
}
return FALSE;

}
```

this I found in google,but dont know how to add to plugin.

I seen the URL is saved in cf_URL in post meta of db, 
I just want to validate the URL or Domain name before it is saved in db.

So that only valid domains or URLs will be save.

Could you please tell me how to validate the domain names using WP User Frontend: Custom Fields

thank you.

**Comment by Sk-Shaikat** [comment]
Hello Vinay Sudhir,
Thank you for reported this issue. This feature has been added as an URL custom field.
