### ISSUE TITLE
Calendar field mindate and maxdate as numbers only work if within 10 years from now

### ISSUE THREAD

**Issue by sailman342** [weDevsOfficial/wp-user-frontend#1100]
No way to get the calendar show dates earlier/further than 10 years from now !

My bith date will not make it :-)

![image](https://user-images.githubusercontent.com/58634016/116829518-61479700-aba4-11eb-9eff-7f2092396d9c.png)

**Comment by sailman342** [comment]
This bug makes it impossible to enter a birthdate, do you eintend to do something, I am using the pro version !

Thanks, should not be complicated to solve !

**Comment by mmarj** [comment]
Hi @sailman342 
We already addressed this scenario with our Pro version of the plugin (the date/time field is with our pro plugin). The fix ([_pro PR_](https://github.com/weDevsOfficial/wpuf-pro/pull/317)) will be patched with our upcoming pro release.

Thanks

**Comment by sailman342** [comment]
Tanks à lot
