### ISSUE TITLE
WPUF Product Form showing meta inconsistency with the regular price post_meta

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1101]
WPUF Product Form showing meta inconsistency with the regular price post_meta

**Description**:
The regular price meta is showing duplicate output on the form dashboard area.

**How to reproduce:**

1. Create multiple WC Product forms. Say: you have 3 WC product type form for a different reason.
2. Now submit dummy products throughout each product form.
3. Now, create a page with a custom dashboard shortcode to show associate product form's data. Like:
→ For form 1: `[wpuf_dashboard form_id="183" post_type="product" meta="_regular_price, your_any_custom_field_meta"]`
→ For form 2: `[wpuf_dashboard form_id="221" post_type="product" meta="_regular_price, your_custom_field_meta_test"]`
→ For form 3: `[wpuf_dashboard form_id="221" post_type="product" meta="_regular_price, your_custom_field_meta_textarea"]`

Now visit your custom product dashboard frontend. You will see the associate product form's Price will appear twice except for the one form.

**Screencast/video:**
Please watch [this video](https://drive.google.com/file/d/1FvrNojqWOMFoZ32VdjcKnBa8RHemUvvO/view?usp=sharing).

**Site info:**
WordPress version: 5.7.1
WPUF Free Version: 3.5.15
WooCommerce Version: 5.2.2

Thanks

**Comment by zamandevs** [comment]
@mmarj Couldn't produce with WP 5.8, WPUF 3.5.19, WPUF-PRO 3.4.6. if you please try with latest version.
