### ISSUE TITLE
"Too large file" error on setting Featured image in post form

### ISSUE THREAD

**Issue by festerman** [weDevsOfficial/wp-user-frontend#1102]
Max file size settings doesn't take in a form: trying to set a featured image gives me a "too large file" error -- uploading the same image file in the Media library works.

I am running  wp-user-frontend v3.5.15 in WP 5.7.1, with PHP 7.3.20.

I have /etc/php.ini set as `upload_max_filesize = 52428800`
and  `post_max_size = 52428800` (ie 50MiBi ...)

and
  `[root@xxx]# wp eval "echo ini_get( 'upload_max_filesize' );"`,
  `[root@xxx]# wp eval "echo ini_get( 'post_max_size' );"` and 
  `[root@xxxx]# wp eval "echo wpuf_max_upload_size();"` 

all return 52428800 (aka 50MB). But a 2377kb image does not work.

A possible cause:

on line 43 in assets/js/upload.js: `max_file_size: max_file_size + 'kb'` -- which seems to expect a value in a specific unit. If that string is passed to plupload, and that in its turn tries to interpret it acc. to https://www.php.net/manual/en/faq.using.php#faq.using.shorthandbytes, then something may go kablooey?

**Comment by festerman** [comment]
OK, I'll retract that: "the bug" is my misunderstanding: the javascript attached to the Featured Image button is 

`<script type="text/javascript">
            ;(function($) {
                $(document).ready( function(){
                    var uploader = new WPUF_Uploader('wpuf-featured_image-153-pickfiles', 'wpuf-featured_image-153-upload-container', 1, 'featured_image', 'jpg,jpeg,gif,png,bmp', 1024);
                    wpuf_plupload_items.push(uploader);
                });
            })(jQuery);
        </script>`

--- and that is in the settings ... So the global max size settings are amended by a local restriction.

**Comment by zamandevs** [comment]
@festerman Still if you face something don't hesitate to reply.
