### ISSUE TITLE
Can not change the Meta Key

### ISSUE THREAD

**Issue by LauridsPetersen** [weDevsOfficial/wp-user-frontend#1108]
Hi

I'm using WP User Frontend version 3.5.16 with WP User Frontend Pro - personal version 3.4.4
Wordpress version 5.7.2

Problem:
I can only change the Meta Key in the forms when I create a new field. If I afterwards will change the Meta Key it resets to its original value.

**Comment by zamandevs** [comment]
@LauridsPetersen We have done this with care. if user able to edit meta key afterwards it will make inconsistency with post that already created using this form. so we enable to edit meta key before saving that field. Thanks for your query.
