### ISSUE TITLE
wp user frontend conflict with woocommerce downloadable products

### ISSUE THREAD

**Issue by ivoquaio** [weDevsOfficial/wp-user-frontend#1109]
WP user frontend 3.5.16 , woocommerce 5.3.0.
Editing the Products, if I check Virtual and Downloadable options, after updating, the options return unchecked.

**Comment by zamandevs** [comment]
@ivoquaio Not sure it's happening due to WPUF. if you face this due to WPUF please open an support ticket with your site details.

**Comment by zamandevs** [comment]
@ivoquaio If you missing something, virtual product type required downloadable files. otherwise, it wouldn't work.
