### ISSUE TITLE
[Enhancement Request] make the columns field sortable(drag & drop) compatible for inside custom fields

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1111]
[Enhancement Request] make the columns field sortable(drag & drop) compatible for inside custom fields

**Description of the current situation and expected outcome:**
Say you have created a long-listed post/registration form with your desire custom fields. Later on, to make the output design of the field look attractive, you decide to re-order your existing fields inside columns. But you will be noticed your existing fields won't be draggable inside your columns fields. So you have to recreate the design again from the stretch in a bitter way:
First, pick a column field, drag & drop your other custom fields inside, which is irritating and troublesome.

So it would be great if we make the `Columns Field` drag & dropable for existing fields.

**Relevant screencast of the scenario:**
https://drive.google.com/file/d/12gH25ISuPpekF-Tc-LCarJdFiOxlV5qL/view?usp=sharing

**Comment by sapayth** [comment]
This has been implemented and is now functional.
