### ISSUE TITLE
Missing string for "Select Country"

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#1114]
The address field is missing a translation for "Select Country" dropdown

**Comment by mmarj** [comment]
It's also available with the Pro pot file. 
SS from my loco translator- https://ibb.co/xq5CPP0
Output- https://ibb.co/mDtQC6N.

Please make sure you have the WPUF pro text-domain set as `wpuf-pro-en_US.po` & `wpuf-pro-en_US.mo`
