### ISSUE TITLE
Make the new "Select Custom Post For Account Page" selected post/custom post-Translateable and improve the post's slug

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1117]
Make the new "Select Custom Post For Account Page" selected post/custom post-Translateable and improve the post's slug.

**Description:**
**Issue1**- From the latest version of WPUF (3.5.17), the default "Post" tab is untranslateable. Also, if you select any other custom post types, you will see it will show the CPT tab on the frontend. However, the strings are untranslateable. 
-- I tried with the default "Posts" and "Products" tab. Those are untranslateable.

**Issue2**- It seems it's adding an extra "s" as a suffix for the backend-selected "Select Custom Post For Account Page". Like if you select "post" and "product" from the backend. You will see it will show the output as "Posts" and "Products", but the slug/URL will reflect as "?section=post" and "?section=product."

Please make this translate-friendly and take care of the associate selected>post's slug/URL.

**Related SS:**
https://ibb.co/FqwCtT3
https://ibb.co/305b7y4

Thanks.

**Comment by zamandevs** [comment]
Fixed [HERE](https://github.com/weDevsOfficial/wp-user-frontend/pull/1124)
