### ISSUE TITLE
Custom Upload Error - plupload

### ISSUE THREAD

**Issue by telenova-code** [weDevsOfficial/wp-user-frontend#1120]
I have to check for the dimensions (width, height) of images before they can be successfully uploaded.

I can successfully do this in PHP using wp_handle_upload_prefilter.
I can return an error using $file['error']

However, if the first file doesn't match width or height requirements,  plupload doesn't allow me to upload any more files, even with the correct dimensions and size.

What I want to do is trigger a plupload error via PHP, instead of returning the error via $file['error']

Could you direct me on how to do this? I have been trying it for the past week with no result. 

Any help will be highly appreciated, thanks

**Comment by zamandevs** [comment]
@telenova-code There are various place on the wp & popular plugin which use this filter nicely. you check one of them locaten wp-admin/includes/ms.php LN: 18 with function name 'check_upload_size'. you can find this filter located in wp-admin/includes/ms-admin-filters LN: 11 as add_filter( 'wp_handle_upload_prefilter', 'check_upload_size' );

**Comment by telenova-code** [comment]
Thanks for your reply zamandevs. However, my problem it is not using that wp filter (wp_handle_upload_prefilter), my problem is that after I use it, and it correctly returns an error because the image was not of the correct dimensions, the upload form stops working.
After the filter has done its job, the form won't let me upload anymore files. The only thing I can do is refresh the page and start again.
I believe the problem lies in the way the form handles uploads using plupload.js and WPUF_Uploader

BTW I am a PRO user, I have a lifetime licence

**Comment by zamandevs** [comment]
@telenova-code I will investigate it with care. BTW if you don't hesitate please create a support ticket and share your site credentials. this way i will get a real scenario which will help me to find out what's going on. besides if you able to add some screenshot or make a video. you can reply here with videos/screenshots or attach when creating a support ticket.

**Comment by telenova-code** [comment]
OK thanks @zamandevs , I will post a video ASAP. However, at the very core, what I need to do is to be able to check the dimensions (width and height) of an image and throw an error if the image doesn't meet the required dimensions.
If there is a way of doing this using JS without touching upload.js would be great. I have tried to override WPUF_prototype to no avail

PS: When I opened tickets in the past I got sent here on Github.

**Comment by telenova-code** [comment]
@zamandevs As you have suggested,  here's a screengrab of the issue. For the sake of clarity and testing, I am using the exact code taken from **ms.php** and only testing for size.
Eventually, I will need to test for width and height. I can successfully do this in PHP, but I run into the exact same issue as shown in the video.

Thanks for your help

https://user-images.githubusercontent.com/85599508/123479362-70582d80-d5c6-11eb-8a65-66168f0f7464.mov

**Comment by zamandevs** [comment]
@telenova-code I've seen your code which seems fine. tested on my side & everything is fine i.e file is uploading properly if no error found for that specific file. 
you can create a support ticket & I can check what exactly happened on your end which I might miss.

**Comment by telenova-code** [comment]
@zamandevs thanks for this. As you can see in the video, the problem happens when the first file to be uploaded gives an error. After that, no matter what file I try to upload, even if it respects the requirements, it cannot be uploaded, it shows the progress bar and nothing else.
I will open a ticket later today
