### ISSUE TITLE
Active Tab doesn't contain the newly introduced Custom Post for the Account option or the previous "Post" tab.

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1121]
**Description:**
With the new version (3.5.17), you will see the Active Tab doesn't contain the newly introduced Custom Post for the Account option or the previous default "Post" tab.

**To reproduce:**
1. Go to your User Frontend Account settings - https://ibb.co/rfJyBm6
2. You will see the Active Tab is missing the Post/Custom post tabs option.

**Relevant SS:**
https://ibb.co/rfJyBm6

**Side note**:  Also, kindly keep this [reported issue](https://github.com/weDevsOfficial/wp-user-frontend/issues/1117) on deck, so nothing slips later.

**Comment by mmarj** [comment]
@zamandevs Bhai, while checking the issue. Please keep in mind that we need to handle another `Posts` link over our Account  → Dashboard → Posts https://ibb.co/StLyRtB.

**Comment by zamandevs** [comment]
Fixed [HERE](https://github.com/weDevsOfficial/wp-user-frontend/pull/1124)
