### ISSUE TITLE
Revise new UI-designed CSS & also the WPUF account fonts override into the 'Open Sans' due to explicit use of !important with the WPUF CSS

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1125]
The new UI design brings a few !important tags with the CSS, making the output fonts unpleasant for users.

**Description:**
1. From the latest version (V3.5.17), we introduce the new UI design. Which introduces the `font-family: 'Open Sans,' sans-serif !important;` with the class `.wpuf-dashboard-container` (Line-1220-1224). Also, the main `body` using font-family is important (Line-3).

2. Explicit use of !important tag. Line-(1301-1309) body .wpuf-dashboard-container table.items-table 

_File reference_: `wp-content/plugins/wp-user-frontend/assets/css/frontend-forms.css.`

**Comment by Anticosti** [comment]
They are not quick to fix what they brake. I would not expect a fix before 2022.

**Comment by zamandevs** [comment]
Fixed on the release.
