### ISSUE TITLE
Forms - Custom Redirect - https://xxxxx.org/wuf-account-page/?section=post

### ISSUE THREAD

**Issue by rickgravelin** [weDevsOfficial/wp-user-frontend#1126]
Before last upgrade this used to be https://xxxxxx.org/wuf-account-page/?section=posts.  Screen title says "Posts".   My 52 Forms are coded to use 'posts'.  Is this an error or are you planning to keep it 'post' , singular?  Asking before I change them all.

**Comment by zamandevs** [comment]
@rickgravelin Generally WP shows the current page/post title as the document title. if you still want to modify it wp has some hooks. can do it yourself. 

If this reply doesn't help you don't hesitate to reach us with your necesseties.
