### ISSUE TITLE
Use resumable.js

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/WP-User-Frontend#113]
There is a problem with uploading photos whenever we have interrupted the internet the data lost and the uploading skipped till the internet comeback.

**i.e.** I am uploading 3 pictures if the internet is ok then the first picture will be uploaded without any problem but if we face interrupted internet at the same time of uploading the second picture then it will be skipped and the third one will start whenever the internet comeback.

this will cause missing some pictures if we are uploading too many.

I suggest to resumable.js

**Comment by Sk-Shaikat** [comment]
Maybe we really can't implement this due to technical limitation
