### ISSUE TITLE
WPUF Generating wpuf-preview private page upon saving any post or registration form

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1137]
→ This issue came up from the newest version-3.5.17. 

**How to reproduce:**
1. Navigate to your User Frontend > Select any existing Post Form or Registration Form.
2. Save the form and visit your > Pages
3. You will see a page called "wpuf-preview" has generated as a "Private" page.

_Note: this is happening for the Post Form or Registration Form both._

**Reference Screencast:**
Please [watch this](https://drive.google.com/file/d/1SgQDIz3vLCNjChBelTN7HgvIKhihd-Iv/view?usp=sharing).

**Expected Behaviour:**
However, it should not auto-generate any pages upon saving the Post Form from the builder.

**Comment by zamandevs** [comment]
Fixed [HERE](https://github.com/weDevsOfficial/wp-user-frontend/pull/1123)
