### ISSUE TITLE
Subscription ID and Transaction ID not assigned when "Free trial" is enabled

### ISSUE THREAD

**Issue by reptilering** [weDevsOfficial/wp-user-frontend#1139]
Hello subscription and transaction ID are now working for subscription packs with 3.4.7. However when free trial is enabled no subscription ID or transaction ID is given. This is necessary for our website as they will need a subscription ID to access their store dashboard. If there is no subscription ID during free trial they will have to wait 30 days to access their account. Please let me know how I can get subscription and transaction ID upon purchase with the free trial enabled…… I reached someone from wedevs and they asked for the subscription ID and transaction ID but there is none. That is the problem. No subscription ID or transaction ID are given to the user when free trial is enabled. 

I need the subscription ID and transaction ID assigned immediately for those who subscribe to our free trial. Note I have Dokan pro and WPUF pro

**Comment by zamandevs** [comment]
@reptilering If you please provide in detail i.e which gateway, how you set up trial. you can share a screencast/video thus we can investigate what happened. besides, you can create a support ticket.
