### ISSUE TITLE
Billing address (wpuf_address_fields) data is not syncing with the Account Page > Billing Address of WPUF

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1141]
**Details/How to reproduce:**
1. Say you have already the Billing Address option enabled for the WPUF > Account page, and your/users updated the Billing Address accordingly. Now
2. Try to purchase a subscription pack of WPUF. Next on the payment page, insert your Billing Address (_ a different address to check the output_).
3. Complete the purchase and visit your **WPUF Account > Billing Address** tab. You will see the Billing Address you inserted on the payment page. It didn't sync/save here.
4. Same goes for a logged-out user when he purchased a subscription. It's not syncing/saving the Billing Address data to your WPUF > Billing Address Page.

**Current Behaviour:**
Billing address (wpuf_address_fields) data is not syncing with the Account Page > Billing Address of WPUF.

**Expected Behaviour:**
It should always save & sync the billing address between the Payment page and WPUF Account page > Billing Address Tab.

**Screencast:**
You can [watch this video](https://drive.google.com/file/d/1lR1hUAR4FAvmh6tZtYt8EtxmbMxo8juL/view?usp=sharing) for a closer look.

**Expected behaviour:**
This should sync the data according to the given information while making a purchase.

**Site info:**
WordPress - Version 5.7.2
WP User Frontend - Version 3.5.18

**Comment by Anticosti** [comment]
Very well expressed. Can't wait for this to work.

**Comment by MimiDev** [comment]
Lovely to see this has been rectified. Thank you.
I guess we'll only see it on the next WPUF update?  ...if so, is there any chance of getting updated file(s) in the interim, as I'm about to launch a new site with a client and would be nice to have this functionality in order please?
