### ISSUE TITLE
New Tax option WP Front End Pro does not save entered data. 

### ISSUE THREAD

**Issue by rickgravelin** [weDevsOfficial/wp-user-frontend#1143]
New Tax option WP Front End Pro does not save entered data.   Also, lots of warning errors in log.  

[kofcvtorg-install-info20210717.txt](https://github.com/weDevsOfficial/wp-user-frontend/files/6835206/kofcvtorg-install-info20210717.txt)

[error_log 20210717.txt](https://github.com/weDevsOfficial/wp-user-frontend/files/6835209/error_log.20210717.txt)

rick

**Comment by zamandevs** [comment]
@rickgravelin If you please provide us details/screencast which situation you face this errors. didn't produce on our end.  
don't hesitate to share your site details through our [Support](https://wedevs.com/contact).
