### ISSUE TITLE
setting for pay-per-post message

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/wp-user-frontend#1145]
The message that showing above the post form "There is a $0.00 charge to add a new post." that looks very unprofessional, and there is no way to edit it. Its better to have a setting for the text, and the message should go down to the bottom of the post form which is the standard way to display the payment information.

**Comment by zamandevs** [comment]
@leew999 There is a filter named wpuf_ppp_notice. more On the [HERE](https://github.com/weDevsOfficial/wp-user-frontend/blob/69260d8d2bec001de11ff3e4ae24080b77391ae6/class/subscription.php#L1005)
