### ISSUE TITLE
Error after upgrade to 3.5.19

### ISSUE THREAD

**Issue by LauridsPetersen** [weDevsOfficial/wp-user-frontend#1147]
Hi

After upgrading to 3.5.19 I get following error (Warning: Illegal string offset 'slug'):

![WP_User_Frontend_error](https://user-images.githubusercontent.com/39841209/127529195-038edcde-926d-4d85-9120-fff8fcabf783.JPG)

If I set the value "Edit Profile" to ON (on "My Account") the error disappears.
And when I set the value of "Edit Profile" to Off the error recurs

![WP_User_Frontend_setting](https://user-images.githubusercontent.com/39841209/127528851-08c89c76-863f-43fc-bf26-a1fb9700f1f1.JPG)

I am using WordPresss 5.8

**Comment by zamandevs** [comment]
@LauridsPetersen  Although it shouldn't happen, Checked again myself. but couldn't found what you stated. still if you face this issues don't try to reach us through our [Support](https://wedevs.com/contact).
