### ISSUE TITLE
remove absolute url limit for website & website URL field

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/wp-user-frontend#1148]
most of the web users dont have the knowledge for input the  absolute url , especially for the woman users.  but without entering the absolute url , the website/website URL field doesn't work, this is a big problem for creating the post form when there is URL field. lots users will have problem for how to input the field.

**Comment by mmarj** [comment]
@leew999  This validation thing may vary from user to user. Previously, the `Website URL` field did not explicitly validate the absolute URL, but few users reported that, and we added the validation more explicitly.

So if you want to get a website URL with less validation, you can use the plain `Text Field` as an alternative. Anyway, you can check [this PR](https://github.com/weDevsOfficial/wp-user-frontend/commit/2595c8b1e60e43e527185a421cd7fe4e4fd0cd38) and alter the file includes/fields/class-field-URL.php-L43

I'm sorry it won't modify further on the core.
Thanks!

**Comment by leew999** [comment]
1: Why don't provide a simple option for admin to choose whether use absolute or relative option, OR you can transfer the relative url to absolute URL after user save the post, but not stop the user just with a message which they don't know how to deal with. 
2: On the registration form, I see the website field support the relative URL, why there is different standard here
3: Text field don't have the link function, 
4: website URL is the only link field,  For the bigger community, there will be lots users doesn't know how to deal with this, I am using few URL fields on registration form,  users has problem can't go through this step.

**Comment by mmarj** [comment]
@zamandevs Bhai, can we enhance this for better usability? Would you please check this out?
Thanks :)

**Comment by leew999** [comment]
any update for this ?

**Comment by zamandevs** [comment]
@leew999 Will handle on coming release.
