### ISSUE TITLE
List of active/inactive subscribers

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/wp-user-frontend#115]
List of active/inactive subscribers

![screen shot 2017-10-23 at 15 32 04](https://user-images.githubusercontent.com/153669/31882089-7d2b110c-b807-11e7-9a70-79da79336341.png)

We also should be able to cancel an active subscription.

**Comment by Sk-Shaikat** [comment]
https://github.com/weDevsOfficial/wp-user-frontend/commit/5a59d8a756092c75d3046a47b2171bc805264426
