### ISSUE TITLE
PHP Notice on blog posts' page from Payment class

### ISSUE THREAD

**Issue by mayeenulislam** [weDevsOfficial/wp-user-frontend#1150]
In my setup the Payment is inactive, and there's no published blog entry. So the blog posts' page is empty. In this scenario there is a PHP notice appearing from the Payment class:

```php
Notice: Trying to get property 'ID' of non-object in \wp-content\plugins\wp-user-frontend\class\payment.php on line 87

Notice: Trying to get property 'ID' of non-object in \wp-content\plugins\wp-user-frontend\class\payment.php on line 87
```

As there is no post, the `global $post` is empty, hence the notice is appearing. An early bail out could be a solution.

**Comment by zamandevs** [comment]
What you stated above is not an issue at all, but it's in the issue list. 
WP manages content. so empty content is not obvious. besides, there are hundreds of notices in WP core.
