### ISSUE TITLE
Post edit success message is mixing up if the new status is set to 'pending'

### ISSUE THREAD

**Issue by mayeenulislam** [weDevsOfficial/wp-user-frontend#1151]
In **Posts Forms &raquo; [myform] &raquo; Settings &raquo; Edit Settings**, in "**Set Post Status to**", if I set it to "**Pending**", after a successful edit, the success message came instead with a warning:
> You can't edit a post while in pending mode.

Actually, the modification/edit is saved, but the success message is mixing up with other `transition_post_status`.
Please note that, I can only edit a post when it's published. So I'm trying to edit a published post and the warning is appearing.

**Comment by zamandevs** [comment]
@mayeenulislam Although it's not possible what you stated above, I've tested again as you describe couldn't produce on my end. if it's still valid on your end please help us to provide more details on what exactly happened and how. 

Thanks for your contribution.
