### ISSUE TITLE
[Feature] Disable post-editing while post in "published" status

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1163]
Allow users to disable post-editing for the end-user while post in "published" status.

**Description**: 
Currently, we facilitate an option called "Disable post editing while post in "pending" status" - https://prnt.sc/1qatqtn. However, depending on the site's use-cases user also needs to disable the editing while the post is in "published" mode.

**Comment by zamandevs** [comment]
@mmarj Please provide scenario. how & where it should apply and mention scope i.e on post form, or global or user-wise etc..

**Comment by mmarj** [comment]
@zamandevs here it is, Bhai:

**Use case**:
Scenario 1 for global use-case: 
Say you want to make your blogging platform uneditable for the author after published posts. I believe this case would be the best fit for the overall situation.

Implementation:
IMO, it should implement global (Dashboard) settings like our existing option "Pending Post Edit".

*Similar to "Published Post Edit" https://prnt.sc/21vwjtf.

After enabling the function, the user can't have the edit button on the frontend dashboard to edit any posts/CPTs (https://prnt.sc/21vxhw9).
