### ISSUE TITLE
Make content_limit_message translate-able

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1165]
**Description:**
We have a Content Restriction feature with the text/text-area fields, which display error messages once the limit cross (https://prnt.sc/1qe1l6i). However, these relevant strings are not translatable.

These strings(_[file ref](https://github.com/weDevsOfficial/wp-user-frontend/blob/d5abc3fc56dc4f424bbf5ea0795618ee514bc5a8/assets/js/frontend-form.js#L994)_) are needs to include with the POT file to let the end-users translate those message.

**Comment by zamandevs** [comment]
Fixed on the release
