### ISSUE TITLE
[Bug] Adding a featured image disables the submit button

### ISSUE THREAD

**Issue by RamseyKal** [weDevsOfficial/wp-user-frontend#1175]
Hi team,

As the title says, when someone is filling a form to add a blog post to our website, they fill the title, add a featured image, content, tags, meta info, and such fields. If they do not add the featured image, they can submit for review.
If they add a featured image, the button is disabled. You cannot click it.

This was an issue previously in the **past years** but you had fixed it this year (we were happy as we were tired of repeating the same thing to our bloggers). Now, with the recent update, the issue has resurfaced and I have bloggers confused and frustrated about this.

You can test this here: https://tribulant.com/blog/free-collaboration/

Thanks in advance!

**Comment by zamandevs** [comment]
@RamseyKal Really sorry for the trouble. please create a [Ticket](https://wedevs.com/contact) on our support thus we can investigate and fix asap. 
N.B: There are plugins that cause this issue, need to hunt down which one are making issue in your regards.
