### ISSUE TITLE
Frontend post submissions with ACF fields does not save ACF field key

### ISSUE THREAD

**Issue by cschot** [weDevsOfficial/wp-user-frontend#1180]
I have also noticed that WPUF does not add a field_key entry to the post meta, which is required by ACF. This may be a separate issue, or it may be related.

_Originally posted by @rajeevkarora in https://github.com/weDevsOfficial/wp-user-frontend/issues/945#issuecomment-671291936_

**Comment by cschot** [comment]
I noticed this behaviour too.

I use a plugin named 'Admin Columns Pro' which allows customizing the columns shown in the backend posts overview.
I have some ACF fields in the columns, but their vailue is not shown. When I publish the post after review, the values are shown.

So I investicated this issue. When I manually add the field keys in the way of a hidden field, the values are shown immediately after submission, without saving the post from the backend first.

Can you make this a out of the box sollution? So the field keys are always saved automatically?

**Comment by cschot** [comment]
It looks likes this issue only applies for grouped acf fields.

**Comment by zamandevs** [comment]
@cschot Are you using the latest version? in the latest release, we've fixed ACF meta-related issues. so it should work as expected. besides is it happen if you change the meta key through another plugin or it happens by default. I would request you to [Contact](https://wedevs.com/contact) our support thus we can help you ASAP.
