### ISSUE TITLE
Account links etc. not displaying on mobile view

### ISSUE THREAD

**Issue by Elinth** [weDevsOfficial/wp-user-frontend#1183]
Hi there,
I am nearly there with this great solution for my website. 
When checking the pages from wp-user-frontend on my iphone all the link items (posts, dashboard, add post) are missing in the field. Also the Authorfield is not fully displayed and the table on the posts overview is missing except for the featured images
It is just not working well with an iphone, Is there some setting I have wrong?

So close though to make this work, would be sad to step away as I need a good mobile view

**Comment by zamandevs** [comment]
@Elinth There's shouln't be any issue what you stated above. so please check with latest version and still if you've face the same issue don't forget to reach us through our [Support](https://wedevs.com/contact)
