### ISSUE TITLE
ReCaptcha v2 and v3 are not working

### ISSUE THREAD

**Issue by Elinth** [weDevsOfficial/wp-user-frontend#1184]
Currently both ReCaptcha v2 and v3 are giving errors. This is in the free build. V2 brings you to a blank page and v3 gives a error message next to the Recaptcha image.

**Comment by Elinth** [comment]
I deleted recatcha keys and now I cannor acces my site anymore, could you help?

**Comment by mmarj** [comment]
Hi @Elinth 

We may need to examine the scenario closely. So would you mind reaching us [HERE](https://wedevs.com/contact) with your issue & site details? 

Thanks in advance!
