### ISSUE TITLE
Body style conflict

### ISSUE THREAD

**Issue by jweisman** [weDevsOfficial/wp-user-frontend#1193]
In [this commit](https://github.com/weDevsOfficial/wp-user-frontend/commit/1369e3deedbe75bc603e253d9ea0c504128dd5fc#diff-a3d3371cc4b32845da2d32c776552971983dd6865557b8d3b3ed75d6e20609a0L8) you moved your font-family to the body tag rather than . This is causing a conflict in my theme. 

Can this change be restored? Plugins generally don't include global styles.

**Comment by zamandevs** [comment]
@jweisman It shouldn't. will be fixed on the coming release.
