### ISSUE TITLE
Strange error message in MyAccount page

### ISSUE THREAD

**Issue by dankanic** [weDevsOfficial/wp-user-frontend#1195]
Hello, 
i have some wierd error message in front end, on page MyAccount. The error is 
"
Warning
: Undefined array key "section" in
/home/autopost/public_html/wp-content/plugins/wp-user-frontend/templates/dashboard/posts.php
on line
3
"
My webhost is runing php 8.0 if that is important.

**Comment by zamandevs** [comment]
@dankanic It shouldn't what you stated. you can [Contact](https://wedevs.com/contact) our support thus we can solve your issue as soon as possible.

**Comment by dankanic** [comment]
Hello, I found that this error is present only when php version is 8.0. Got back to 7.4 and its not showing anymore. Hope that will help to resolve it.

**Comment by zamandevs** [comment]
Using php 8. couldn't produce on my end. please share a screencast etc or communicate our [Support](https://wedevs.com/contact)
