### ISSUE TITLE
Spinning Icon

### ISSUE THREAD

**Issue by webmoi** [weDevsOfficial/wp-user-frontend#1197]
The icon, next to the enable/disable auto updating, does not stop spinning on a fresh install of Wordpress and User Frontend. Using php 7.4. Any thoughts on why?

![2021-11-13 (3)](https://user-images.githubusercontent.com/52388692/141646126-18e646d0-0e02-4bb2-aeae-567e58cfdc42.png)

**Comment by zamandevs** [comment]
@webmoi Thanks for your contribution. will fix on coming release.
