### ISSUE TITLE
multiple category fields not allowed ??

### ISSUE THREAD

**Issue by Wa0066999** [weDevsOfficial/wp-user-frontend#1200]
It looks like we can have only one category field, but in most of the case, we need to have multiple categories for each of the post, those categories can't be mixed into a single list. I see this is a very basic function for the content posting. if this can be added into the future version. otherwise the WPUF can't be used in most of the advance content system.

**Comment by zamandevs** [comment]
@Wa0066999 Thanks for your concern. as we map taxonomies with WP core/registered taxonomies, it doesn't make sense for multiple option for same taxonomy i.e category.  

We consider your queries if you please provide use case where it's exactly needed and for better demonstration provide some screencast etc. we will implement this if we get enough use case.

**Comment by Wa0066999** [comment]
Hi, we are running an online magazine, we have about 10 parent taxonomies, each of the taxonomy has about 10-30 terms, its almost impossible to put all parent/child terms into only one field. it must has multiple category field, each field will match with one of the parent taxonomy. otherwise we can't use user-frontend for the content management, each post will has multiple terms attached on it, this is quite basic for any content website.

**Comment by zamandevs** [comment]
@Wa0066999 We will consider this with priority. besides seems, there is a same issue [HERE](https://github.com/weDevsOfficial/wp-user-frontend/issues/1149). so consider this as duplicate
