### ISSUE TITLE
Compatibility with Pods Framework

### ISSUE THREAD

**Issue by lapalach** [weDevsOfficial/wp-user-frontend#1204]
The plugin ist not compatible with Pods Framework. It is possible to create a frontend form for custom post types with custom fields. But after submission, the custom fields can not be edited in the wordpress backend by editors and admins. No error message occurs, changes in the textfield are not updated.
It would be great if you make it compatible with Pods. It's just a small issue with huge impact.

**Comment by lapalach** [comment]
I found out thtat WPUF and Pods both populate custom fields. I had the WPUF custom fields tab hidden, wo i couldn't edit the custom pods fields. see screenshot.
![Uploading screencapture-igtanz-ost-ch-wp-admin-post-php-2021-11-19-12_36_02.png…]()

**Comment by zamandevs** [comment]
@lapalach Thanks for your query. couldn't understand your last message. what you stated above should work as intended. if anything went wrong, please reach us here or through our [Support](https://wedevs.com/contact).
We will consider your situation ASAP.
