### ISSUE TITLE
post expiration doesn't work when using  CPTUI ( bug )

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/wp-user-frontend#1205]
when attach user-frontend's post form to the custom content type CPTUI ( https://wordpress.org/plugins/custom-post-type-ui/ ) the expiration doesn't works, all of our expired post still alive on the site.

**Comment by zamandevs** [comment]
@leew999 What you stated above shouldn't happen. post expiration has nothing to do with CPTUI or other plugin cause it's related to wp posts table. we consider your problem and if it's still happen help us to find out by sharing more detail i.e screencast etc or contact our [Support](https://wedevs.com/contact). we will help you ASAP.
