### ISSUE TITLE
The string "Featured Image" doesn't translate for the mobile/responsive device

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1210]
The string "Featured Image" doesn't translate for the mobile/responsive device.

Screencast/Video: https://somup.com/crlfDf04uU

**Expected behaviour**: The translation should implied in any device.

**Comment by sapayth** [comment]
As you can see there are 2 different string text for responsive devices and desktops. The one with the colon is showing on the responsive devices. It works when we change the responsive text. The same thing applies to other headers such as Title, Status, Payment, Options.
![image](https://user-images.githubusercontent.com/15567340/145749028-e520925c-548f-4842-b7f5-043e913a8d15.png)
