### ISSUE TITLE
Forms editing or creation display

### ISSUE THREAD

**Issue by viczx** [weDevsOfficial/wp-user-frontend#1218]
Im usinng wordpres 5.8.2 with 8.0 php, the forms are not showing for editing and also can`t create or duplicate any.

![blank](https://user-images.githubusercontent.com/29782202/146599539-922a3430-48a2-43c6-a1ea-a4704d6a8d17.png)

**Comment by sapayth** [comment]
It is causing for the translation. In `wp-content/plugins/wp-user-frontend/admin/class-admin-settings.php`
please change line no: 88
to `$this->menu_pages[] = add_menu_page( __( 'WP User Frontend', 'wp-user-frontend' ), 'User Frontend', $capability, 'wp-user-frontend', [ $this, 'wpuf_post_forms_page' ], 'data:image/svg+xml;base64,' . base64_encode( '<svg width="83px" height="76px" viewBox="0 0 83 76" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="wpuf-icon" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g id="ufp" fill-rule="nonzero" fill="#9EA3A8"><path d="M49.38,51.88 C49.503348,56.4604553 45.8999295,60.2784694 41.32,60.42 C36.7400705,60.2784694 33.136652,56.4604553 33.26,51.88 L33.26,40.23 L19,40.23 L19,51.88 C19,64.77 29,75.25 41.36,75.26 L41.36,75.26 C47.3622079,75.2559227 53.0954073,72.7693647 57.2,68.39 C61.4213559,63.9375842 63.7575868,58.0253435 63.72,51.89 L63.72,40.23 L49.38,40.23 L49.38,51.88 Z" id="Shape"></path><polygon id="Shape" points="32.96 0.59 0 0.59 3.77 16.68 32.96 16.68"></polygon><path d="M68,0 L49.75,0 L49.75,16.1 L68,16.1 C68.74,16.1 69.39,17.1 69.39,18.24 C69.39,19.38 68.74,20.38 68,20.38 L49.75,20.38 L49.75,36.5 L68,36.5 C76,36.5 82.5,28.31 82.5,18.25 C82.5,8.19 76,0 68,0 Z" id="Shape"></path><polygon id="Shape" points="32.96 20.41 5.31 20.41 9.07 36.5 32.96 36.5"></polygon></g></g></svg>' ), '54.2' );`

**Comment by viczx** [comment]
awesome, thank for your support, i can see and edit my posts, but now i have another issue, when i try to save the changes, the page does not update and it does not save the updates.

**Comment by sapayth** [comment]
In `wp-content/plugins/wp-user-frontend/assets/js/wpuf-form-builder.js` please change line no 540 to: 
`if ( typeof tinyMCE !== 'undefined' && window.location.search.substring(1).split('&').includes('page=wpuf-profile-forms') ) {`

Both problems will be solved in the upcoming release.
**Next Step:**
If the problem still occurs please [contact our support here](https://wedevs.com/contact) so that we can take a closer look at your site with your credentials.

**Comment by viczx** [comment]
> In `wp-content/plugins/wp-user-frontend/assets/js/wpuf-form-builder.js` please change line no 540 to: 
> `if ( typeof tinyMCE !== 'undefined' && window.location.search.substring(1).split('&').includes('page=wpuf-profile-forms') ) {`
> 
> Both problems will be solved in the upcoming release.
> **Next Step:**
> If the problem still occurs please [contact our support here](https://wedevs.com/contact) so that we can take a closer look at your site with your credentials.

wow ty. i really appreciate your support. just a little comment, i opened a ticket but still waiting for support. 
ty again
