### ISSUE TITLE
On clicking "Insert/edit link (Ctrl+K)" icon, it scrolls down to footer everytime

### ISSUE THREAD

**Issue by ijdk-loop** [weDevsOfficial/wp-user-frontend#1219]
I have installed the plugin in one of my sites. Everything is working fine. I checked "Rich Text" on "Post Content". It is working fine in admin preview. But on real use, whenever I click on the "Insert/edit link (Ctrl+K)" icon, nothing happens and it automatically scrolls down to footer bottom. After that it happens every time, I scroll up to the  "Post Content" section, and it then comes automatically scrolled down to the footer bottom.
Please advise.
![Capture](https://user-images.githubusercontent.com/77895803/146830805-c788adc2-b1b0-440d-9298-e7cd251d5111.PNG)
.

**Comment by zamandevs** [comment]
@ijdk-loop It shouldn't be what you stated above. tested again and everything is fine on our end. please open a [Support](https://wedevs.com/contact) ticket so we can investigate what's wrong on your end.

**Comment by ijdk-loop** [comment]
it was happening due to amp was enabled in the page, i opted out amp from that page and things was resolved.
