### ISSUE TITLE
Error when I try to Edit, Create or Duplicate a form.

### ISSUE THREAD

**Issue by oari17** [weDevsOfficial/wp-user-frontend#1226]
https://incondicionalmente.com/wp-content/uploads/2022/01/Imagen1.png

The error appeared in the previous version, wait for the new version to see if it had been solved but it remains the same after updating.

**Comment by sapayth** [comment]
1. It is causing for the translation. In `wp-content/plugins/wp-user-frontend/admin/class-admin-settings.php`
please change line no: 88
to `$this->menu_pages[] = add_menu_page( __( 'WP User Frontend', 'wp-user-frontend' ), 'User Frontend', $capability, 'wp-user-frontend', [ $this, 'wpuf_post_forms_page' ], 'data:image/svg+xml;base64,' . base64_encode( '<svg width="83px" height="76px" viewBox="0 0 83 76" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="wpuf-icon" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g id="ufp" fill-rule="nonzero" fill="#9EA3A8"><path d="M49.38,51.88 C49.503348,56.4604553 45.8999295,60.2784694 41.32,60.42 C36.7400705,60.2784694 33.136652,56.4604553 33.26,51.88 L33.26,40.23 L19,40.23 L19,51.88 C19,64.77 29,75.25 41.36,75.26 L41.36,75.26 C47.3622079,75.2559227 53.0954073,72.7693647 57.2,68.39 C61.4213559,63.9375842 63.7575868,58.0253435 63.72,51.89 L63.72,40.23 L49.38,40.23 L49.38,51.88 Z" id="Shape"></path><polygon id="Shape" points="32.96 0.59 0 0.59 3.77 16.68 32.96 16.68"></polygon><path d="M68,0 L49.75,0 L49.75,16.1 L68,16.1 C68.74,16.1 69.39,17.1 69.39,18.24 C69.39,19.38 68.74,20.38 68,20.38 L49.75,20.38 L49.75,36.5 L68,36.5 C76,36.5 82.5,28.31 82.5,18.25 C82.5,8.19 76,0 68,0 Z" id="Shape"></path><polygon id="Shape" points="32.96 20.41 5.31 20.41 9.07 36.5 32.96 36.5"></polygon></g></g></svg>' ), '54.2' );`

2. In `wp-content/plugins/wp-user-frontend/assets/js/wpuf-form-builder.js` please change line no 540 to: 
`if ( typeof tinyMCE !== 'undefined' && window.location.search.substring(1).split('&').includes('page=wpuf-profile-forms') ) {`

Both problems will be solved in the upcoming release.

**Comment by sapayth** [comment]
I hope your problem is fixed. I am closing the issue for now. Feel free to open a new issue or communicate our [Support](https://wedevs.com/contact) if there is any query.

**Comment by alganoglumertcan** [comment]
I'm having the same problem. Even though I disabled all the plugins and the theme, I couldn't find the solution. Can you help me?

**Comment by sapayth** [comment]
Hello @alganoglumertcan,
Sorry to hear that you still get the problem. Please make sure you are using the latest version of WP User Frontend.
If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.
