### ISSUE TITLE
multiple payment selection for post form

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/wp-user-frontend#1229]
If we can have more than just one payment option.  like user can select to pay $10,$20,or $30 etc...  this will make the user-frontend a much better pay-to-post plugin. at the moment, the payment function is very limited, because whenever we need to have a payment from user, it need to have options for different purpose.

**Comment by zamandevs** [comment]
@leew999 Thanks for your comments. if you please describe to us how is this useful or how it should work. provide us scenarios so we can think about this in detail.

**Comment by leew999** [comment]
@zamandevs hi, whenever we let user to pay to post, there always be more than just one option, for any content management website, for example like user will pay $30 for create a basic post, $50 to create a standard post which including some promotional feature, and $80 to create a premium post which including all promotional feature.  this is a very standard practice for content posting website, at the moment, the user-frontend only has one payment option, in 90% of the case, this is not enough and we have to find another solution for this function. thanks

**Comment by mmarj** [comment]
@leew999 currently we provide PayPal & Stripe (_Pro feature_). What else (payment gateway) do you prepare to have on the list? Although we have a plan to integrate Authorize.Net in future.

**Comment by leew999** [comment]
@mmarj you misunderstand my question, I was talking about to have multiple payment cost options like user can select to pay $10, $20 or $30... at the moment, we can only have one cost setting like this https://imgur.com/a/byJo3CO , I suggest to have multiple cost options.

**Comment by mmarj** [comment]
@leew999 Got it. You are referring to a "Deposits & Partial Payments for your Subscription or PayPerPost transaction" like the [WooCommerce plugin](https://wordpress.org/plugins/tags/deposits/).

I doubt the feasibility in the WPUF subscription context. It can be a user-specific customization feature. Better hire an expert to achieve your expectation. I can't agree more to accept this as a plugin core feature [for now]. 

However, I am keeping this in my logbook as a feature request. We will re-think if we have more user requests.
Thanks!

**Comment by leew999** [comment]
@mmarj hi, I am not referring for the subscription, I am talking about for the pay-per-post. I donn't know how many user are using  the pay-per-post function for now, its very limited because there is only one cost option that can be used.
