### ISSUE TITLE
Payment Page Not Showing on Mobile

### ISSUE THREAD

**Issue by Paulbc0** [weDevsOfficial/wp-user-frontend#1231]
Hi,

I have configured the plugin to allow payments in particular for ‘Pay to Post’. When testing on a desktop/laptop it works fine. When you click the ‘Submit’ button on the form you are taken to the payment page and details for making the payment via PayPal are shown as expected.

However, when I test on a mobile device when you click the submit button you are ‘not’ taken to the payment page but given a message to say thank you for your submission and you have been sent an email.

I have re-checked the settings numerous times and do not know why it doesn’t work and show the payment page on a mobile device.

Any help would be greatly appreciated.

**Comment by sapayth** [comment]
Hello @Paulbc0,

We have rechecked and the feature is working on our end. Please update the plugin with the latest version and try again. 
If the problem still exists, feel free to contact us.
