### ISSUE TITLE
Unable to save any new registration form

### ISSUE THREAD

**Issue by teesan** [weDevsOfficial/wp-user-frontend#1232]
When trying to create or edit a registration form, I am unable to save. When the save button clicked it, it looks as if it is saving, but it never completes, the processing icon just stays there indefinitely.

![image](https://user-images.githubusercontent.com/69631956/150399388-39897ba7-117c-4ce2-b7cb-59c3ad2fa0c8.png)

**Comment by sapayth** [comment]
Hello @teesan,
Sorry for the inconvenience. In `wp-content/plugins/wp-user-frontend/assets/js/wpuf-form-builder.js` replace line no from `542 to 545` with the below code:
```
if ( typeof tinyMCE !== 'undefined' && window.location.search.substring(1).split('&').includes('page=wpuf-profile-forms') ) {
    var parentWrap = $('#wp-wpuf_verification_body_' + form_id + '-wrap');
    if ( ! parentWrap.hasClass('tmce-active') ) {
        $('#wpuf_verification_body_' + form_id + '-tmce').click();  // bring user to the visual editor
        $('#wpuf_welcome_email_body_' + form_id + '-tmce').click();  // bring user to the visual editor
    }
    $('textarea[name="wpuf_settings[notification][verification_body]"]').val(tinyMCE.get('wpuf_verification_body_' + form_id).getContent());
    $('textarea[name="wpuf_settings[notification][welcome_email_body]"]').val(tinyMCE.get('wpuf_welcome_email_body_' + form_id).getContent());
}
```
I hope this will solve the problem you are having. Feel free to notify us of any queries.

**Comment by Anticosti** [comment]
I am encountering the same exact issue. I have edited my `wp-content/plugins/wp-user-frontend/assets/js/wpuf-form-builder.js` file but... still the same issue.

**Comment by sapayth** [comment]
Sorry to hear that you still are getting the problem. As we checked, it seems working on our end. There might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.
1. Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
2. Use a default theme such as twenty-twenty.
3. Clear your site cache as well as the browser cache. Then try again.

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by Anticosti** [comment]
I will check that next morning...

**Comment by Anticosti** [comment]
@[sapayth](https://github.com/sapayth)
I desactivated all the plugins that I could and still having the issue :(
![Screen Shot 2022-02-17 at 15 42 46](https://user-images.githubusercontent.com/5446224/154570190-bb409ad1-e292-49b3-a270-683aba6ac8fe.png)

**Comment by sapayth** [comment]
I hope your problem is fixed. I am closing the issue for now. Feel free to open a new issue or communicate our [Support](https://wedevs.com/contact) if there is any query.

**Comment by teesan** [comment]
The provided code change fixed the issue for me

> Hello @teesan, Sorry for the inconvenience. In `wp-content/plugins/wp-user-frontend/assets/js/wpuf-form-builder.js` replace line no from `542 to 545` with the below code:
> 
> ```
> if ( typeof tinyMCE !== 'undefined' && window.location.search.substring(1).split('&').includes('page=wpuf-profile-forms') ) {
>     var parentWrap = $('#wp-wpuf_verification_body_' + form_id + '-wrap');
>     if ( ! parentWrap.hasClass('tmce-active') ) {
>         $('#wpuf_verification_body_' + form_id + '-tmce').click();  // bring user to the visual editor
>         $('#wpuf_welcome_email_body_' + form_id + '-tmce').click();  // bring user to the visual editor
>     }
>     $('textarea[name="wpuf_settings[notification][verification_body]"]').val(tinyMCE.get('wpuf_verification_body_' + form_id).getContent());
>     $('textarea[name="wpuf_settings[notification][welcome_email_body]"]').val(tinyMCE.get('wpuf_welcome_email_body_' + form_id).getContent());
> }
> ```
> 
> I hope this will solve the problem you are having. Feel free to notify us of any queries.

This fixed the issue for me, thanks.
