### ISSUE TITLE
Template not loading

### ISSUE THREAD

**Issue by tomaslefever** [weDevsOfficial/wp-user-frontend#1241]
after update, template is not loading when I execute this function:

add_filter( 'wpuf_account_sections', 'wpuf_my_page' );

function wpuf_my_page( $sections ) {
$sections = array_merge( $sections, array( array( 'slug' => 'my-page', 'label' => 'My Page' ) ) );

return $sections;
}

add_action( 'wpuf_account_content_my-page', 'wpuf_my_page_section', 10, 2 );

function wpuf_my_page_section( $sections, $current_section ) {
wpuf_load_template(
"my-page.php",
array( 'sections' => $sections, 'current_section' => $current_section )
);
}

**Comment by sapayth** [comment]
Hello @tomaslefever,
Sorry for the inconvenience. In the `wpuf_account_sections` filter, we can now add sections directly as an associative array. So changing the function `wpuf_my_page` with the below code should solve your problem.
```
function wpuf_my_page( $sections ) {
   $sections = array_merge( $sections, array( 'my-page' => 'My Page' ) );

   return $sections;
}
```
Feel free to notify us of any queries.

**Comment by sapayth** [comment]
I hope your problem is fixed and closing the issue. Feel free to open a new issue or communicate our [Support](https://wedevs.com/contact) if there is any query.
