### ISSUE TITLE
Lost password 

### ISSUE THREAD

**Issue by Ck222** [weDevsOfficial/wp-user-frontend#1242]
unable to reset password with this plugin

**Comment by sapayth** [comment]
Hello @Ck222,
Sorry to hear about your problem. The reset password option is working on our end. Please give us a step-by-step scenario of how you are trying so that we can reproduce if there is any problem.

**Comment by sapayth** [comment]
Hopefully, the problem is solved. Feel free to create a new issue or [contact us ](https://wedevs.com/contact) for any queries.
