### ISSUE TITLE
JSON-Error when updating pages

### ISSUE THREAD

**Issue by errotu** [weDevsOfficial/wp-user-frontend#1248]
First, thank you very much for your great plugin!

Unfortunately, I get an error very similar to #839, #840 and #857. Whenever I update a page (with the Gutenberg Editor), it actually saves the page, but throws out the error: "The response is not a valid JSON response."

I checked the browser console and noticed the following:

> POST https://site-domain.org/wp-admin/post.php?post=12&action=edit&meta-box-loader=1&meta-box-loader-nonce=ddc1000fcb&_locale=user Status 302 Found

Any ideas on how to fix this? I would guess it has something to do with me using custom fields in a post form of User Frontend.

**Comment by errotu** [comment]
It seems to be somehow related to the interplay of [Getwid](https://getwid.getmotopress.com/) and WPUF. On pages without any Getwid-Blocks, the error does not appear (there are actually no WPUF-elements on the page). However, it totally disappears when I deactivate WPUF.

**Comment by sapayth** [comment]
Hello @errotu,
Sorry for the inconvenience. We tried to reproduce the problem but it seems to work on our end. Can you please provide a step-by-step instructions so that we can reproduce the problem?

**Comment by errotu** [comment]
Hi @sapayth, thanks for your reply! I tried to dig a little deeper and it's kind of a mysterious error to me. It seems to be related to the length of the post somehow (not to Getwid, as the error also occurs on pages where I don't use Getwid blocks at all).

When I create a single page in Gutenberg (without any special blocks or anything) and I use the following text, I receive the JSON-error. However, whenever I remove two or more paragraphs from the text, the error disappears and I can save without any problem. Can you reproduce that?

---
<h1>Quid, quod homines infima fortuna, nulla spe rerum gerendarum, opifices denique delectantur historia?</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>Sed residamus, inquit, si placet.</b> <i>Quae est igitur causa istarum angustiarum?</i> <i>Sed quod proximum fuit non vidit.</i> Duo Reges: constructio interrete. <i>Gloriosa ostentatio in constituendo summo bono.</i> <b>Mihi, inquam, qui te id ipsum rogavi?</b> <mark>Nam, ut sint illa vendibiliora, haec uberiora certe sunt.</mark> <mark>Summus dolor plures dies manere non potest?</mark> Quodsi Graeci leguntur a Graecis isdem de rebus alia ratione compositis, quid est, cur nostri a nostris non legantur? Sin est etiam corpus, ista explanatio naturae nempe hoc effecerit, ut ea, quae ante explanationem tenebamus, relinquamus. </p>

<h4>Quoniam, si dis placet, ab Epicuro loqui discimus.</h4>

<p>Illa argumenta propria videamus, cur omnia sint paria peccata. <a href="http://loripsum.net/" target="_blank">[Si enim ad populum me vocas, eum.](http://loripsum.net/)</a> Sed qui ad voluptatem omnia referens vivit ut Gallonius, loquitur ut Frugi ille Piso, non audio nec eum, quod sentiat, dicere existimo. Ipse negat, ut ante dixi, luxuriosorum vitam reprehendendam, nisi plane fatui sint, id est nisi aut cupiant aut metuant. Quod mihi quidem visus est, cum sciret, velle tamen confitentem audire Torquatum. </p>

<h2>Deinde qui fit, ut ego nesciam, sciant omnes, quicumque Epicurei esse voluerunt?</h2>

<p><a href="http://loripsum.net/" target="_blank">[At multis se probavit.](http://loripsum.net/)</a> Quis est tam dissimile homini. Quippe, inquieta cum tam docuerim gradus istam rem non habere quam virtutem, in qua sit ipsum etíam beatum. <i>Ad eas enim res ab Epicuro praecepta dantur.</i> Nam si dicent ab illis has res esse tractatas, ne ipsos quidem Graecos est cur tam multos legant, quam legendi sunt. </p>

<p>Fortasse id optimum, sed ubi illud: Plus semper voluptatis? Hosne igitur laudas et hanc eorum, inquam, sententiam sequi nos censes oportere? Rem unam praeclarissimam omnium maximeque laudandam, penitus viderent, quonam gaudio complerentur, cum tantopere eius adumbrata opinione laetentur? Conclusum est enim contra Cyrenaicos satis acute, nihil ad Epicurum. Erit enim instructus ad mortem contemnendam, ad exilium, ad ipsum etiam dolorem. Quid affers, cur Thorius, cur Caius Postumius, cur omnium horum magister, Orata, non iucundissime vixerit? Etenim nec iustitia nec amicitia esse omnino poterunt, nisi ipsae per se expetuntur. Familiares nostros, credo, Sironem dicis et Philodemum, cum optimos viros, tum homines doctissimos. Si est nihil nisi corpus, summa erunt illa: valitudo, vacuitas doloris, pulchritudo, cetera. Sit, inquam, tam facilis, quam vultis, comparatio voluptatis, quid de dolore dicemus? Quod quidem mihi si quando dictum est-est autem dictum non parum saepe-, etsi satis clemens sum in disputando, tamen interdum soleo subirasci. <i>Equidem, sed audistine modo de Carneade?</i> </p>

<p>Magni enim aestimabat pecuniam non modo non contra leges, sed etiam legibus partam. Hoc non est positum in nostra actione. </p>

<p>Ergo id est convenienter naturae vivere, a natura discedere. Quid tibi, Torquate, quid huic Triario litterae, quid historiae cognitioque rerum, quid poetarum evolutio, quid tanta tot versuum memoria voluptatis affert? Sed ad bona praeterita redeamus. Hosne igitur laudas et hanc eorum, inquam, sententiam sequi nos censes oportere? Ne seges quidem igitur spicis uberibus et crebris, si avenam uspiam videris, nec mercatura quaestuosa, si in maximis lucris paulum aliquid damni contraxerit. Est autem officium, quod ita factum est, ut eius facti probabilis ratio reddi possit. Quid de Platone aut de Democrito loquar? Ut enim, inquit, gubernator aeque peccat, si palearum navem evertit et si auri, item aeque peccat, qui parentem et qui servum iniuria verberat. </p>

<p>Si ad corpus pertinentibus, rationes tuas te video compensare cum istis doloribus, non memoriam corpore perceptarum voluptatum; <i>Conferam tecum, quam cuique verso rem subicias;</i> <i>Quis est tam dissimile homini.</i> Me ipsum esse dicerem, inquam, nisi mihi viderer habere bene cognitam voluptatem et satis firme conceptam animo atque comprehensam. Sin laboramus, quis est, qui alienae modum statuat industriae? <a href="http://loripsum.net/" target="_blank">[At enim hic etiam dolore.](http://loripsum.net/)</a> Hic ego: Pomponius quidem, inquam, noster iocari videtur, et fortasse suo iure. Sin tantum modo ad indicia veteris memoriae cognoscenda, curiosorum. Quamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Nam et ille apud Trabeam voluptatem animi nimiam laetitiam dicit eandem, quam ille Caecilianus, qui omnibus laetitiis laetum esse se narrat. Vides igitur, si amicitiam sua caritate metiare, nihil esse praestantius, sin emolumento, summas familiaritates praediorum fructuosorum mercede superari. Sic enim censent, oportunitatis esse beate vivere. </p>

<h3>Quae hic rei publicae vulnera inponebat, eadem ille sanabat.</h3>

<p><i>Omnia contraria, quos etiam insanos esse vultis.</i> <a href="http://loripsum.net/" target="_blank">[Sed ad illum redeo.](http://loripsum.net/)</a> Atque his tribus generibus honestorum notatis quartum sequitur et in eadem pulchritudine et aptum ex illis tribus, in quo inest ordo et moderatio. A primo, ut opinor, animantium ortu petitur origo summi boni. <a href="http://loripsum.net/" target="_blank">[Quid, quod res alia tota est?](http://loripsum.net/)</a> -, sed ut hoc iudicaremus, non esse in iis partem maximam positam beate aut secus vivendi. Nam ista vestra: Si gravis, brevis; Primum non saepe, deinde quae est ista relaxatio, cum et praeteriti doloris memoria recens est et futuri atque inpendentis torquet timor? Non ergo Epicurus ineruditus, sed ii indocti, qui, quae pueros non didicisse turpe est, ea putant usque ad senectutem esse discenda. Quare si potest esse beatus is, qui est in asperis reiciendisque rebus, potest is quoque esse. Eorum enim est haec querela, qui sibi cari sunt seseque diligunt. </p>

<p>Is enim percontando atque interrogando elicere solebat eorum opiniones, quibuscum disserebat, ut ad ea, quae ii respondissent, si quid videretur, diceret. Quae iam oratio non a philosopho aliquo, sed a censore opprimenda est. Itaque illa non dico me expetere, sed legere, nec optare, sed sumere, contraria autem non fugere, sed quasi secernere. Quem si tenueris, non modo meum Ciceronem, sed etiam me ipsum abducas licebit. Polemoni et iam ante Aristoteli ea prima visa sunt, quae paulo ante dixi. Quibus natura iure responderit non esse verum aliunde finem beate vivendi, a se principia rei gerendae peti; Sunt autem, qui dicant foedus esse quoddam sapientium, ut ne minus amicos quam se ipsos diligant. Atque his de rebus et splendida est eorum et illustris oratio. </p>

<p>Hoc loco tenere se Triarius non potuit. Peccata autem partim esse tolerabilia, partim nullo modo, propterea quod alia peccata plures, alia pauciores quasi numeros officii praeterirent. <b>Si quae forte-possumus.</b> Quare, quoniam de primis naturae commodis satis dietum est nunc de maioribus consequentibusque videamus. Ita fit cum gravior, tum etiam splendidior oratio. Quae tamen a te agetur non melior, quam illae sunt, quas interdum optines. An potest, inquit ille, quicquam esse suavius quam nihil dolere? His similes sunt omnes, qui virtuti student levantur vitiis, levantur erroribus, nisi forte censes Ti. </p>
---

**Comment by sapayth** [comment]
Hello @errotu,
Thanks for your detailed description. I tried again with your instruction, sadly the problem not producing. Please [contact our support here](https://wedevs.com/contact) so that we can take a closer look at your site with your credentials.
