### ISSUE TITLE
Required Product Image field is not behaving as a required one in the WooCommerce Product upload form template.

### ISSUE THREAD

**Issue by nabid-anzum** [weDevsOfficial/wp-user-frontend#1253]
**Description:**
If Product Image field in the WooCommerce Product upload form template is set required, then it is not working as a required one. If user click the submit button of that form without populating the Product Image field, the form uploads the product. Product can be found in the db without Product image. 

**How to reproduce the issue:**
- Go to WP Admin Panel -> WP user Frontend -> Post Form -> Add Form
- Select the WooCommerce Product form template.
- Make sure that Product Image field is required https://snipboard.io/rMmftV.jpg
- Publish the form to a page.
- Submit a product by using this form from the frontend.
- Don't upload image in the Product Image field.
- It will upload the product without image, although image was required.

**Expected Behaviour:** 
The form should not let the user upload product without the image if Product Image field is required.

**System Status:**
WooCommerce: v6.3.1
WP User Frontend lite: v3.5.27

**Comment by sapayth** [comment]
Hello @nabid-anzum,

On `wp-content/plugins/wp-user-frontend/assets/js/frontend-form.js` file, please add the below code from `line no: 707`

```
// if this is a file upload field
if ( $(item).attr('type') && $(item).attr('type') === 'file' ) {
    var container = $(item).parent().siblings('.wpuf-attachment-upload-filelist');
    required = $(container).data('required');
    length = $(container).find('ul').children().length;

    if ( required == 'yes' && ! length ) {
        error = true;
        error_type = 'required';
        WP_User_Frontend.markError( container,  error_type );
    }
}

// if this is a radio field
if ( $(item).attr('type') && $(item).attr('type') === 'radio' ) {
    var container = $(item).parents('.wpuf-fields');
    required = $(container).data('required');
    length = $(item).find('input:checked').length;

    if ( required == 'yes' && ! length ) {
        error = true;
        error_type = 'required';
        WP_User_Frontend.markError( container,  error_type );
    }
}
```

Feel free to notify me of any queries.

**Comment by alganoglumertcan** [comment]
Hi,

This snippet does not make the image field mandatory. Is there anything else that needs to be changed?

**Comment by sapayth** [comment]
Hello @alganoglumertcan,
Sorry to hear that you still get the problem. As we checked, it seems working on our end. There might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.
1. Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
2. Use a default theme such as twenty-twenty.
3. Clear your site cache as well as the browser cache. Then try again.

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by ngigiGodfrey** [comment]
The above solution sorts my issue. I replaced the two files, frontend-form.js and frontend-form-min.js and it works fine now. the form doesn't submit without an image. Thank you team.
