### ISSUE TITLE
Missing string in the POT file

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1257]
Seems these strings are missing from the translateable [[wp-user-frontend.pot](https://github.com/weDevsOfficial/wp-user-frontend/blob/develop/languages/wp-user-frontend.pot)] file

1. ["View" and "Preview"](https://prnt.sc/IYxJcRj00bVC) from the Status column of the Post/Custom post dashboard
2. "[Unlimited](https://prnt.sc/4aas8i8Hpd8X)". _To reproduce it_: 
	i) Create a sub without any expiry date (https://prnt.sc/WgCom4dNr-e9).
	ii) Purchase the pack and now visit your Account > Subscription tab
	iv) You will have the string "Unlimited" on the pot file but it doesn't apply to this string (https://prnt.sc/j6gwOi-mVmCP)

![image](https://user-images.githubusercontent.com/5959265/161124004-6e61aa89-9e2d-42ca-a7f2-f2253ff905cd.png)
![image](https://user-images.githubusercontent.com/5959265/161128228-f2030391-9894-44ca-b00f-a99b932e2adf.png)

**Comment by Rat01047** [comment]
@anik-fahmid this issue needs to be rechecked
- for "Unlimited" translation is working but for "View" it is not.

**Comment by Rat01047** [comment]
This issue does not exist anymore.
