### ISSUE TITLE
Images are not showing when shared to social sites like FaceBook with Yoast SEO plugin.

### ISSUE THREAD

**Issue by nabid-anzum** [weDevsOfficial/wp-user-frontend#1259]
**Description:** 
Uploaded images are not showing in the social sites like Facebook when the post is shared to social site with Yoast SEO plugin. Yoast Seo plugin shows the post image if it is shared in social sites like FaceBook. But if a post with image is posted through WP User Frontend's form and shared in a social site like Facebook with Yoast SEO plugin, it doesn't show the image of the post. It only shows the site logo with the post.

**How to Reproduce:**
- Install and activate Yoast SEO plugin.
- Create a WP User Frontend post form with image upload/feature image field.
- Place that post form in a page.
- Now use that form to post.
- Then share that post to a social site like Facebook.
- The shared post in Facebook will not show the image of the post.

**Expected behaviour:**
When shared in faceBook, it should show the post image. If a default post with an image is created from the backend and shared in a social sites like Facebook then it shows the post image. So, post created with WP User Frontend forms should also show its images when shared in a social site like Facebook. 

**System Status:**
WPUF free: v3.5.27
WPUF pro: v.3.4.11
Yoast SEO: v18.5.1

**Comment by sapayth** [comment]
For the latest Yoast, it seems working now
