### ISSUE TITLE
"Live | View" on Desktop, becomes "Live|View" on Mobile

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#1261]
On Desktop:
![Screen Shot 2022-04-09 at 23 08 30](https://user-images.githubusercontent.com/5446224/162600055-76ace6b3-c2de-47a5-bae8-423e755bd88c.png)

On Mobile:
![Screen Shot 2022-04-09 at 23 08 52](https://user-images.githubusercontent.com/5446224/162600082-a6c6a593-5d92-44db-9166-c93de45362ec.png)

I tried ajusting with this CSS, but no success:
`@media (max-width:600px){
      td.data-column.flex-column span::after{
      margin-right: 0.5em!important;
      }
      td.data-column.flex-column a::before{
      margin-left: 0.5em!important;
      }
}`

**Comment by sapayth** [comment]
Hello @Anticosti,

On `wp-content/plugins/wp-user-frontend/templates/dashboard/posts.php` please replace the `line no: 169` with bellow code:

`echo apply_filters( 'wpuf_preview_link_separator', '&nbsp;|&nbsp;' );`

Hopefully, it will be updated in the upcoming release

**Comment by Anticosti** [comment]
Thank you @sapayth
Works perfectly.
