### ISSUE TITLE
Customer's Dashboard - Need to be able to change SVG icons color

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#1262]
In the Customer's Dashboard - I need to be able to change the SVG icons color
Tried everything with CSS but no success.
iPhone Landscape:
[https://snipboard.io/28oYKJ.jpg](https://snipboard.io/28oYKJ.jpg)
iPhone Portrait:
[https://snipboard.io/Vmn8c0.jpg](https://snipboard.io/Vmn8c0.jpg)

Kind Regards,

**Comment by sapayth** [comment]
Hello @Anticosti,
Please try the below CSS:
```
a.wpuf-posts-options svg path {
    fill: red;
}
```

Feel free to notify us if there are any queries.

**Comment by Anticosti** [comment]
Thank you @sapayth !
Works like a charm. Much appreciated.
