### ISSUE TITLE
Google Map not showing on frontend

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#1263]
Version 3.4.6

Hello,

the google map does not show on Frontend. In the form editor the map shows up.

Any suggestion?

Denis

**Comment by sapayth** [comment]
Hello @DenisCGN,
The latest WP User Frontend Pro version is 3.4.11. Please update your plugin. Feel free to notify us of any queries.

**Comment by DenisCGN** [comment]
@sapayth 

Hello, this is the answer from themify theme developer:

UPDATE: That plugin doesn’t work if jQuery is deferred (loaded in the footer). We’ve disabled this option: https://share.getcloudapp.com/p9u6ZvRZ and that plugin works now. Perhaps you should report the issue to the plugin’s developer (their plugin should work even jquery is loaded in footer).


Maybe you can take a look.

**Comment by sapayth** [comment]
Hello @DenisCGN,
We use jQuery to render the map. So it is important not to defer jQuery.
