### ISSUE TITLE
I want to make a request to add a feature to WP User Frontend.

### ISSUE THREAD

**Issue by eogmlgud13** [weDevsOfficial/wp-user-frontend#1268]
1. Feature request subject:
Ans:  I want to make a request to add a feature to WP User Frontend.

2. Description of the Feature request:
Ans:     
1)  I hope that the function of WP User Frontend Plugin has the function of canceling membership.

2)  We hope that you will also add Korean KakaoTalk and Naver social logins to the social functions in the module function of the WP User Frontend Plugin.

3. Is your feature request related to a problem? Any use-cases or target audiences? Please describe:
Ans:     
1) If there is a membership withdrawal function, it will be a high-quality plug-in.

2) If Naver and KakaoTalk social login were possible, the number of Korean users would increase significantly.

4. Describe the solution you'd like:
Ans:   WP User Frontend Plugin

**Comment by sapayth** [comment]
Hello @eogmlgud13,
Thanks a lot for your valuable suggestions.

1. By canceling membership, if you mean canceling a subscription, the user can do that. If the user visits the all subscription page (the page where `[wpuf_sub_pack]` shortcode is used), there is a cancel button to unsubscribe from the existing subscription.
2. We are adding KakaoTalk and Navar social login to our feature request list. If we get the same requirement for other users, we would love to add them in our social logins.

**Comment by eogmlgud13** [comment]
I received a reply and interpreted it, but I don't understand.
 
1. Is there a way for a member who signed up through WP User Frontend to delete their account on my website? (For example, is it possible to implement the account deletion function in CSS code or PHP code?)
 
2. Is there a way to add Korean KakaoTalk and Naver social logins to the social login function of WP User Frontend?
(For example, can I add KakaoTalk or Naver social login with CSS code or PHP code?)
 
 
-----Original Message-----

**Comment by sapayth** [comment]
Hello @eogmlgud13,

1. Sadly no. There is no option for a member to delete their own account. But we do have a plan to implement this feature.
2. Right now WP User Frontend doesn't have KakaoTalk and Naver social logins options.

**Comment by eogmlgud13** [comment]
Ok, i understand.     thanks  ^~^    (I hope that membership withdrawal and Naver KakaoTalk social login function will be added.) 
 
-----Original Message-----
