### ISSUE TITLE
Text limit error

### ISSUE THREAD

**Issue by lapalach** [weDevsOfficial/wp-user-frontend#1269]
When I copy/paste a long text into the textarea, the text limit (in my case 600 characters) throws a javasrcipt error.

![Screenshot 2022-05-05 095346](https://user-images.githubusercontent.com/17046159/166882907-30500a37-4bd8-42de-87f1-4f02b35907be.jpg)

**Comment by sapayth** [comment]
Hello @lapalach,
Sorry to hear about your problem. As we checked, it seems working on our end. There might be a conflict with another plugin or theme. Let's do a conflict test to be confirmed.
1. Please deactivate all plugins except the WP User Frontend and WP User Frontend Pro.
2. Use a default theme such as twenty-twenty.
3. Clear your site cache as well as the browser cache. Then try again.

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by sapayth** [comment]
Hello @lapalach,
Sorry to hear about your problem. Please replace your wp-content/plugins/wp-user-frontend/assets/js/frontend-form.min.js with [this file](https://gist.githubusercontent.com/sapayth/4b6828afc1aab41da6d79a623d5383eb/raw/698419a6bed39cc550413ef71abd8206b09e6088/frontend-form.min.js).

Feel free to notify us of any queries.

**Comment by lapalach** [comment]
Thank you. The error disappeared after replacing the file.

**Comment by lapalach** [comment]
We are still facing issue with the data upload in the frontend form. The error log shows the following. Could you please have a look at it. Thank you.

2022/05/20 11:09:36 [error] 65934#65934: *1161293 FastCGI sent in stderr: "PHP message: PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/svbm.ch/htdocs/wp-content/plugins/wp-user-frontend-pro/includes/class-frontend-account.php on line 92" while reading response header from upstream, client: 94.187.8.44, server: [www.svbm.ch](http://www.svbm.ch/), request: "POST /wp-admin/admin-ajax.php?nonce=d2becc8be9&type=stelleninserat__pdf HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php80-fpm-svbm.ch.sock:", host: "[www.svbm.ch](http://www.svbm.ch/)", referrer: "https://www.svbm.ch/stelle-inserieren/"
2022/05/20 11:09:43 [error] 65934#65934: *1161293 FastCGI sent in stderr: "PHP message: PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/svbm.ch/htdocs/wp-content/plugins/wp-user-frontend-pro/includes/class-frontend-account.php on line 92" while reading response header from upstream, client: 94.187.8.44, server: [www.svbm.ch](http://www.svbm.ch/), request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php80-fpm-svbm.ch.sock:", host: "[www.svbm.ch](http://www.svbm.ch/)", referrer: "https://www.svbm.ch/stelle-inserieren/"

**Comment by sapayth** [comment]
Hello @lapalach,
please contact our [Support](https://wedevs.com/contact) so that we can investigate the problem.

**Comment by sapayth** [comment]
Fixed in the latest release
