### ISSUE TITLE
The cancel subscription button doesn't work.

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/WP-User-Frontend#127]
The cancel subscription button doesn't work from the frontend.

**Comment by Sk-Shaikat** [comment]
There is no issue like this. Please check properly when create any issue.

**Comment by mahbubme** [comment]
I have checked again, it seems the subscription pack cancel option not working when users purchase pack using PayPal or Stripe payment gateways. However, it works fine if with Bank Payment option.

**Comment by Sk-Shaikat** [comment]
It was not an issue with subscription button. The issue was about 'recurring' pack. Non-recurring subscription pack cancels requests were sending to the gateway with 'undefine' value of profile_id which was creating the issue. Though the issue has been fixed.
