### ISSUE TITLE
The custom shortcode param for wpuf_dashboard is not working

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1270]
**Description:**
Follow [this doc's](https://wedevs.com/docs/wp-user-frontend-pro/getting-started/user-dashboard/) mentioned statement. 

_Quotes:_
> Note: Alongside with existing previous attributes you can pass any attributes which accept WP_Query (https://developer.wordpress.org/reference/classes/wp_query/) add this link for WP_Query except for attributes which accept multiple values i.e author__in, category__in which named used ‘__ ’. this shortcode accept author_in & category__in where you can pass username & category name in comma separated value. For example
> 
> `[wpuf_dashboard category='on' orderby='date' order=‘'desc' post_type='post' author__in='test_expiry,another_author' category__in='small shirts,shirts,new term,abcd']`.

You will see the shortcode with parameter is not rendering the expected output.

Screencast: Please [watch this](https://somup.com/c3h6rcO8gQ).

**Expected behavior:**
It should work fine as stated in the doc.

**Site info:**
WordPress 5.9.3
WooCommerce 6.5.0
Wp User Frontend Version 3.5.27

**Comment by anik-fahmid** [comment]
Similar/Duplicate issue: https://github.com/weDevsOfficial/wp-user-frontend/issues/1287
