### ISSUE TITLE
The option preservation state for the predefine items is not working for the read-only radio button and dropdown fields during post-editing

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#1273]
**How to reproduce:**
1. Create a form with the radio button and dropdown field.
2. Predefine an option and make the field read-only from the editor
3. Post the form.
4. Go to the account/post page and edit it using WPUF frontend editing mode.
5. You will see the radio button and dropdown fields data selection is empty. 

**Screencast:**
Watch this video of the situation - https://somup.com/c3hlrAOSfC

**Expected behavior:**
The option state should be set as selected with the associate value for the radio and dropdown field.

**Site info:**
WordPress V5.9.3
WPUF free: v3.5.27
WPUF pro: v.3.4.11

**Comment by sapayth** [comment]
Fixed in the latest release
