### ISSUE TITLE
WP User Frontend Pro - business - Bug with medias folders

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#1274]
I am using 60 plugins.
My setting at:
wp-admin/options-media.php
is checked:
**Organize my uploads into month- and year-based folders**
I was wondering why all the files I uploaded - since August 2020 - with **Media / Add New** are all located in the same folder:
wp-content/uploads/2019/03/

After 10 hours trying to find the culprit, I found out that as soon as I deactivate **WP User Frontend Pro - business** (Version 3.4.11) now the new files are uploaded to the good logic folder: 
wp-content/uploads/2022/05/

**Comment by zamandevs** [comment]
Fixed [HERE](https://github.com/weDevsOfficial/wpuf-pro/pull/401)

**Comment by Anticosti** [comment]
@[zamandevs](https://github.com/zamandevs)
Sorry. Your link above leads to a 404 page...

**Comment by zamandevs** [comment]
@Anticosti Due to the private repo you're seeing this. please open a support ticket and we will fix it for you asap. besides it will be available on the next release.
