### ISSUE TITLE
I like to see more flexibility in LABEL Position.

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/wp-user-frontend#128]
I like to have the choice, to have the label.

**Options:**

1. Above the fields
2. left to the fields but align right to the field
3. And maybe No Label

**Reference:** [https://wedevs.com/85355/live-preview-form-builder-wp-user-frontend/#comment-52010](https://wedevs.com/85355/live-preview-form-builder-wp-user-frontend/#comment-52010)

**Comment by tareq1988** [comment]
Added in v2.5.7
