### ISSUE TITLE
You do not have sufficient permissions to access this form.

### ISSUE THREAD

**Issue by janinewen** [weDevsOfficial/wp-user-frontend#1282]
I have set permissions according to https://wedevs.com/docs/wp-user-frontend-pro/posting-forms/guest-posting/ but its not working.

https://snipboard.io/FGfuzZ.jpg
https://snipboard.io/VgU7Mb.jpg
https://snipboard.io/bIcGJf.jpg

Website is douard.co.za/submissions

Thanks

**Comment by anik-fahmid** [comment]
I hope this is working (tested the link you posted and it's working). If you still have problems with specific points please [reach us](https://wedevs.com/contact/) or comment here.
