### ISSUE TITLE
The post forms ADD NEWS page is blank and doesn't show anything

### ISSUE THREAD

**Issue by ufo86817** [weDevsOfficial/wp-user-frontend#1285]
The post forms ADD NEWS page is blank and doesn't show anything

**Comment by fofen** [comment]
Same problem. WP 6.0.

**Comment by sapayth** [comment]
Hello @ufo86817 and @fofen,
Sorry to hear about your problem. Is your "Site Language" something other than "English"? You can find your "Site Language" from WordPress Dashboard > General Settings. If yes, please refer to [this solution](https://github.com/weDevsOfficial/wp-user-frontend/pull/1288).

[contact our support here](https://wedevs.com/contact) if you are having problem implementing the above solution or for any queries.

**Comment by Rat01047** [comment]
Any conflict due to Language change has been resolved in this [PR](https://github.com/weDevsOfficial/wp-user-frontend/pull/1288)
