### ISSUE TITLE
The variable products attributes remove option is not working when the WPUF plugin is activated.

### ISSUE THREAD

**Issue by Saifislam01** [weDevsOfficial/wp-user-frontend#1293]
**Description:**

WP User Frontend Plugin is conflicting with Dokan. For variable products, the attributes remove option is not working from the frontend of the Dokan dashboard when the WPUF plugin is activated.

**Here is the reference video:** https://www.loom.com/share/91014756ac694786b456d304bc8673a5

**System Status:**

Dokan free v3.6.3

Dokan Pro v3.7.3

WPUF free v3.5.28

**Comment by J-H-Mojumder** [comment]
It seems like it is a sweetalert-related problem. When the WPUF plugin is activated, the swals of Dokan are not working as we can see in [this video](https://www.loom.com/share/405370f5d91041a483a9a249ec513fba).

I hope this finding will help.

**Comment by tanjiralmamun** [comment]
@sapayth Bhai, it seems the WPUF Sweetalert scripts are loading on the vendor dashboard, which is unnecessary as WPUF does not have any work on the vendor dashboard. 
View Page Source screenshots of the Vendor Dashboard:
https://snipboard.io/LpskP5.jpg
https://snipboard.io/j96wxc.jpg

Also, WPUF is using an older Sweetalert2 version (v6.6.4 - https://snipboard.io/8Ak2yb.jpg) that conflicts with Dokan.

It would be better if WPUF Sweetalert scripts do not load on the vendor dashboard, along with upgrading the Sweetalert2 version to the latest version (v11.4.24) to get rid of this conflict.

Please take a look on this matter.
