### ISSUE TITLE
multiple price options for pay-per-post

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/wp-user-frontend#1294]
we only have one price option for pay-per-post,  this is limiting the possibility of the user-frontend, in many different cases, admin will like to have many different price options for pay-per-post, which can make the website a true pay to publishing system, please see this sample [https://imgur.com/a/0RIXe0b] which from a classified website, but from my experience, whenever admin want to charge user to pay to post, there will be many price options. I also seeing many requirements for this from users on other wp custom fields plugins, so I will suggest to add this into the future release which will make the user-frontend a full function custom fields plugin.

**Comment by leew999** [comment]
can this price options be a plugin of user-frontend, or even another payment plugin for wordpress but work with user-frontend. like this plugin [](https://en-gb.wordpress.org/plugins/woocommerce-pay-per-post/)

**Comment by sapayth** [comment]
We already support pay-per-post. Details [here](https://wedevs.com/docs/wp-user-frontend-pro/subscription-payment/how-to-charge-for-each-post-submission/). For many price options, we can think of a enhancement @anik-fahmid bhai, @saiftheboss7 bhai
