### ISSUE TITLE
'Required' attribute on image upload field not working. the form is submitting without an image

### ISSUE THREAD

**Issue by ngigiGodfrey** [weDevsOfficial/wp-user-frontend#1295]
I have created a frontend form for users to add products from the frontend. All the other fields in the form with a "required" * attribute throw a warning if the user does not type anything in the field. However, the product image upload still submits even without an image yet it is marked as 'required'.

**Comment by Saifislam01** [comment]
Hi, 

Thanks for getting in touch with us and sharing the details of your issues. This issue will be fixed in our upcoming release, but to get a quick solution you may follow this link: https://github.com/weDevsOfficial/wp-user-frontend/issues/1253
to resolve the issue.

Hope this will helps!

**Comment by ngigiGodfrey** [comment]
Hi,

This sorted my issue. Thank you!

Kind regards

**Comment by Saifislam01** [comment]
Hi, 

You're most welcome. I'm thrilled your issue was resolved.

Thanks.
