### ISSUE TITLE
Post is not creating by Save Draft button.

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/WP-User-Frontend#130]
**How to reproduce the issue:** 

1) Create a posting form
2) Enable **Post Draft** option from the form settings & save it.
3) Copy the form shortcode. Create a new page, paste the form shortcode in the page editor. Publish that page. 
4) View that page on the frontend. Try to submit a post by clicking on **Save Draft** button. After clicking, you can see a message where it says **Post Saved**. However, the post actually not saving.

**Comment by Sk-Shaikat** [comment]
Tested several times with all available options in form settings. Found no bug like this. An issue like this (created without testing) can only be waste of time. I recommend, please test properly before creating any issue.
