### ISSUE TITLE
Fatal error when edit the featured post 

### ISSUE THREAD

**Issue by hexie2108** [weDevsOfficial/wp-user-frontend#1315]
**Description**
When accessing the edit page of a featured post, the following exception is thrown:
Fatal error: Uncaught TypeError: Cannot access offset of type string on string in G:\xampp\htdocs\html\wp-content\plugins\wp-user-frontend\includes\class-frontend-render-form.php:911

**Reason**
if a user has metadata '_wpuf_subscription_pack'  with empty string ,  throw a exception if it tries to use as array

**File**
includes/class-frontend-render-form.php:911

**Version**
3.6.0

**Comment by sapayth** [comment]
commit [here](https://github.com/weDevsOfficial/wp-user-frontend/pull/1379/commits/62ccfc980ce997744907e73eaf8a3cbc362b79a2)
