### ISSUE TITLE
Error deleting the image when clicking cancel button in the delete confirmation window

### ISSUE THREAD

**Issue by hexie2108** [weDevsOfficial/wp-user-frontend#1316]
**Description**
When I open the confirmation window to delete image, both confirmation button and delete button delete the image.

![20221129214911](https://user-images.githubusercontent.com/40892639/204644753-054f095f-7598-47ca-8995-3c488b00755f.jpg)

**Possible solution**
Add a if statement like 
`if(!result.isConfirmed) return;`

**File**
assets\js\upload.js:199

**Version**
3.6.0

**Comment by sapayth** [comment]
Hello @hexie2108, sorry to hear about your problem. But for the image field and other fields, the `delete` and `cancel` buttons are working as expected on our end. please contact our [Support](https://wedevs.com/contact) so that we can investigate if this is a site-specific problem.

**Comment by hexie2108** [comment]
> Hello @hexie2108, sorry to hear about your problem. But for the image field and other fields, the `delete` and `cancel` buttons are working as expected on our end. please contact our [Support](https://wedevs.com/contact) so that we can investigate if this is a site-specific problem.

Hi, I recorded a video to illustrate the problem and I create a new  wordpress site that only  enabled wp-user-frontend, so you can check the problem.

[video link ](https://youtu.be/NrNB9IoEkaQ)
[demo site](http://mikuclub.altervista.org/order-received/)

**Comment by anik-fahmid** [comment]
Hello @hexie2108 , We are working on [this](https://github.com/weDevsOfficial/wpuf-pro/issues/502).

**Comment by Mohamedbenarbia** [comment]
I can confirm that I am experiencing the same problem mentioned in this issue. 
Both confirmation button and delete button delete the image.

 I have also attempted potential workarounds and I fixed it by changing the code bellow 

`.then(function (**result**) {

                **if (result.isConfirmed) {**

                    var data = {
                        'attach_id' : el.data('attach-id'),
                        'nonce' : wpuf_frontend_upload.nonce,
                        'action' : 'wpuf_file_del'
                    };
                    self.removed_files.push(data);
                    jQuery('#del_attach').val(el.data('attach-id'));
                    jQuery.post(wpuf_frontend_upload.ajaxurl, data, function() {
                        self.perFileCount--;
                        el.parent().parent().remove();

                        self.count -= 1;
                        self.showHide();
                        self.uploader.refresh();
                    });
                **}**
            });`
