### ISSUE TITLE
Save as Draft Not working

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/WP-User-Frontend#132]
After clicking on **Save as Draft** button, the post is awaiting approval rather than Draft.

**Comment by Sk-Shaikat** [comment]
If the setting option 'Charge for posting' checked in payment setting tab, then post status saved as pending for 'save as draft' button.

**Comment by mahbubme** [comment]
Ok, if the status is changed to **Pending** instead of **Draft** after clicking on **Save as Draft** button then there is another issue, the user who has active subscription pack cannot edit the post from frontend dashboard. **Users can edit post?** option is already enabled from dashboard settings of WPUF plugin.
