### ISSUE TITLE
Upgrading from 3.6.0 to 3.6.1 made my Post Status form go half width

### ISSUE THREAD

**Issue by markwaters** [weDevsOfficial/wp-user-frontend#1331]
Sorry , I am new to Wordpress Forms.
I made this simple form to post Status Posts from my sites Front Page.
The wp-user-frontend plugin automatically updated today and now the form is just half width.
I tried another theme and it is the same.
I tried the Rich Text Forms and those are the same too.
Rolled back to 3.6.0 and it works as before.
HTH
Mark.
Screenshots -
- [3.6.0](https://markwaters.neocities.org/20230106-wp-user-frontend-3.6.0-status-posting-full-width.jpg)
- [3.6.1](https://markwaters.neocities.org/20230106-wp-user-frontend-3.6.1-status-posting-half-width.jpg)

**Comment by anik-fahmid** [comment]
@markwaters seems okay from our end (3.6.3). Could you please check your form's display settings (WPUF>Form>Settings>Display Settings) and be sure that the label position is okay? Also please check the text field.

**Comment by markwaters** [comment]
Hi @anik-fahmid 
I upgraded this morning after seeing your reply , from 3.6.0 to 3.6.3 , without changing any settings and the form is showing exactly as I initially set it.
Thanks for fixing this.
Mark.
