### ISSUE TITLE
Required Asterix Password & View Password Inside

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#1334]
Required Asterix Password & View Password Inside

Hello,

please add the asterix for the required password. Can you put the eye icon inside the password field?

Thanks so much,
Denis

3.6.1 & 3.4.12

<img width="1295" alt="wedevs-registration-form" src="https://user-images.githubusercontent.com/2209723/213261603-9e0b6861-562e-453b-a3c8-e3edb68ac977.png">

**Comment by DenisCGN** [comment]
Asterix is there in the LIVE version missing only in the PREVIEW.

**Comment by anik-fahmid** [comment]
Hello! @DenisCGN 

We've noticed the issue you mentioned and are working on it. Hopefully, it will be fixed in your recent updates.
