### ISSUE TITLE
Wordpress Fatal Error: Version 3.6.2

### ISSUE THREAD

**Issue by kabirbd89** [weDevsOfficial/wp-user-frontend#1337]
When I update plugin to v3.6.2 (8 Feb, 2023) my site shows fatal error. And I goes back to previous version 3.3.1. And its shows the following code. It is a multiuser blog site and no ecommerce and or multivendor plugin are enabled. 

`Fatal error: Uncaught Error: Call to undefined function dokan_is_seller_dashboard() in /home1/junglteq/public_html/wstate/wp-content/plugins/wp-user-frontend/wpuf.php:668 Stack trace: #0 /home1/junglteq/public_html/wstate/wp-includes/class-wp-hook.php(308): WP_User_Frontend->enqueue_scripts('') #1 /home1/junglteq/public_html/wstate/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #2 /home1/junglteq/public_html/wstate/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /home1/junglteq/public_html/wstate/wp-includes/script-loader.php(2180): do_action('wp_enqueue_scri...') #4 /home1/junglteq/public_html/wstate/wp-includes/class-wp-hook.php(308): wp_enqueue_scripts('') #5 /home1/junglteq/public_html/wstate/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #6 /home1/junglteq/public_html/wstate/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #7 /home1/junglteq/public_html/wstate/wp-includes/general-template.php(3043): do_action('wp_head') #8 /home1/junglteq/public_html/wstate/wp-content/themes/unos/header.php(7): wp_head() #9 /home1/junglteq/public_html/wstate/wp-includes/template.php(783): require_once('/home1/junglteq...') #10 /home1/junglteq/public_html/wstate/wp-includes/template.php(718): load_template('/home1/junglteq...', true, Array) #11 /home1/junglteq/public_html/wstate/wp-includes/general-template.php(48): locate_template(Array, true, true, Array) #12 /home1/junglteq/public_html/wstate/wp-content/themes/unos/front-page.php(6): get_header() #13 /home1/junglteq/public_html/wstate/wp-includes/template-loader.php(106): include('/home1/junglteq...') #14 /home1/junglteq/public_html/wstate/wp-blog-header.php(19): require_once('/home1/junglteq...') #15 /home1/junglteq/public_html/wstate/index.php(17): require('/home1/junglteq...') #16 {main} thrown in /home1/junglteq/public_html/wstate/wp-content/plugins/wp-user-frontend/wpuf.php on line 668`

And line 668 in wpuf.php is, 

`                   || ( dokan_is_seller_dashboard() && isset( $wp->query_vars['posts'] ) ) ) {
`

As I do not use ecommerce and multivendor platform may i remove these line from wpuf.php and continue use plugin.

**Comment by sapayth** [comment]
please replace the `line no: 668` of `wpuf.php` file with the below line:
`|| ( class_exists( 'WeDevs_Dokan' ) && dokan_is_seller_dashboard() && ! empty( $wp->query_vars['posts'] ) ) ) {`

hope this will solve the problem. feel free to notify for any queries

**Comment by kabirbd89** [comment]
> please replace the `line no: 668` of `wpuf.php` file with the below line: `|| ( class_exists( 'WeDevs_Dokan' ) && dokan_is_seller_dashboard() && ! empty( $wp->query_vars['posts'] ) ) ) {`
> 
> hope this will solve the problem. feel free to notify for any queries

Problem solved for now.
