### ISSUE TITLE
E-mail notification content opimization

### ISSUE THREAD

**Issue by darker008** [weDevsOfficial/wp-user-frontend#1341]
many thanks for developing such plugin. 
as there is email notification to admin role after a new post is created. 
new I meet an issue. 
I found that all post content is included in email content, sothat email content is too long sometimes. I think only post link is enough.  
then I try modfiy the $mail_body  both in wpuf-user-frontend.php and form-element.php, 
but it doest work. 

what should I modify in source code, any advice could be provided?
thank you in advance.

**Comment by anik-fahmid** [comment]
You can edit email notification properties here in the form settings:

![image](https://user-images.githubusercontent.com/18075711/235670337-4fc7eaa4-64f1-4466-99d9-7eca4c8a6870.png)
