### ISSUE TITLE
Review begging notice shows on any admin page

### ISSUE THREAD

**Issue by elosha** [weDevsOfficial/wp-user-frontend#1352]
The admin notice (big nag screen) begging for a review shows on every admin page, regardless if it belongs to the plugin or not. For example on the posts page.

For professional environments it would be good to be able to disable any superfluous admin notices via filter. Looking at the source code there is more annoying stuff that can appear …

**Comment by anik-fahmid** [comment]
We really appreciate your feedback regarding the admin notice concern and will consider it for future enhancements.

**Comment by elosha** [comment]
"Not planned" – well, at least stick to the rules of conduct and keep it to your own admin pages, please.
