### ISSUE TITLE
fail on install

### ISSUE THREAD

**Issue by jost666** [weDevsOfficial/wp-user-frontend#1359]
PHP log file shows this error:

PHP Parse error:  syntax error, unexpected '=' in /home/<site>/wp-content/plugins/wp-user-frontend/includes/class-frontend-form-post.php on line 193

 Newest version of WP as of today

**Comment by sapayth** [comment]
Hello @jost666,

Sorry to hear about your problem. Can you please try with the latest version now? If the issue still exists, feel free to contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by sapayth** [comment]
Considering the issue resolved with our proposed solution. Closing it now. Feel free to reopen if needed.

Appreciate your collaboration!
