### ISSUE TITLE
Posted when edited

### ISSUE THREAD

**Issue by gregy1403** [weDevsOfficial/wp-user-frontend#1360]
I noticed that when user submit a post and post is waiting for publish then user edits post, this post will get published! Without admin!

Can you replicate this?

**Comment by sapayth** [comment]
Hello @gregy1403,

There is a setting regarding what you want to do when user edits a post. From the post form settings > Edit settings you can set post status to: `Draft, Pending Review, Private, Published and No Change`. When a user edits his post, the post status will change accordingly.

<img width="1397" alt="image" src="https://github.com/weDevsOfficial/wp-user-frontend/assets/15567340/d18aeaad-1c20-47d8-bb1d-c7d60d7159c0">

You can see a little more [here](https://wedevs.com/docs/wp-user-frontend-pro/posting-forms/post-form-settings/). Feel free to notify if there is any confusion.

**Comment by sapayth** [comment]
Considering the issue resolved with our proposed solution. Closing it now. Feel free to reopen if needed.

Appreciate your collaboration!
