### ISSUE TITLE
Recaptcha blocking wp admin

### ISSUE THREAD

**Issue by fernandonjardim** [weDevsOfficial/wp-user-frontend#1369]
Hi there!
I've recently added the recaptcha key under my settings, and now I cannot access wp admin
portugaltechweek.com/admin
any recommendations? Can I change something into the ftp, so I can get access back to wp?

**Comment by anik-fahmid** [comment]
We couldn't regenerate the issue. Could you please send some details like recorded video/screenshot?

**Comment by anik-fahmid** [comment]
We could login after adding recaptcha key under WPUF settings. Here is the reference video: [https://www.awesomescreenshot.com/video/19619115?key=cfc706db592aad7e897280c08ebe52e3](url)

**Comment by sapayth** [comment]
Hello @fernandonjardim ,
Considering the issue resolved with our proposed solution. Closing it now. If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

Appreciate your collaboration!
