### ISSUE TITLE
After clicking on Save as Draft button Post Body field data is not saving 

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/WP-User-Frontend#137]
How to reproduce the issue: 

Create a new posting form with **Post Body** field, select **Rich Textarea or Teeny Rich Textarea** option for this field and save the form. Submit a post by clicking on Save as Draft Button from the frontend. Check the submitted post in wp-admin, there is not data in the content field. However, this issue is not occurring when content field selected as **Normal** Textarea field.

[http://prntscr.com/fb0j70](http://prntscr.com/fb0j70)
[http://prntscr.com/fb0kqn](http://prntscr.com/fb0kqn)

**Comment by Sk-Shaikat** [comment]
Fixed this issue.
