### ISSUE TITLE
After Plugin update, error during publish custom post: Uncaught ReferenceError: tinymce is not defined

### ISSUE THREAD

**Issue by pillgrim** [weDevsOfficial/wp-user-frontend#1372]
After plugin update to version 3.6.6, i can't plublish or save a custom post (design Generatepress element). 

Uncaught ReferenceError: tinymce is not defined
    at HTMLFormElement.<anonymous> (wpuf-admin.js?ver=3.6.6:145:31)
    at HTMLFormElement.dispatch (load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.2.2:2:43184)
    at y.handle (load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,wp-polyfill-inert,regenerator-runtime,wp-polyfill,wp-hooks&ver=6.2.2:2:41168)

Do you can check this?

Thanks and regards

**Comment by pillgrim** [comment]
After plugin update to version 3.6.7 I can save the custom post.
But it's not possible to publish this post.

**Comment by sapayth** [comment]
> After plugin update to version 3.6.7 I can save the custom post. But it's not possible to publish this post.

Please replace `wp-user-frontend/assets/js/wpuf-admin.js` file with [this](https://raw.githubusercontent.com/sapayth/wp-user-frontend/f3cc568e661c55cae4cff37a9ccbb372abe5b302/assets/js/wpuf-admin.js) file. If the problem still exists, please [contact support](https://wedevs.com/contact/) so that the problem can be inspect more deeply

**Comment by vincenzost** [comment]
I had the same issue.
I rolled back to version 3.6.4 and the website works fine now.
But please release a fix so we can all update to the latest version.
Thanks.

**Comment by x2-j** [comment]
Had the same too. We rolled back and regained most functionality but there are still issues with this approach.
