### ISSUE TITLE
Error in log when loading dashboard with no section parameter

### ISSUE THREAD

**Issue by mavhc** [weDevsOfficial/wp-user-frontend#1375]
https://github.com/weDevsOfficial/wp-user-frontend/blob/develop/templates/dashboard/posts.php#L3C5-L3C5 tries to read the section GET parameter, but when the page loaded is just /profile/, and the default tab is posts, there is no section to get, which causes errors in the log.

PHP Notice:  Undefined index: section in /var/www/html/wp-content/plugins/wp-user-frontend/templates/dashboard/posts.php on line 3

**Comment by sapayth** [comment]
fixed in latest release
