### ISSUE TITLE
White blank page after log in

### ISSUE THREAD

**Issue by mhmdcg** [weDevsOfficial/wp-user-frontend#1396]
Hi, I always get the white blank page after logging in. I'm using WPUF login page. I even changed "Redirect After Login" page to different pages from the setting, but still not working!

**Comment by sapayth** [comment]
Hello @mhmdcg,
Sorry to hear about your problem. Please make sure you are using the latest version of WP User Frontend and WPUF pro.
If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by sapayth** [comment]
Considering the issue resolved with our proposed solution. Closing it now. Feel free to reopen if needed.

Appreciate your collaboration!
