### ISSUE TITLE
Logic error in if condition of function 'wpuf_get_child_cats'

### ISSUE THREAD

**Issue by hexie2108** [weDevsOfficial/wp-user-frontend#1398]
![20231125210707](https://github.com/weDevsOfficial/wp-user-frontend/assets/40892639/e2aae22b-dc88-4b00-a25b-3667ad2f24c6)

**Problem:**
Unable get response from action wp_ajax_wpuf_get_child_cat, because error is always returned when nonce is correct.

**Version:**
WP User Frontend 3.6.9

Cause:
wpuf-functions.php  line 1782
if  enter the true statement and throws an error when nonce is correct.
`
    if ( wp_verify_nonce( $nonce, 'wpuf_nonce' ) ) {
        wp_send_json_error( __( 'Permission denied', 'wp-user-frontend' ) );
    }
`

**Comment by sapayth** [comment]
Considering the issue resolved with our proposed solution. Closing it now. Feel free to reopen if needed.

Appreciate your collaboration!
