### ISSUE TITLE
Saving forms doesn´t work after activating Master Slider plugin.

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/wp-user-frontend#140]
Saving forms doesn´t work after activating [Master Slider](https://wordpress.org/plugins/master-slider/) plugin.

Refer Screenshot:
http://prntscr.com/fh92ff

**Comment by Sk-Shaikat** [comment]
https://github.com/moxiecode/plupload/issues/1163
http://www.plupload.com/punbb/viewtopic.php?id=1758
