### ISSUE TITLE
version 4/4.0.1 causes site to break with "There was a problem installing the plugin" error

### ISSUE THREAD

**Issue by SathyaBhat** [weDevsOfficial/wp-user-frontend#1402]
as mentioned by comments in https://wordpress.org/support/topic/there-was-a-problem-installing-the-plugin/ version 4/4.0.1 causes WordPress sites to break and throw a "There was a problem installing the plugin" even when trying to use the admin pages.

Only way is fix it at this point is to rollback to 3.6. or remove the wp-user-frontend directory in plugins (or move it elsewhere). 

Note: Might want to disable auto updates for plugins else it will break again

**Comment by clownguts** [comment]
I am also receiving the same error

**Comment by Anticosti** [comment]
Same here. Had to revert to Version 3.6.9
and WP User Frontend Pro Version 3.4.13

**Comment by Anticosti** [comment]
Updated the WP User Frontend to Version 4.0.2 : OK. All fine.
I currently have WP User Frontend Pro Version 3.4.14 : Should I upgrade to Version 4.0.0 ?

**Comment by sapayth** [comment]
Hello @SathyaBhat, @clownguts, @Anticosti,

Sorry to hear about your problem. Please make sure you are using the latest version of WP User Frontend[v4.0.3] and WPUF pro[v4.0.5]. As there are some major changes, please take a full backup of your site before updating the plugins.

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.

**Comment by Anticosti** [comment]
Hmmm... the latest version available in my pro account, is:
3.4.14
![image](https://github.com/weDevsOfficial/wp-user-frontend/assets/5446224/69882d66-26de-4f68-aa8b-e24b64bd8da0)

**Comment by Anticosti** [comment]
01. I had to revert from version 4.0.3 to 3.6.9 because when editing a CPT created with WPUF, it does not take me back to the page refreshed with the edit(s).
02. When I upgrade WP User Frontend Pro - appsumo to version 4.0.5
I then loose all my WPUF transaction pages and settings for my menus

**Comment by sapayth** [comment]
Hello @Anticosti,
You need to use WPUF 4.0.3 and WPUF Pro 4.0.5 at the same time.
