### ISSUE TITLE
Critical error when user tries to login

### ISSUE THREAD

**Issue by 006rodaal** [weDevsOfficial/wp-user-frontend#1410]
I have WP User Frontend V4.0.3 and the Pro plugin V4.0.5. When an user tries to login wordpress tries to login and says:
A critical error has occurred on this site.
This started to occur since update V4. What I've tried:

- I disabled all other plugins and tried to login but it didn't work;
- I activated a WP standard theme and tried to login but it didn't work;
- I tried to login with different user roles but it didn't work.

**Comment by sapayth** [comment]
Hello [user],

Sorry to hear about your problem. Please contact our [support](https://wedevs.com/contact) and share your credentials there so that we can check it in every possible way.

**Comment by 006rodaal** [comment]
Hi @sapayth thanks for your quick response. I contacted your support and I just got a response. But I did the update and it still doesn't work. My ticket number is #854002. I will provide the credentials so you can debug the problem.

**Comment by 006rodaal** [comment]
For me, logging in only works when I disable the core Wp User Frontend plugin.
