### ISSUE TITLE
Login Recaptcha V2 gives login error

### ISSUE THREAD

**Issue by 006rodaal** [weDevsOfficial/wp-user-frontend#1411]
Hi,

I found the following bug: When recaptcha V2 is enabled and you try to log in the following error page comes up 'A critical error has occurred on this site.'

I tested this on my live website and locally on a fresh wordpress installation and both have the exact same problem. It's solved by disabling recaptcha in the wp user frontend setings. 

I recommend fixing this asap as this will gives spammers and bots the change to create accounts.

**Comment by sapayth** [comment]
Hello @006rodaal,
Sorry we didn't find the ticket number you mentioned. You can send a mail at [support@wedevs.com](mailto:support@wedevs.com) or try below solution:
replace `wp-user-frontend/includes/Free/Simple_Login.php` this file with [this file](https://raw.githubusercontent.com/weDevsOfficial/wp-user-frontend/56df979c9f9ab5a139767c0295fa6995d63200ce/includes/Free/Simple_Login.php).

**Comment by 006rodaal** [comment]
@sapayth thanks for your response. I've tried your solution and that indeed solves it. Thanks :)
