### ISSUE TITLE
Editing an user profile in the wp backend gives a critical error

### ISSUE THREAD

**Issue by 006rodaal** [weDevsOfficial/wp-user-frontend#1414]
Hi,

We use WP user frontend V4.0.3 and Pro 4.0.5. The following problem occurs:
When an user has signed up they fill in certain aspects in their profile in the wp user frontend registration form. This is saved in their profile. When we edit this user in the wordpress backend and change something after saving we get a critical error. I've also tested this on a clean wp install and the same happens.

Can you create a solution for this? Thanks!

**Comment by 006rodaal** [comment]
@sapayth can you check this? Wordpress sent me an e-mail with the error:
Foutdetails =========== Een fout van het type E_ERROR werd veroorzaakt op regelnummer 124 van het bestand /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-content/plugins/wp-user-frontend-pro/includes/Admin/Posting_Profile.php. Foutmelding: Uncaught Error: Call to undefined method WeDevs\Wpuf\Pro\Admin\Profile_Form::update_user_meta() in /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-content/plugins/wp-user-frontend-pro/includes/Admin/Posting_Profile.php:124 Stack trace: #0 /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-includes/class-wp-hook.php(324): WeDevs\Wpuf\Pro\Admin\Posting_Profile->save_fields() #1 /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #2 /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-admin/user-edit.php(157): do_action() #4 {main} thrown

**Comment by sapayth** [comment]
Hello @006rodaal,

Sorry for your trouble. In `plugins/wp-user-frontend-pro/includes/Admin/Posting_Profile.php:124` file please replace line no `124` with below code:
`\WeDevs\Wpuf\Pro\Frontend\Profile_Form::update_user_meta( $custom_fields, $user_id );`

**Comment by 006rodaal** [comment]
Thanks, that works! I assume you also push this change to a new release from wp frontend pro?

**Comment by sapayth** [comment]
fixed in latest version
