### ISSUE TITLE
Error while changing an user role

### ISSUE THREAD

**Issue by 006rodaal** [weDevsOfficial/wp-user-frontend#1415]
@sapayth another error in the plugin:
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 124 van het bestand /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-content/plugins/wp-user-frontend-pro/includes/Admin/Posting_Profile.php. Foutmelding: Uncaught Error: Call to undefined method WeDevs\Wpuf\Pro\Admin\Profile_Form::update_user_meta() in /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-content/plugins/wp-user-frontend-pro/includes/Admin/Posting_Profile.php:124 Stack trace: #0 /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-includes/class-wp-hook.php(324): WeDevs\Wpuf\Pro\Admin\Posting_Profile->save_fields() #1 /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #2 /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /home/deb145809/domains/groenezorgalliantie.com/public_html/wp-admin/user-edit.php(157): do_action() #4 {main} thrown

**Comment by sapayth** [comment]
Hello @006rodaal,

Sorry for your trouble. In `plugins/wp-user-frontend-pro/includes/Admin/Posting_Profile.php:124` file please replace line no `124` with below code:
`\WeDevs\Wpuf\Pro\Frontend\Profile_Form::update_user_meta( $custom_fields, $user_id );`

**Comment by 006rodaal** [comment]
Thanks, that works! I assume you also push this change to a new release from wp frontend pro?
