### ISSUE TITLE
[Bug] Column field - Conditional logic not working

### ISSUE THREAD

**Issue by Rat01047** [weDevsOfficial/wp-user-frontend#1421]
Issue:
For Column-field the conditional logic is not working as expected

Scenario:
1. Create new Post-form
2. Add Column-field 
3. Click edit-Column-field > Click Advanced-options
4. There is no Conditional-logic option
5. Edit any other Post-forms-field > then Re-edit-Column-field and then Advanced-options
6. Now the Conditional-field is showing -> But it is not functioning

Video for reference:
https://www.awesomescreenshot.com/video/24321972?key=9e57238857e8bb2b1d0cb34d401b91cf

**Comment by anik-fahmid** [comment]
@Rat01047 vai, this issue should be closed as it's working now.

**Comment by Rat01047** [comment]
@anik-fahmid,
This issue does not exists anymore
