### ISSUE TITLE
Problem with images in post form

### ISSUE THREAD

**Issue by ManuWide** [weDevsOfficial/wp-user-frontend#1423]
Hi, I have a problem after the latest update of both the basic and Pro versions. Now if I edit a form it gives me this error. How can I solve it? Thank you Good work
Fatal error: Uncaught Error: Class "WeDevsWpufFieldsWPUF_Upload" not found in /home/sw4tookc/public_html/wp-content/plugins/wp-user-frontend/includes/Fields/Form_Field_Image.php:62 Stack trace: #0 /home/sw4tookc/public_html/wp-content/plugins/wp-user-frontend/includes/Admin/Forms/Field_Manager.php(229): WeDevsWpufFieldsForm_Field_Image->render() #1 /home/sw4tookc/public_html/wp-content/plugins/wp-user-frontend/includes/Frontend_Render_Form.php(266): WeDevsWpufAdminFormsField_Manager->render_fields() #2 /home/sw4tookc/public_html/wp-content/plugins/wp-user-frontend/includes/Frontend/Frontend_Form.php(131): WeDevsWpufFrontend_Render_Form->render_form() #3 /home/sw4tookc/public_html/wp-includes/shortcodes.php(433): WeDevsWpufFrontendFrontend_Form->edit_post_shortcode() #4 [internal function]: do_shortcode_tag() #5 /home/sw4tookc/public_html/wp-includes/shortcodes.php(273): preg_replace_callback() #6 /home/sw4tookc/public_html/wp-includes/class-wp-hook.php(324): do_shortcode() #7 /home/sw4tookc/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters() #8 /home/sw4tookc/public_html/wp-includes/post-template.php(256): apply_filters() #9 /home/sw4tookc/public_html/wp-content/themes/goliosi/template-parts/content-page.php(15): the_content() #10 /home/sw4tookc/public_html/wp-includes/template.php(792): require('/home/sw4tookc/…') #11 /home/sw4tookc/public_html/wp-includes/template.php(725): load_template() #12 /home/sw4tookc/public_html/wp-includes/general-template.php(206): locate_template() #13 /home/sw4tookc/public_html/wp-content/themes/goliosi/page.php(30): get_template_part() #14 /home/sw4tookc/public_html/wp-includes/template-loader.php(106): include('/home/sw4tookc/…') #15 /home/sw4tookc/public_html/wp-blog-header.php(19): require_once('/home/sw4tookc/…') #16 /home/sw4tookc/public_html/index.php(17): require('/home/sw4tookc/…') #17 {main} thrown in /home/sw4tookc/public_html/wp-content/plugins/wp-user-frontend/includes/Fields/Form_Field_Image.php on line 62

**Comment by anik-fahmid** [comment]
@Rat01047 please check to reproduce.

**Comment by anik-fahmid** [comment]
@Rat01047 if the latest versions don't produce this error, please close this issue.

**Comment by Rat01047** [comment]
@anik-fahmid,
This issue does not exist in our current versions for WPUF-lite and WPUF-Pro, as tested in my local
