### ISSUE TITLE
Error after PayPal payment

### ISSUE THREAD

**Issue by ashwebstudio** [weDevsOfficial/wp-user-frontend#1429]
After doing a payment with PayPal, I get the following error upon returning back to the website: 

PHP Fatal error:  Uncaught Error: Class "WeDevs\Wpuf\Lib\Gateway\WP_User_Frontend" not found in /app/public/wp-content/plugins/wp-user-frontend/Lib/Gateway/Paypal.php:496

**Comment by sapayth** [comment]
Hello @ashwebstudio,
Sorry to hear about your problem. Please replace `wp-content/plugins/wp-user-frontend/Lib/Gateway/Paypal.php` file with
[this](https://gist.githubusercontent.com/sapayth/0f6ad49ea7e957d72cd13ab567150fa4/raw/e759c6d2789c34b10923b01f304f17147aa2b9b3/Paypla.php)

Feel free to contact [support](https://wedevs.com/contact) if there is any assistance needed.
