### ISSUE TITLE
4.0.6 Pro - "math-captcha.css" generates a 404 error

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#1440]
I discovered in Google Chrome Network Console:

Loading my site,  it searches for this file and generates a 404error, thus slowing down my site: 
/wp-content/plugins/wp-user-frontend-pro/assets/css/frontend/**math-captcha.css**

**It's current location is here:**
/wp-content/plugins/wp-user-frontend-pro/assets/css/frontend/**fields/math-captcha.css**

**Solution:**
Copied "math-captcha.css" to the parent folder:
/wp-content/plugins/wp-user-frontend-pro/assets/css/frontend/math-captcha.css

Thank you for fixing this in the next update.

Kind Regards,

**Comment by anik-fahmid** [comment]
@Rat01047 vai please test this and assign.

**Comment by Rat01047** [comment]
@sapayth bhai, 
Can you look at this.
I was not able to recreate this in my Local-setup

**Comment by sapayth** [comment]
fixed in the latest release
