### ISSUE TITLE
4.06 Pro - Error

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#1441]
I have a page where I inserted (Classic Editor) this shortcode [wpuf_form id="780"] for the form that Authors have to use to post a new CPT listing.

Issue:
Just the first field appears (out of 40 + fields) on a blank page and without any CSS formatting.

In my "error.log" file, 
this is what is been generated at each reload I try:
////////////////////////////////////
[19-Feb-2024 19:47:52 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WeDevs\Wpuf\Admin\Subscription::init() in /home/myuser/public_html/wp-content/plugins/wp-user-frontend/includes/Admin/Forms/Field_Manager.php:271
Stack trace:
#0 /home/myuser/public_html/wp-content/plugins/wp-user-frontend/includes/Admin/Forms/Field_Manager.php(227): WeDevs\Wpuf\Admin\Forms\Field_Manager->check_field_visibility(Array)
#1 /home/myuser/public_html/wp-content/plugins/wp-user-frontend/includes/Frontend_Render_Form.php(260): WeDevs\Wpuf\Admin\Forms\Field_Manager->render_fields(Array, '780', Array, 'post', NULL)
#2 /home/myuser/public_html/wp-content/plugins/wp-user-frontend/includes/Frontend/Frontend_Form.php(309): WeDevs\Wpuf\Frontend_Render_Form->render_form('780', NULL, Array, Object(WeDevs\Wpuf\Admin\Forms\Form))
#3 /home/myuser/public_html/wp-includes/shortcodes.php(433): WeDevs\Wpuf\Frontend\Frontend_Form->add_post_shortcode(Array, '', 'wpuf_form')
#4 [internal function]: do_shortcode_tag(Array)
#5 /home/myuser/public_html/wp-includes/shortcodes.php(273): preg_replace_callback('/\\[(\\[?)(wpuf_f...', 'do_shortcode_ta...', '[wpuf_form id="...')
#6 /home/myuser/public_html/wp-includes/class-wp-hook.php(324): do_shortcode('[wpuf_form id="...')
#7 /home/myuser/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('[wpuf_form id="...', Array)
#8 /home/myuser/public_html/wp-includes/post-template.php(256): apply_filters('the_content', '[wpuf_form id="...')
#9 /home/myuser/public_html/wp-content/plugins/breakdance/subplugins/breakdance-elements/elements/Template_Content_Area/ssr.php(13): the_content()
#10 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/elements/Element.class.php(244): include('/home/myuser/...')
#11 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(442): Breakdance\Elements\Element::ssr(Array, Array, false, NULL)
#12 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(838): Breakdance\Render\getInnerHtml('EssentialElemen...', Array, '', Array, Array, NULL)
#13 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(1229): Breakdance\Render\getHtml(Array, 'EssentialElemen...', Array, '', Array, Array, Array, NULL)
#14 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(1185): Breakdance\Render\_render(Array, 10980, true, Array, NULL)
#15 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(1185): Breakdance\Render\_render(Array, 10980, true, Array, NULL)
#16 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(1185): Breakdance\Render\_render(Array, 10980, true, Array, NULL)
#17 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(237): Breakdance\Render\_rendermyuser(Array, 10980, true, Array, NULL)
#18 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(197): Breakdance\Render\getRenderedNodes(10980, true, NULL)
#19 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/renderer.php(46): Breakdance\Render\getRenderedPost(10980, NULL)
#20 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/themeless/theme-simulator/breakdance-template.php(16): Breakdance\Render\render(10980)
#21 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/capture-wordpress-output.php(96): include('/home/myuser/...')
#22 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/render/capture-wordpress-output.php(77): Breakdance\Render\getWordPressHtmlOutput('/home/myuser/...')
#23 /home/myuser/public_html/wp-content/plugins/breakdance/plugin/actions_filters/template_include.php(56): Breakdance\Render\getWordPressHtmlOutputWithHeaderAndFooterDependenciesAddedAndDisplayIt('/home/myuser/...')
#24 /home/myuser/public_html/wp-includes/class-wp-hook.php(324): Breakdance\ActionsFilters\template_include('/home/myuser/...')
#25 /home/myuser/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('/home/myuser/...', Array)
#26 /home/myuser/public_html/wp-includes/template-loader.php(104): apply_filters('template_includ...', '/home/myuser/...')
#27 /home/myuser/public_html/wp-blog-header.php(19): require_once('/home/myuser/...')
#28 /home/myuser/public_html/index.php(17): require('/home/myuser/...')
#29 {main}
  thrown in /home/myuser/public_html/wp-content/plugins/wp-user-frontend/includes/Admin/Forms/Field_Manager.php on line 271
////////////////////////////////////

Error Details (From WordPress email):
=============
An error of type E_ERROR was caused in line 271 of the file /home/myuser/public_html/wp-content/plugins/wp-user-frontend/includes/Admin/Forms/Field_Manager.php. Error message: Uncaught Error: Call to undefined method WeDevs\Wpuf\Admin\Subscription::init() in /home/myuser/public_html/wp-content/plugins/wp-user-frontend/includes/Admin/Forms/Field_Manager.php:271
Stack trace:
#0 /home/myuser/public_html/wp-content/plugins/wp-user-frontend/includes/Admin/Forms/Field_Manager.php(227): WeDevs\Wpuf\Admin\Forms\Field_Manager->check_field_visibility(Array)
#1 /home/myuser/public_html/wp-content/plugins/wp-user-frontend/includes/Admin/Posting.php(363): WeDevs\Wpuf\Admin\Forms\Field_Manager->render_fields(Array, '780', Array, 'post', 899)
#2 /home/myuser/public_html/wp-admin/includes/template.php(1456): WeDevs\Wpuf\Admin\Posting->render_form('780', Array)
#3 /home/myuser/public_html/wp-admin/edit-form-advanced.php(714): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post))
#4 /home/myuser/public_html/wp-admin/post.php(206): require('/home/myuser/...')
#5 {main}
  thrown

Any insight on how to fix this would be greatly appreciated.

Kind Regards,

**Comment by sapayth** [comment]
Hello @Anticosti,

Sorry to hear about your inconvenience. Please replace `wp-content/plugins/wp-user-frontend/includes/Admin/Forms/Field_Manager.php` line no `271` with below line:
`$user_pack = ( new Subscription() )->get_user_pack( get_current_user_id() );`

Feel free to notify us of any queries.

**Comment by Anticosti** [comment]
Huge thanks [sapayth](https://github.com/sapayth) for fixing this so quick. 
It works perfectly now.
Much appreciated.
