### ISSUE TITLE
errors with "allowDynamicProperties" after upgrade to 4.0.8

### ISSUE THREAD

**Issue by efCZa** [weDevsOfficial/wp-user-frontend#1465]
After updated to 4.0.8 I’m receiving thes errors, how to fix it?:

Warning: The use statement with non-compound name 'AllowDynamicProperties' has no effect in /home/html/citizenscience.cz/public_html/subdomains/db/wp-content/plugins/wp-user-frontend/wpuf.php on line 37

Warning: The use statement with non-compound name 'AllowDynamicProperties' has no effect in /home/html/citizenscience.cz/public_html/subdomains/db/wp-content/plugins/wp-user-frontend/Lib/invisible_recaptcha.php on line 20

**Comment by Rubaiyat-E-Mohammad** [comment]
Fixed in 4.0.9
