### ISSUE TITLE
[BUG] Selected category option is not visible on frontend post

### ISSUE THREAD

**Issue by Rubaiyat-E-Mohammad** [weDevsOfficial/wp-user-frontend#1492]
Description: Selecting a category option while filling up a form is working fine. But the selected option is not reflecting on the published post from frontend

Steps: 
1. Create a post from including category option selection field
2. Publish the form and create a post from frontend
3. Publish the post and observe that the selected category option is not reflecting on the post

More details and reference video in slack [Thread](https://wedevs.slack.com/archives/G17RY7NVB/p1729704847149539)

**Comment by sapayth** [comment]
[categories](https://wordpress.com/support/posts/categories/) and [meta fields](https://wordpress.org/documentation/article/assign-custom-fields/) are not the same. so we can’t treat them the same way. there should be some theme options to show the categories. if the user needs to show them in the content body, here is a basic way:

```
add_filter( 'the_content', 'astra_show_categories' );
function astra_show_categories( $content ) {
	if ( ! is_single() ) {
		return $content;
	}

	$categories_list = get_the_category_list( esc_html__( ', ', 'theme-text-domain' ) );

	if ( $categories_list ) {
		$content .= 'Categories: ' . $categories_list;
	}

	return $content;
}
```

**Comment by Rubaiyat-E-Mohammad** [comment]
Not an issue. Fixed in client site.
