### ISSUE TITLE
Improve Google Maps integration

### ISSUE THREAD

**Issue by rananrahim** [weDevsOfficial/WP-User-Frontend#156]
Currently the google maps in forms only show the predefined location set by the form creator. But there are more advanced usabilities available which can be at our disposal. It will make the google maps feature really comprehensive and powerful.

1. **Geolocate** : Form submitters location will be automatically detected using chrome or other browser's location information.
2. **Search**: Users will be able to search their location
3. **Get Direction**: If there is a predefined location, users will be able to get directions by one tap.

**Comment by Sk-Shaikat** [comment]
Google map is a pro version feature. Moving these issues to the pro-repository.
