### ISSUE TITLE
 Add checkbox inline option to taxonomy checkboxes.

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/wp-user-frontend#163]
When I create checkboxes I can show the inline. The CSS seems to be "**wpuf-checkbox-inline**".
Now, when I publish or create taxonomies in checkboxes, how do I use this CSS on the taxonomy checkboxes?
It would be great if you can add this option to taxonomy checkboxes, too.

**Comment by tareq1988** [comment]
Do you have any example on what you want to do?
