### ISSUE TITLE
Featured image not set

### ISSUE THREAD

**Issue by codearachnid** [weDevsOfficial/WP-User-Frontend#17]
I have the plugin (v 1.3.0) active and running on a production site. Just recently upgraded to the v1.3.0 version and now when users attempt to replace the featured image it doesn't not finish upload and setting. The progress bar will complete 100% and appears no error but no image will set and the option to save the featured image is not active. Looking at the filesystem and media library I do not see evidence of the image being uploaded there either. The user level managing the post is "subscriber" so not sure if it's a permissions issue or what has changed with the featured image functionality to break the upload.

**Comment by Sk-Shaikat** [comment]
This issue has been fixed. Recent version does not have this issue.

**Comment by rob1998** [comment]
Hi I think this issue has resurfaced, it uploads the image to 100%, but when I click save it doesn't set the image as the featured image.
I checked and it is uploaded, but just not set as featured.
Version 3.1.0
