### ISSUE TITLE
The user should redirect to a different page after updating their profile instead of the page that selected for redirecting after registration.

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/wp-user-frontend#172]
The user should redirect to a different page after updating their profile instead of the page that selected for redirecting after registration.

**Comment by damienoneill2001** [comment]
Can this please be logged as a bug and not a feature request.

When a user updates their profile, they should not be taken to the page that states "Thanks for registering, please check your email for an activation link".

That is behaviour that should not happen, is bad UX and should be treated as a bug.

Thanks

Damien

**Comment by damienoneill2001** [comment]
Hi Mahbubur,

Just wondering if there has been any update on this issue?

Damien

**Comment by tareq1988** [comment]
We are looking into it.

**Comment by tareq1988** [comment]
This feature has been introduced in the develop version.

**Comment by damienoneill2001** [comment]
Thanks Tareq

Do you have an ETA of when it may appear in the full release?

Damien

**Comment by damienoneill2001** [comment]
Hey  @mahbubme @tareq1988 ,

Was this fixed in the most recent release?

Damien

**Comment by damienoneill2001** [comment]
Hey @mahbubme @tareq1988 ,

I was just wondering what the plan was for this bug?  It was closed about a month ago but I did not see it in the most recent version of the free plugin.  Is it part of the next Pro version?

Thanks

Damien
