### ISSUE TITLE
Deleting a CPT Post deletes the post permanently

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/wp-user-frontend#191]
When I delete a post from the user's frontend Dashboard, the post moves into the Trash in the background as would be expected.

But, when I delete a Custom Post Type post, the post deletes permanently and does not go to the Trash. This is bad in case a user accidentally deletes a post and needs to be reinstated.

**Comment by damienoneill2001** [comment]
Hey Mahbubur,

Was this fixed in the most recent release?

Damien

**Comment by mahbubme** [comment]
Hello @damienoneill2001, 

Yes, you will find the fix in the latest version.

Thanks
