### ISSUE TITLE
recaptchalib.php conflict

### ISSUE THREAD

**Issue by munyagu** [weDevsOfficial/wp-user-frontend#197]
This library is very useful, but duplicates the function names with other plug-ins using the same library.

Fatal error: Cannot redeclare _recaptcha_qsencode() (previously declared in /hoge/wp-content/plugins/wp-user-frontend/lib/recaptchalib.php:47) in /hoge/wp-content/plugins/types/vendor/toolset/toolset-common/toolset-forms/js/recaptcha-php-1.11/recaptchalib.php on line 47

**Comment by tareq1988** [comment]
reCaptcha is a very common library that many plugins use. So we first check if the library is present, use the existing ones. If not, we include our library.

But when other plugins use the library, they have to do the same. If that would've been the case, the *Types* plugin would've just worked. Maybe they didn't check if the library is already present in any existing plugin.

So it's not a problem from our side, it's from their side.
