### ISSUE TITLE
Feature Image, Tags, and Header Image not working (WP 3.9)

### ISSUE THREAD

**Issue by JMCB1001** [weDevsOfficial/WP-User-Frontend#21]
After updating to wordpress 3.9, Feature Image, Tags, and Header Image won't load or save on either the front end or the admin side. I've found it to be related to this plugin as if I disable all of them but this one, I still get the error. Any ideas?

**Comment by Sk-Shaikat** [comment]
Maybe your WordPress didn't download correctly. Hope you have no issues with the latest versions. Thank you.
