### ISSUE TITLE
Articles publish even if set to "Pending"

### ISSUE THREAD

**Issue by matthew-dean** [weDevsOfficial/wp-user-frontend#210]
I've discovered that if I set-up the plugin to save submitted articles in a "Pending Review" state, I check the box to have people verify their email address, that:

a) The email that is sent to them indicates that the purpose of the email is to Publish immediately. (The link says "Publish" instead of a more accurate "Verify Email")

b) Clicking said link does indeed set the article into Published, bypassing review.

The only remedy seems to be un-checking verifying emails, which keeps the article in a Pending Review state.

**Comment by itowhid06** [comment]
Your issue is valid and we are working on it. Hopefully it will be resolved in next release.

**Comment by tareq1988** [comment]
Fixed.
