### ISSUE TITLE
Autocomplete Address Form/API Google with a custom field

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/wp-user-frontend#211]
Is that possible to integrate an API google in a field?
I would like that the address is checked before the post is created. (it will be nice that the address will be also Autocompleted)
Something like that: https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform?hl=de

**Comment by Sk-Shaikat** [comment]
We have the auto-complete option already. Do you mean auto-suggestions?

**Comment by mahbubme** [comment]
Please check the following example, we don't have this feature.
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform?hl=de

**Comment by Sk-Shaikat** [comment]
Issue updated: https://github.com/weDevsOfficial/wp-user-frontend/issues/295
