### ISSUE TITLE
Adding Custom Taxonomy as a hidden field

### ISSUE THREAD

**Issue by ArtScopeUK** [weDevsOfficial/WP-User-Frontend#24]
Hi, 

How do I add a custom taxonomy as a hidden field? I have managed to add WooCommerce fields (meta keys and meta values) but can't seem to add my own custom taxonomy fields. 

Any steer welcome... 

Mattias.

**Comment by Sk-Shaikat** [comment]
Hello,
You could try 'Action Hook' field for this. Please go through the following doc link for more details
https://docs.wedevs.com/docs/wp-user-frontend-pro/developer-docs/action-hook-field/

Thank you.

**Requesting author to close this issue.
