### ISSUE TITLE
WP Galleries cannot be edited

### ISSUE THREAD

**Issue by davidsdesk** [weDevsOfficial/WP-User-Frontend#25]
I noticed that, while images can be uploaded and edited, and galleries can be created through the front-end, galleries cannot be edited once created. Are there any plans to change this?

**Comment by gingebean** [comment]
+1

**Comment by Sk-Shaikat** [comment]
When you edit the post from front-end you could add multiple images in post content. If you need to change those image you can simply delete it and add new one from the editor.
