### ISSUE TITLE
Post form custom unauthorized message does not display

### ISSUE THREAD

**Issue by eldenmcd** [weDevsOfficial/wp-user-frontend#263]
I have an unauthorized message set for a post form which has stopped being displayed for users who are not logged in. Now only the default WPUF message is displayed: "Sorry. Guest Posting is not enabled for this form."

**Comment by eldenmcd** [comment]
Looks like this is a 'WPUF Pro' feature

**Comment by mahbubme** [comment]
@eldenmcd, Please make sure that you have set up unauthorized message from the form specific post settings. Navigate to **wp-admin -> User Frontend > Post Forms > Add new or Edit an existing form > Settings > Post Settings > Unauthorized message**. 
![1](https://user-images.githubusercontent.com/10685760/33802029-c372dab8-dd97-11e7-8aab-8cfe57ee54e6.png)
