### ISSUE TITLE
 Stuck to “saving form data”

### ISSUE THREAD

**Issue by GrosMatou** [weDevsOfficial/wp-user-frontend#271]
Hi,

First of all, thank you for your awesome plugin.
Since the last update, I have a problem,

After modifying my post form, when I click on “save Form”, the “saving form data” message is displayed, but continue loading and nothing happens… and my form isn’t saved 🙂

Do you have a hint to fix this problem?

Thank you in advance

Matthias

**Comment by mahbubme** [comment]
@GrosMatou, Thanks for reaching us. 

Please check the topic you created on WordPress.org. I have already replied there for this same issue.

**Comment by ShapesGraphicStudio** [comment]
Hello,
Has the been fixed ? I'm experiencing the same issue.
Best regards,
David
