### ISSUE TITLE
Updating to v2.7 broke the ability to register

### ISSUE THREAD

**Issue by damienoneill2001** [weDevsOfficial/wp-user-frontend#293]
After upgrading both the free and pro versions of WPUF to 2.7, the registration form stopped working.

When a user tries to register now, the URL changes from mysite.com/registration/ to mysite.com/registration/false and a 404 page is shown.

I have disabled all plugins except for WPUF and WPUF Pro and I have switched the theme to Twenty Fifteen but the issue still shows.  When I try to register with the default WordPress registration form, it works.  Only the WPUF form is broken.

I have downgraded the free version to v2.6.1 and the issue is still there.  I do not have access to a lower version of the Pro version.

**Comment by tareq1988** [comment]
One thing coming top of mind, try saving the plugin settings again, specifically the **Login/Register** tab and see what happens. Otherwise I can't think of a reason why it might be broken.

**Comment by damienoneill2001** [comment]
Thanks for the message @tareq1988.  I have tried that but it did not help.  Are you seeing the same behaviour on your installations?  

Is it possible to get one of the older versions of the Pro plugin sent out to me so I can test?

This was not an issue before upgrading to v2.7.0 and has only arisen since the upgrade.

**Comment by damienoneill2001** [comment]
Hi guys,

This has not yet been resolved.  I have got nowhere with support yet and am still concerned that it is an issue.  Is there any reason why this has been closed?

Damien

**Comment by shabnam611** [comment]
Hello Damien! 

Thanks for your query. I got your email yesterday and have replied you already. Can you please check your email? I have attached the previous versions of WPUF Pro with my last email. 

Please check and let me know if you need any more help. 

Mushrit

**Comment by damienoneill2001** [comment]
Thanks Mushrit,

I do not have that email.  Can you check your bouncebacks to see if it came back to you.  I do see your response in the tickets area of my account, but no corresponding email.

Can you add them to dropbox please?

Thanks

Damien

**Comment by shabnam611** [comment]
Hello Damien, 

Sorry about that. I sent you an email just now, can you please check again? I hope you will be able to download the previous versions. 

Mushrit

**Comment by damienoneill2001** [comment]
Yep, I have received that link now.  I will let you know how the testing goes.

Thanks again
