### ISSUE TITLE
Upgrade to 2.8.0 broke the ability to edit own posts

### ISSUE THREAD

**Issue by babid** [weDevsOfficial/wp-user-frontend#299]
After upgrading to 2.8.0 I can't update my own posts anymore. Clicking the [Edit] link in the screen listing my posts brings me to the post itself (not the edit form).

**Comment by mahbubme** [comment]
@babid Please navigate to **wp-admin > User Frontend > Settings > Frontend Posting**, now click on **Save Changes** button & check by editing post from the frontend. 

If the issue still exists on your site then please create a support ticket [here](https://wedevs.com/contact/). I will be happy to help you.

Thanks

**Comment by babid** [comment]
@mahbubme Many thanks. For some reason the Edit Page setting was lost (maybe during upgrade). Reset it and everything works fine now
