### ISSUE TITLE
%category% includes html garbage

### ISSUE THREAD

**Issue by patbell101** [weDevsOfficial/wp-user-frontend#316]
When I use%category% in my email form subject eg New CLE %category%:%post_title%

It is received as 
Subject: New CLE <a href="http://charente-limousine-exchange.com/category/announcements/" rel="tag">Announcements</a>:news test

**Comment by mahbubme** [comment]
@patbell101, 

Could you please create a support [here](https://wedevs.com/contact/)? We will be happy to help you. 

Thanks
