### ISSUE TITLE
Settings icons disappear after installing WP Project Manager 

### ISSUE THREAD

**Issue by thebengalboy** [weDevsOfficial/wp-user-frontend#317]
The settings icons disappear if you install the WP Project manager. Referred to the screenshot.
<img width="1258" alt="settings icons" src="https://user-images.githubusercontent.com/5962216/35264781-35442098-0048-11e8-9afb-b81b0929aac7.png">

**Comment by mahbubme** [comment]
@thebengalboy, Need to update WP Project Manager settings API to the latest version.
