### ISSUE TITLE
Multiple photo uploaders - Mobile iphone safari

### ISSUE THREAD

**Issue by SzutaBoj** [weDevsOfficial/wp-user-frontend#328]
Hi

I and my customers have bug with "send photo" module. I have multiple modules in one form. On mobile Safari this "blocking" sending photo (automaticly scroll to top of the site). 

(Sigle module per form works well).

**Comment by mahbubme** [comment]
Hello @SzutaBoj,

Please create a support ticket [here](https://wedevs.com/contact/). Our support team will help you to fix your issues. 

Thanks
