### ISSUE TITLE
[BUG][2.8.3] - Edit link broken

### ISSUE THREAD

**Issue by Deimz** [weDevsOfficial/wp-user-frontend#354]
All edit post links in the dashboard are broken since the last update. I'm using the PRO version. Links just bring the user to the single post page.

**Comment by Deimz** [comment]
The problem was that during update Wpuf edit page settings was lost

**Comment by rafsuntaskin** [comment]
So, after re-saving the settings the links are working fine now? 
Let us know if you are still facing issues.
