### ISSUE TITLE
Add Login Redirect Settings

### ISSUE THREAD

**Issue by rafsuntaskin** [weDevsOfficial/wp-user-frontend#355]
Allow admins to set a page to Redirect users after Login

**Comment by rafsuntaskin** [comment]
Also add Registration Redirect settings

**Comment by mahbubme** [comment]
These are the settings for this new feature.
![1](https://user-images.githubusercontent.com/10685760/36724023-170b1fbe-1bdc-11e8-850e-aad815349a10.png)
