### ISSUE TITLE
Small problem with 2.8.3

### ISSUE THREAD

**Issue by emmanuelrio** [weDevsOfficial/wp-user-frontend#357]
Hi :-)

When I install the last version 2.8.3 the <! - nextpage -> tag no longer appears in the form.

It works but the text: .... PAGE BREAK .... no longer appears. I tested, it's certain that it comes from the plugin.

Thank you in advance to make the correction so that I can switch to this version.

And congratulations for your work :-)

Emmanuel

**Comment by mahbubme** [comment]
Hello @emmanuelrio, How to reproduce the issue? Could you please describe in details? Also, send me the screenshot if possible.

Thanks

**Comment by emmanuelrio** [comment]
Hi :-)

Thank you for your answer. Here are 2 screenshots for you to see the problem.

Have a nice day

Emmanuel

![bug-page-break-1](https://user-images.githubusercontent.com/36857966/36747710-05795bde-1bf6-11e8-89f5-d86be0158433.png)
![bug-page-break-2](https://user-images.githubusercontent.com/36857966/36747711-05be1b48-1bf6-11e8-99cf-c984fa0b31de.png)

**Comment by rafsuntaskin** [comment]
@emmanuelrio

We are unable to reproduce the issue on our end. Seems like you are using some other plugins which inserts some extra buttons on your visual editor. But in our case its like this :

<img width="742" alt="screen shot 2018-02-28 at 12 10 01 pm" src="https://user-images.githubusercontent.com/7523321/36772698-787add4e-1c80-11e8-9b9d-5753137c73eb.png">

So, It might be an issue with that plugin as well we are not sure yet.

Let us know your findings.

Thanks

**Comment by emmanuelrio** [comment]
Hi :-)

Thank you for your answer. Here are 2 screenshots for you to see the problem.

Have a nice day

Emmanuel

![bug-page-break-1](https://user-images.githubusercontent.com/36857966/36747710-05795bde-1bf6-11e8-89f5-d86be0158433.png)
![bug-page-break-2](https://user-images.githubusercontent.com/36857966/36747711-05be1b48-1bf6-11e8-99cf-c984fa0b31de.png)

**Comment by emmanuelrio** [comment]
Hi :-)

Like many people I use the very popular plugin TinyMCE advanced. But the problem does not come from this plugin. Try with the <! - nextpage -> tag that is part of Wordpress. TinyMCE advanced just serves to paste this code.

Sorry for my not very good english :-)

Have a nice day

Emmanuel

**Comment by rafsuntaskin** [comment]
@emmanuelrio  we have found the issue and the fix will be available in next update.

Thanks for helping us.
