### ISSUE TITLE
CSS problem when creating multiple checkboxes

### ISSUE THREAD

**Issue by volveras** [weDevsOfficial/wp-user-frontend#388]
When you create multiple checkboxes on the post forms this happens: 
![css bug](https://user-images.githubusercontent.com/33986873/37725190-a5ccd7a0-2cef-11e8-86d5-56637f5a0a78.JPG)

**Comment by Anticosti** [comment]
**Wish** WPUF would include this "**U.S. States**" Custom Fields by default, like above.
Also the **Canadian Provinces** would be so great, along withe along with **Country List** (allready included)

**Comment by mahbubme** [comment]
Hello @volveras,

We have reproduced the CSS issue and trying to fix. We will inform you the updates.

@Anticosti, We don't have the plan to include **U.S States** with Address field or individual custom field for now. However, we may include it in future updates.

Thanks
