### ISSUE TITLE
Please add U.S. States / Canadian Provinces

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#389]
**Wish** WPUF would include this "**U.S. States**" Custom Fields by default.
Also the **Canadian Provinces** would be so great, along with **Country List** (already included)

**Comment by rafsuntaskin** [comment]
Hi @Anticosti,

As we are now focusing on improving the UI. Therefore, there is no possibility of this kind of implementation for now but I have kept this in the backlog.

Thanks for your suggestion.
