### ISSUE TITLE
WP-user-fronted blocking site from coming up...

### ISSUE THREAD

**Issue by jmarshane116** [weDevsOfficial/wp-user-frontend#392]
Hello, 

I have the latest version of user-frontend installed, and have not installed any plugins since I installed it.  But for some reason, when user-frontend is activated, I cannot get to my site.  When I deactivate it, I can get to my site with no problems.

To be certain this plugin is the cause, I deactivated every plugin on my site (which aren't many) and found it is definitely the cause, because when I activate it, I am getting **HTTP 500 error**.

Can you please assist?

Much thanks in advance ...

jmr ...

**Comment by itowhid06** [comment]
Hello @jmarshane116,

Can you please create a support ticket [here ](https://wedevs.com/contact/)with your site details? We will be happy to help you.

Thanks
