### ISSUE TITLE
Can’t disable new post notifications

### ISSUE THREAD

**Issue by arekkko** [weDevsOfficial/wp-user-frontend#395]
Hello,
I using WP User Frontend and I can’t disable New Post Notifications for custom form. I un-check the Enable post notification field and click Save Form button. After that I refresh page and see that Enable post notification field is still checked.

How I can permanently disable notification for new created post sending by WP User Frontend?

**Comment by mahbubme** [comment]
Hello @arekkko,

Please follow the ticket you created on WordPress.org for this same issue. We already replied there.

https://wordpress.org/support/topic/cant-disable-notifiactions/

Thanks
