### ISSUE TITLE
Custom Post Type - Post Expiration (Not working)

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#409]
I have a CPT where the submitted content should ideally be online just for a couple hours (1 to 5 hours)

This setting is not working for the "1 Day"
The content stays live
Settings / Post Expiration / Post Expiration Time: 1 Day
Settings / Post Expiration / Post Status : Draft

**Comment by Anticosti** [comment]
Just as a side note:
There is no fee to post.
No payment required.
No pack associated.
Completely free.

Thanks.

**Comment by itowhid06** [comment]
Hello @Anticosti ,
We found this issue only when a user has bought a subscription pack and then cancelled it whether payment is enabled or not in the form. Could you please confirm us the subscription status of the user you faced the issue with?

**Comment by Anticosti** [comment]
Hello @itowhid06
Thank you for your reply.
The Subscription status of the user is: "Subscriber"
I am looking into this right now. Will let you know.

Thanks

**Comment by Anticosti** [comment]
Conclusion: 
One day passed, and the post is still online while it should had been triggred to OFFLINE

**Comment by Anticosti** [comment]
Now when the user (subscription pack with Editor role) post a new submission, it then shows in his Dashboard as a Status "Awaiting Approval"

I am really puzzled

**Comment by itowhid06** [comment]
Hello @Anticosti ,

Can you please create a support ticket [here ](https://wedevs.com/contact/) with your temporary site details? We will be happy to help you.

Thanks

**Comment by Anticosti** [comment]
Thank you @itowhid06
Opening a ticket... wiil be available in about 15 minutes -;)
Kind Regards

**Comment by Anticosti** [comment]
@itowhid06 
Ticket created.
You may check Ticket #96806

Kind Regards

**Comment by Anticosti** [comment]
Any update?

**Comment by itowhid06** [comment]
Hello @Anticosti ,
I've forwarded this to our support team. Please follow the ticket for faster response. Also please allow us some time as friday and saturday is our weekend and the nature of problem requires some time to investigate. We'll try to solve your problem as soon as possible. Thank you for your kind cooperation.

Best Regards

**Comment by Anticosti** [comment]
@itowhid06
Thank you for the follow up.
Will check back on Monday with my ticket.
Have a great Weekend!

**Comment by itowhid06** [comment]
fixed https://github.com/weDevsOfficial/wp-user-frontend/pull/424/commits/b019ca9c4fad6479ae90a2bf305d5909dac2318f
