### ISSUE TITLE
Feature Request:  Post Expiration (extra options)

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#411]
Post Expiration Options: 

Right now we have these options: 
- Day
- Month
- Year

Wish I could have these:
- Hour
- Day
- Week
- Month
- Year

Kind Regards,

**Comment by rafsuntaskin** [comment]
As we already have **Days** therefore **Week** is not suitable for all users as you can always count **weeks** using days.

As for Hour it's not in plan for now as we use WP Cron which is not precise for websites with low visitors.

Thanks
