### ISSUE TITLE
2.8.7 :  Billing Address - Needs little tweaks

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#414]
Little Tweaks needed:
https://www.dropbox.com/s/8dqxdrfcbjyschg/S%C3%A9lection_049.bmp?dl=0

Kind Regards,

**Comment by itowhid06** [comment]
Hello @Anticosti,

You can set state and country field as required editing the billing address template as per your need and overriding the billing address template by following this guide [How to override templates](https://wedevs.com/docs/wp-user-frontend-pro/tutorials/how-to-override-dashboard-templates/).
As for the missing strings issue, we'll have a look into it.  
And for displaying only selected countries, it's not in our task-lists yet, but in future we might consider it.

Best Regards

**Comment by Anticosti** [comment]
@ itowhid06
Thank you for your reply.
Appreciated.
