### ISSUE TITLE
Changing the subscription button label 'Buy Now'

### ISSUE THREAD

**Issue by thebengalboy** [weDevsOfficial/wp-user-frontend#425]
Please consider adding an option to change the subscription button label 'Buy Now' to anything that user wants. It would be very good if you can provide a flexible option to the user that they can choose it themselves.

Thanks

**Comment by rafsuntaskin** [comment]
**This is available from v2.8.8**

Free users can now override Subscription templates from their theme therefore they can simply change the button text by editing
`wp-user-fronted/templates/subscriptions->pack-details.php` and saving it within  `WPUF/templates/subscriptions` folder.



But our PRO users have a settings to customize all the colors and texts from Settings : 

<img width="1265" alt="screen shot 2018-04-26 at 11 05 50 am" src="https://user-images.githubusercontent.com/7523321/39286857-0ff24de0-4942-11e8-9c40-530ec28eb33c.png">

**This is available from PRO v2.8.2**
