### ISSUE TITLE
Edit Subscription -> Expiration Message

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#427]
01. I edited the **Expiration Message** for testing and typed in the text box: **Expiration Message**
02. I modified the message for something more detailed, cleared cache and all, and still "**Expiration Message**" is showing.
Would be nice if we could customize the Expiration Message at:
Edit Subscription
-- Subscription Options
-- -- Posting Restriction (tab)
-- -- -- Expiration Message

If we could use replacement tags, like the ones for email templates

**Comment by Anticosti** [comment]
I had to go directly in the database: Find and Edit:
SELECT * FROM `user_databasename`.`wp_postmeta` WHERE (CONVERT(`meta_id` USING utf8) LIKE 'Expiration Message' OR CONVERT(`post_id` USING utf8) LIKE 'Expiration Message' OR CONVERT(`meta_key` USING utf8) LIKE 'Expiration Message' OR CONVERT(`meta_value` USING utf8) LIKE 'Expiration Message')

**Comment by Anticosti** [comment]
Wish we could present in this email, the Title and URL of the post that just expired.

**Comment by itowhid06** [comment]
Hello @Anticosti ,

We were unable to reproduce the issue at our end. The expiration message is being updated without any problem. Can you please deactivate your caching plugins and try it again? Let us know the update.

Also, at the moment including Title and URL of expired posts in the mail is not in our task list, but we will analyze it and might add this feature in future.

Best Regards
