### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#428]
Just noticed: There is a missing string(s) in the language file:
page:
account/?section=subscription

You have in English:
Package & billing details: Free **For each** 1 **year** 

In French I have:
Forfait et détails de facturation: Gratuit **For each** 1 **year**

Regards,

**Comment by itowhid06** [comment]
completed https://github.com/weDevsOfficial/wp-user-frontend/pull/429/commits/068b4e8817405f32e84a65ce86fb2060339f7aaf
