### ISSUE TITLE
Subscription time redirection to the login page for existing user

### ISSUE THREAD

**Issue by thebengalboy** [weDevsOfficial/wp-user-frontend#433]
Hello, I have created a subscription page with the short-code [wpuf_sub_pack]. Now, when a non-logged in user wanting to get a subscription pack, it's redirecting to the registration page. Well, this user has an account on my site already, but there is no sign in option. Please consider adding the login option too.

Thanks

**Comment by tareq1988** [comment]
Add Login and forgot password link instead on the registration page.
