### ISSUE TITLE
Warning: Use of deprecated PHP4 style class constructor is not supported since PHP 7

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#437]
Greetings,

Just to let you know I got this report from my Siteground hosted website.
Hope this may be helpfull?

`----------------------------------------------------------------------------------------------------------------
FILE: /home/user/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/req/fpdf/fpdf.php
----------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------
 1055 | ERROR | Function set_magic_quotes_runtime() is deprecated since PHP 5.3 and removed since PHP 7.0
----------------------------------------------------------------------------------------------------------------
FILE: /home/user/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/req/fpdf/font/unifont/ttfonts.php
--------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------
 72 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
--------------------------------------------------------------------------------------------------------------------------------
FILE: /home/user/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/req/fpdf/tfpdf.php
-----------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------------------------
   79 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
 1261 | ERROR   | Function set_magic_quotes_runtime() is deprecated since PHP 5.3 and removed since PHP 7.0
-----------------------------------------------------------------------------------------------------------------
`

Regards,

**Comment by mahbubme** [comment]
Fixed in the pro version.
