### ISSUE TITLE
What could prevent "Subscriptions" to not show in the "User Frontend" admin menu?

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#438]
Greetings,

I have a multisite setup.
On one subsite Subcriptions appears in the submenu;
On the othe subsite it does not...?

<ul class="wp-submenu wp-submenu-wrap"><li class="wp-submenu-head" aria-hidden="true">User Frontend</li><li class="wp-first-item"><a href="admin.php?page=wpuf-post-forms" class="wp-first-item">Post Forms</a></li><li><a href="admin.php?page=wpuf-profile-forms">Registration Forms</a></li><li><a href="admin.php?page=wpuf_weforms">Contact Form</a></li><li class="current"><a href="edit.php?post_type=wpuf_subscription" class="current" aria-current="page">Subscriptions</a></li><li><a href="edit.php?post_type=wpuf_coupon">Coupons</a></li><li><a href="admin.php?page=wpuf_updates">Updates</a></li><li><a href="admin.php?page=wpuf_transaction">Transactions</a></li><li><a href="admin.php?page=wpuf_tools">Tools</a></li><li><a href="admin.php?page=wpuf-modules">Modules</a></li><li><a href="admin.php?page=wpuf-support"><span style="color:#f18500">Help</span></a></li><li><a href="admin.php?page=wpuf-settings">Settings</a></li></ul> 

What could be the cause?

Thanks

**Comment by itowhid06** [comment]
Hello @Anticosti ,

Please make sure that you have checked 'Enable Payments' option from wp-admin > User Frontend > Payments tab. Subscriptions, Coupons and Transactions won't appear in User Frontend menu until you have enabled payments.

Best Regards

**Comment by Anticosti** [comment]
You were right. Thank you so much.
My bad.
