### ISSUE TITLE
I don't see any subcribed user being listed below "Subscribers" column

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#439]
Greetings,
On a test subsite:
I have a Pack and two users subsribed to this pack
at:
wp-admin/edit.php?post_type=wpuf_subscription
I don't see any user being listed below "Subscribers" column

Thanks again

**Comment by itowhid06** [comment]
Hello @Anticosti ,

If you are still facing the issue, then please open a ticket [Here](https://wedevs.com/contact).

Best Regards

**Comment by Anticosti** [comment]
Thank you for your reply.
Ticket created.
#97979

Kind Regards,
