### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by fanwarde** [weDevsOfficial/wp-user-frontend#454]
When I click on the indentation button(Left, Center, Right Indent) on the WP-UserFrontend editor. A jquery error is thrown "Uncaught TypeError: Cannot read property 'toLowerCase' of undefined". From debugging i noticed that this function is throwing an error **if (tagName.toLowerCase() == 'a') {** . Also the indentation doesn't work.

**Comment by rafsuntaskin** [comment]
Hello @fanwarde ,

I was not able to reproduce the issue on my end as indenting produces no such error.

It might be an issue on theme or plugin conflict on your site. Try changing the theme or deactivating other plugins to be confirmed. If that doesn't resolve the problem then please provide more details about the form settings.

Thanks

<img width="1280" alt="screen shot 2018-05-14 at 8 14 43 am" src="https://user-images.githubusercontent.com/7523321/39975177-e2827ce8-574e-11e8-91fd-72be897853c7.png">

**Comment by fanwarde** [comment]
Hello,
Sorry for reopening this post. This issue only occurs in chrome on windows. Every time I click the Left indent button it throws and error. It works properly on firefox and edge. 
![error](https://user-images.githubusercontent.com/20441188/45790797-889c0080-bc54-11e8-807b-1076f0dc6f73.PNG)
