### ISSUE TITLE
Please make the alert `Please Cancel Your Currently Active Pack first ! ` translatable.

### ISSUE THREAD

**Issue by harlet** [weDevsOfficial/wp-user-frontend#459]
Hi guys!
Can you please make the js alerts and text translatable?
The needed text is in: /wp-user-frontend/assets/js/subscriptions.js:34

Thank you!

**Comment by rafsuntaskin** [comment]
Hi @harlet ,

Thanks for your report. We are working on these texts to make them translatable by next update.

Thanks
