### ISSUE TITLE
Please make the expiration period values internationalized in the front end.

### ISSUE THREAD

**Issue by harlet** [weDevsOfficial/wp-user-frontend#462]
On the pack admin add/edit page I see the values in en and I think the logic needs this.
![backend](https://user-images.githubusercontent.com/5509330/40231093-6f5d650a-5aa2-11e8-90c1-21471c3f8136.png)

But I need a way to translate the front end `cycle_period`.
/wp-user-frontend/class/subscription.php:828

Thank you! 🍻

**Comment by mahbubme** [comment]
Hello @harlet,

We just fixed this issue, from the next version(2.8.10) you can translate the cycle period labels.

Thanks
