### ISSUE TITLE
Drag and Drop images ordering on uploading

### ISSUE THREAD

**Issue by thebengalboy** [weDevsOfficial/wp-user-frontend#471]
Hello,

Post form or Product form, if I use the multiple image upload field, it allows to select and upload multiple images at a time(while posting). But, those images get the order in sorting on their own way. It would be great if you can consider adding the drag & drop feature on image uploading. Like, I would like to take the 4th image to position 1.

Thanks

**Comment by mahbubme** [comment]
Hello @wmalexander, 

This feature has been added in the development version, please wait for the next release (2.9.0). 

Thanks

**Comment by wmalexander** [comment]
Thanks!
