### ISSUE TITLE
Missing space before the Pipe character

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#481]
Greetings,

For example, I have a checkbox field, where I have four options:
- Apple
- Banana
- Lemon
- Orange

Suppose the four options are selected on the Post creation, 
they will output like this (_see the **missing space** before the **Pipe character**_):
**Apple| Banana| Lemon| Orange**
Wish they could output like this:
**Apple | Banana | Lemon | Orange**

An idea, for the future: Would be nice if we could have an option to choose a custom seperator and format it as wished. One could choose any character combination of his choice: 
`(;)  (/)  ( ; )  ( / )  (&nbsp;/ ) etc. `
Even the possibility to insert a non-breaking space (`&nbsp;`) would be a big plus.
Example:
**Apple / Banana / Lemon / Orange**

Keep up with this great work ;-)

Kind Regards,

**Comment by Anticosti** [comment]
Checking back...

**Comment by Anticosti** [comment]
Greetings,
Any chance this could be solved, soon?
Taking a chance ;)

Best Regards

**Comment by rafsuntaskin** [comment]
Hi,

I will check on these before releasing next update to add the space. 

And we also have it in plan so that users can use anything other than just `|` as separator.

Thanks

**Comment by Anticosti** [comment]
Tanks for the update. 
Love you guys. Thumbs Up.
Much appreciated (again)
Keep up this great work you guys doing.
