### ISSUE TITLE
WPUF update : rename translation .po .mo files

### ISSUE THREAD

**Issue by acbardou** [weDevsOfficial/wp-user-frontend#483]
Hi,

you informed us (non-english users) that we needed to change the name of the .po and .mo files.
Could you please describe precisely here the whole process ?

Thank you !

Anne-Constance

**Comment by rafsuntaskin** [comment]
You need to change it if you face any issues after updating the plugin.

But to assist you I need these answers 
Which language are you using? 
Is it located within the plugin folder or wp-content/languages folder?

**Comment by acbardou** [comment]
Hi ! Thank's. Here's my answer from wordpress.org : Hi ! Thank's for your answer ! 

I'm using loco translate and my website is in French. So the translation folder is in /www/wp-content/languages/loco/plugins . 
Do I have to rename it from wpuf-fr_FR.po to wp-user-frontend-fr_FR ?

**Comment by rafsuntaskin** [comment]
Please follow the ticket on [https://wordpress.org/support/topic/wpuf-update-rename-translation-po-mo-files/#post-10376315](wordpress.org) as one of our clients has already provided a solution for you to follow.

Let us know if that helped.

Thanks

**Comment by acbardou** [comment]
Thank's for you answer. Yes, his answer was really great and detailed.
Problem is solved now.

Regards,

Anne-Constance
ᐧ




[image: Logo]
<http://res.cloudinary.com/hrscywv4p/image/upload/c_limit,fl_lossy,h_1440,w_720,f_auto,q_auto/v1/1081088/fullBluePlan_de_travail_21024_irvjys.png>
[image: Logo] <http://www.instagram.com/avanamahe_officiel> [image: Logo]
<http://www.twitter.com/avanamahe> [image: Logo]
<http://www.facebook.com/avanamahe> [image: Logo]
<http://www.linkedin.com/avanamahe>

Anne-Constance Bardou
Fondatrice
Coucou, on cherche un dev !
06 33 67 98 78
acb@avanamahe.com
Fondatrice
http://www.avanamahe.com
[image: Logo] <http://www.instagram.com/ava_nam_ahe> [image: Logo]
<http://www.instagram.com/ava_nam_ahe> [image: Logo]
<http://www.instagram.com/ava_nam_ahe> [image: Logo]
<http://www.instagram.com/ava_nam_ahe> [image: Logo]
<http://www.instagram.com/ava_nam_ahe> [image: Logo]
<http://www.instagram.com/ava_nam_ahe>

2018-06-08 6:28 GMT+02:00 Rafsun Chowdhury <notifications@github.com>:
