### ISSUE TITLE
Form Builder not showing post field when modify

### ISSUE THREAD

**Issue by erapisardi** [weDevsOfficial/WP-User-Frontend#49]
When I try to change the form already created the field are not showing, neither the other options like "post settings" "edit settings".
Tried to deactivate all the other plugins but the issue is still there.
The console errors and warnings
Uncaught TypeError: $(...).wpColorPicker is not a function
util.js:22 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
![schermata 2016-02-16 alle 11 50 15](https://cloud.githubusercontent.com/assets/1405317/13074208/7c8e2bb0-d4a3-11e5-81f5-badc0321a69d.png)

**Comment by erapisardi** [comment]
I tried with a brand new wp deployment, no plugins, default theme. but the issue is still there.

**Comment by mahbubme** [comment]
Hi,

I have tried to reproduce the issues you have mentioned. I have only found the warning about google maps and informed the developer team. A javascript warning will never cause a plugin to malfunction.
I have no idea about the wpColorPicker error. 

It would be better for me to diagnose the issue if you can provide me the login details to support[at]wedevs.com

Else, please make sure that the PHP version of your server is 5.4+ and MySQL version 5.6+ and you are using the latest version of WordPress.
