### ISSUE TITLE
Impossible to save post form

### ISSUE THREAD

**Issue by alvinje** [weDevsOfficial/wp-user-frontend#491]
It seems to be imposible to save a post form on my website.
I've had some custom field to a post form and when I want to save it, no change is saved and I've no error message

**Comment by rafsuntaskin** [comment]
Please enable WP_DEBUG in your WordPress config file and check if you have any errors logged on debug.log generated within the wp-content folder.

Does it work with default posts?

**Comment by rafsuntaskin** [comment]
Hi, Hope you got this resolved let us know if you still need help. I will close this for now.

**Comment by Kdoni** [comment]
I have thesame issue, problem still persist even after your recommendation

**Comment by Kdoni** [comment]
> Hi, Hope you got this resolved let us know if you still need help. I will close this for now.

I have thesame issue, problem still persist even after your recommendation
