### ISSUE TITLE
WPUF Login showing the username even if you insert the email and a wrong password

### ISSUE THREAD

**Issue by thebengalboy** [weDevsOfficial/wp-user-frontend#494]
It's showing the username even if you insert the user email and a wrong password. If anyone who knows your email address can ascertain whether you have an account with a certain website or not by typing in your email at login and then seeing a username is associated with that email address. It's security/privacy issue actually.

How to reproduce the issue;

- Try login with WPUF Login page
- Use the email and a wrong password
- See the error, it's showing the username

**Comment by rafsuntaskin** [comment]
`add_filter( 'wpuf_get_username_from_email', 'rt_show_username_only_988' );

function rt_show_username_only_988( $bool ){
    return false;
}`

This should revert the behavior. We can't replace it in the core now as many have wanted this the other way around.
