### ISSUE TITLE
Need to change the cursor from the bottom to top of the next page

### ISSUE THREAD

**Issue by projna** [weDevsOfficial/wp-user-frontend#515]
In a multi-step form, when the first page is being filled up and clicked on the button "next", it changes the cursor at the bottom of the form.
Now it is needed to scroll up to go to the top of the form page. It is suggested from the user that after clicking on the "next" button the cursor will be on the top of the form.

**Comment by thebengalboy** [comment]
Also, the steps are not showing properly on the mobile devices. Example-> https://prnt.sc/k6d7n6
