### ISSUE TITLE
Store the Address from the google maps Field

### ISSUE THREAD

**Issue by projna** [weDevsOfficial/wp-user-frontend#522]
Is it possible to store the Address from the google maps Field? When an address is entered it will be sent to Google and return in some java stuff. Now it may be added a checkbox store address in a custom field or something. So it does not need to ask the user for the address again.

**Comment by DenisCGN** [comment]
Yes and please Store the PLACE ID :-)

**Comment by thebengalboy** [comment]
Hello @projna and @DenisCGN 

I'm extremely sorry to inform you that, we are not going to consider this feature soon as per the management decision. We may consider adding this in the future if we get the similar request few more.

Thanks
