### ISSUE TITLE
every form includes 2 fields that have not been chosen

### ISSUE THREAD

**Issue by custardxx** [weDevsOfficial/wp-user-frontend#536]
Every form is burdened with 2 fields that have not actually been chosen, namely email and name at the top.
Any ideas?

**Comment by mahbubme** [comment]
Hello @custardxx,

It seems you have guest post enabled and required name and email address option in your form. You can disable it from the form's **Settings > Submission Restriction**. Please check the following screenshot: 

[https://prnt.sc/kd2kfk](https://prnt.sc/kd2kfk)

Thanks
