### ISSUE TITLE
Remove :not selector usage for multi level elements

### ISSUE THREAD

**Issue by mrmadhat** [weDevsOfficial/wp-user-frontend#538]
The :not selector doesn't seem to behave the same across browsers. Chrome will accept nested elements e.g `:not(.parent .child)` whereas Safari will not.

In wp-user-frontend/assets/css/frontend-forms.css there's the following css:

```
.wpuf-image-wrap :not(.attachment-name img) {
    position: absolute;
    width: 100%;
    transition: .3s;
}
```

and the following html:

```
<li class="ui-state-default wpuf-image-wrap thumbnail">
    <div class="attachment-name">
        <img src="some-image-150x150.jpg" alt="about-header">
    </div>
    <!-- removed unnecessary html -->
</li>
```
The css above will not be applied to `.wpuf-image-wrap .attachment-name img` in Chrome (correct) but will be applied in Safari.

## How to replicate

1- Add a frontend form that accepts an image e.g featured image
2- Use the form in Safari

Tested in Safari 11.1.2

**Comment by hasinur1997** [comment]
I tested using Safari, it shows like as chrome.
