### ISSUE TITLE
Direct Link To Post Edit

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#542]
Hello,
because I use a Custom Post Type for the user profile I like to have a link that directly moves to the edit page and open the CPT without going via the dashboard...(cause there is only one post).
A direct link to edit a post with ID XXX.
Thanks,
Denis

**Comment by DenisCGN** [comment]
Please 🙏🏻

**Comment by mahbubme** [comment]
Hello @DenisCGN,

I am really sorry for the delay in response. 

You can generate edit link by creating a function that will return the post edit URL. You need to call that function where you want to link the edit page directly. Here is the code example:

`function wpuf_post_edit_link() {
	global $post;

	$edit_page  = (int) wpuf_get_option( 'edit_page_id', 'wpuf_frontend_posting' );
	$post_id    = $post->ID;
	$url        = add_query_arg( array('pid' => $post->ID), get_permalink( $edit_page ) );

	return wp_nonce_url( $url, 'wpuf_edit' );
}`

Thanks

**Comment by DenisCGN** [comment]
I forgot to say thank you!
Cheers,
Denis
