### ISSUE TITLE
AVATAR Upload Button Text

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#543]
Hello,

can you please add the possibilitiy to change the button text for the avatar upload like in the other upload fields?
https://festivaldate.de/wp-content/uploads/2018/07/wedev_image_upload_button____.jpg

thanks,
Denis

**Comment by mahbubme** [comment]
Hello @DenisCGN,

The option to change the button text has been added to the WPUF Pro plugin, you will get it from the version 2.9.1

![download](https://user-images.githubusercontent.com/10685760/47774401-233d3400-dd17-11e8-817e-f464578fda84.png)


Thanks

**Comment by DenisCGN** [comment]
Hello When will The New pro Version be released?
My pro is still at 2.8.2
And normal is at 2.9.2
And The Avatar thing does Not Change.
Cheers,
Denis

Von meinem iPhone gesendet

**Comment by mahbubme** [comment]
Currently, the pro version is 2.9.0, so please wait for 2.9.1

Thanks
