### ISSUE TITLE
Count Charachters insted of words

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#544]
Hello,
can you please add the count of charachters in fields and textareas. This is, for me, nicer than counting words.
thanks,
Denis

**Comment by thebengalboy** [comment]
Hello @DenisCGN 

I have added your request on our feature request log. We may consider adding this in the future if we get the similar request few more.

Thanks for your understanding :)

**Comment by DenisCGN** [comment]
Any News Herr?

**Comment by DenisCGN** [comment]
Something new here???

**Comment by hasinur1997** [comment]
This feature is implemented.
