### ISSUE TITLE
Subscription is not completely hidden even when the settings is so

### ISSUE THREAD

**Issue by mayeenulislam** [weDevsOfficial/wp-user-frontend#548]
In our case there should be no subscription. So we deactivated the Subscription feature from WPUF Settings.

![wpuf-no-subscription](https://user-images.githubusercontent.com/4551598/43880065-aed09b14-9bc8-11e8-979e-c089341458e6.png)

The Setting is doing what it says, the Subscription menu button from the My Account is vanished.

But the translation strings, and TinyMCE toolbar shortcode option is not obeying the setup.<br>
![tinymce-subscription-shortcode](https://user-images.githubusercontent.com/4551598/43880147-010e0f1a-9bc9-11e8-9c40-c745ebb28817.png)

You can see the translation string is not compliant to the setting:<br>
https://github.com/weDevsOfficial/wp-user-frontend/blob/v2.8.10/templates/dashboard/dashboard.php#L13

So in Bengali, we simply stripped out the string with the anchor tag in Translation, but what about the default language?

You can simply make the Settings' checkbox label to: **":ballot_box_with_check:  Enable Subscription"**, and change the other things accordingly.

**Comment by mahbubme** [comment]
Hello @mayeenulislam,

Thanks for mentioning the issues. We will fix them in the next release.
