### ISSUE TITLE
Cannot edit fields when creating forms

### ISSUE THREAD

**Issue by ThisIsSavo** [weDevsOfficial/wp-user-frontend#550]
Hi. I installed WP user frontend, and when trying to create a form I cannot select a certain field to change it's name etc. I suppose when I hover over a field that mini-menu should pop-up and allow me to select a field. Instead, weird question marks and exclamation marks are appearing. 
![wp-user-frontend-issue](https://user-images.githubusercontent.com/4977043/43955389-38bfb92c-9ca0-11e8-8a05-eb8659f7b72a.png)

**Comment by thebengalboy** [comment]
Hello @ThisIsSavo 

There might have a conflict with any other plugin or theme. Please [check the conflict](http://www.thebengalboy.com/best-practice-find-wordpress-theme-plugin-conflicts/) on your site and let me know the result.

Thanks

**Comment by ThisIsSavo** [comment]
Thank you. It has been resolved.
It wasn't the plugins, it was the theme I'm using. Reverted back to the default theme and was able to edit forms. Guess it's a 'hack' but I managed to create & edit my forms successfully.
