### ISSUE TITLE
Custom Metaboxes missing after upgrading from 2.8.10 to 2.9.0

### ISSUE THREAD

**Issue by depiction** [weDevsOfficial/wp-user-frontend#554]
I noticed recently that a few custom metaboxes added by my website’s theme on post edit pages were missing. After nearly two hours of debugging, I discovered that they disappeared after upgrading this plugin from 2.8.10 to 2.9.0.

I’ve been able to reproduce the issue multiple times. If I upgrade to 2.9.0 or the latest version (currently 2.9.1), the metaboxes disappear. When I revert back to 2.8.10 or any version before that, they re-appear.

What changed in 2.9.0 that could be causing this? I don’t see any console errors.

I added the following lines to wp-config.php to enable debugging and log errors to wp-content/debug.log, but the only thing outputted to that file is a warning that “wp_enqueue_style was called incorrectly”.

define(‘WP_DEBUG’, true);
define(‘WP_DEBUG_DISPLAY’, false);
define(‘WP_DEBUG_LOG’, true);

**Comment by mrmadhat** [comment]
I had a similar issue with upgrading, the problem turned out that it was because ACF was installed. #521 fixed the issue for me. It allows you to add a filter that will show WPUF metaboxes even with ACF active.

`add_filter( 'wpuf_hide_meta_when_acf_active', __return_false );`

**Comment by depiction** [comment]
I have ACF, but the metaboxes that disappear are added by my theme, not ACF. The above fix didn't work.

**Comment by thebengalboy** [comment]
Add these two lines of code on your theme function.php file. It should resolve the issue.

`remove_action( 'admin_init', array( wpuf()->settings, 'admin_init') );`
`add_action( 'admin_init', array( wpuf()->settings, 'admin_init'), 100 );`

**Comment by depiction** [comment]
@thebengalboy That worked. Thanks!

**Comment by Grauen** [comment]
Hi @thebengalboy ,

I just created a new issue on this before reading this one (surprise ;) ).
https://github.com/weDevsOfficial/wp-user-frontend/issues/574

` add_filter( 'wpuf_hide_meta_when_acf_active', __return_false );`

This helped but there must be a way to fix this in the plugin itself. Why is wpuf hiding the meta box when acf is active? Can't we have an option to turn this feature off?
