### ISSUE TITLE
Blocker! NoCaptcha reCaptcha compatibility problem. Cant log in.

### ISSUE THREAD

**Issue by d-v-s** [weDevsOfficial/wp-user-frontend#561]
After some of updates it is unable to login using No CAPTCHA reCAPTCHA plugin. WPUF Login/Register settings are all disabled (turned off).
There are two error messages with different settings.
1. reCaptcha keys are not saved in WPUF General settings. Then error message is “To use reCAPTCHA you must get an API key from https://www.google.com/recaptcha/admin”
2. reCaptcha keys are saved in WPUF General settings. Then error message is “{“success”:false,”error”:”noCaptcha reCAPTCHA validation failed”}”
There are no errors in log file except some warnings (dont know if it helps):

`[21-Sep-2018 11:48:50 UTC] PHP Warning:  Use of undefined constant error - assumed 'error' (this will throw an Error in a future version of PHP) in /wp-content/plugins/wp-user-frontend/lib/recaptchalib_noCaptcha.php on line 163`
`[21-Sep-2018 11:48:50 UTC] PHP Warning:  Use of undefined constant codes - assumed 'codes' (this will throw an Error in a future version of PHP) in /wp-content/plugins/wp-user-frontend/lib/recaptchalib_noCaptcha.php on line 163`
`[21-Sep-2018 11:48:50 UTC] PHP Warning:  A non-numeric value encountered in /wp-content/plugins/wp-user-frontend/lib/recaptchalib_noCaptcha.php on line 163`
`[21-Sep-2018 11:48:50 UTC] PHP Warning:  A non-numeric value encountered in /wp-content/plugins/wp-user-frontend/lib/recaptchalib_noCaptcha.php on line 163`
`[21-Sep-2018 11:48:50 UTC] PHP Notice:  Undefined offset: 0 in /wp-content/plugins/wp-user-frontend/lib/recaptchalib_noCaptcha.php on line 163`

If I deactivate WPUF everything works fine. For now I have to disable WPUF (or find an alternative).

Duplicated [here](https://wordpress.org/support/topic/blocker-no-captcha-recaptcha-compatibility-problem-cant-log-in/)

**Comment by thebengalboy** [comment]
Hello @d-v-s 

As we tested locally and have not found any issue, it would be very good if you can [reach our support center](http://wedevs.com/contact/). They will check and fix the issue on your site.

Thanks

**Comment by d-v-s** [comment]
Hello @thebengalboy 
As I've described in [this post](https://wordpress.org/support/topic/blocker-no-captcha-recaptcha-compatibility-problem-cant-log-in/#post-10743077) this issue does exist in clean installation.

I kindly ask you to fix it.
Thanks a lot.

**Comment by thebengalboy** [comment]
@mahbubme Please have a look on this

**Comment by mahbubme** [comment]
@d-v-s,

Fixed the issue. The fix will include in the next release.

Thanks
