### ISSUE TITLE
upgrade killed my site

### ISSUE THREAD

**Issue by zavesti** [weDevsOfficial/wp-user-frontend#564]
The moment I upgraded WPUF to new version today (Sep 28, 2018)  - I started getting 500 error message. The site is unreachable now.

**Comment by thebengalboy** [comment]
Hello @zavesti 

Have you updated it from the .org or downloaded and installed manually? Which version you were using?

**Comment by mahbubme** [comment]
Hello @zavesti,

We haven’t heard back from you in a while, so I’m going to mark this as resolved – if you have any further questions, you can start a new thread.

Thanks
