### ISSUE TITLE
New Post Notification checkbox

### ISSUE THREAD

**Issue by gkopec** [weDevsOfficial/wp-user-frontend#568]
Can you change the value of hidden input to "off"?
wp-content/plugins/wp-user-frontend/includes/free/form-element.php:215

**Comment by mahbubme** [comment]
Hello @gkopec,

By default, we keep the new post notification option enabled. You can turn this option off from the form notifications setting instead of changing in core plugin. 

https://prnt.sc/lc2lhn

Thanks
