### ISSUE TITLE
plugin conflicts with another third party plugin

### ISSUE THREAD

**Issue by acmpflorida** [weDevsOfficial/wp-user-frontend#572]
I tried submitting support on wedevs website but their support form is broken.  I am posting here as an issue, so please be kind.  

I installed your plugin to use the forms for our users to submit posts from the front-end.  It was brought to my attention that on my website, unrelated form we use for contact us forms is giving an error:

Sorry you are an error in ajax, please contact the administrator of the website

After some thorough testing, when I disable your plugin, this error goes away.  I have attempted to rollback your plugin to a previous version and going back all the way to 2.8 makes no difference.  I have contact my web host to check. mod security and disabling it did not resolve the error either.

If someone from Support can reach out to me, I would much appreciate it.

**Comment by mahbubme** [comment]
Hello @acmpflorida,

Could you please send an email to support@wedevs.com? Our support team will help you to fix this issue. Please provide your site details there, so that we can debug your site and fix the issue as soon as possible.

Thanks
