### ISSUE TITLE
registration shortcode is not working

### ISSUE THREAD

**Issue by KaziShahHamza** [weDevsOfficial/wp-user-frontend#573]
I am a free user in WP user front-end. The registration shortcode is not working there.

**Comment by mahbubme** [comment]
Hello @KaziShahHamza,

Please make sure that you have set up the registration page perfectly. Here is the documentation: https://wedevs.com/docs/wp-user-frontend-pro/registration-profile-forms/how-to-setup-registrationlogin-page/

Thanks

**Comment by KaziShahHamza** [comment]
Thanks, @mahbubme. I forgot to choose registration page in the settings.

**Comment by mahbubme** [comment]
Great, glad to hear that you got it fixed.
