### ISSUE TITLE
Cannot see WPUF Customfield data in WP-Admin Edit-View for Post when ACF for Wordpress is installed

### ISSUE THREAD

**Issue by Grauen** [weDevsOfficial/wp-user-frontend#574]
I tested this on a fresh install of the current Wordpress version 4.9.8 with the following plugins:
WP User Frontend Version 2.9.3
ACF Version 5.7.7

When looking at the edit view of a post  (doesn't matter whether post type is 'post' or a custom post type)  when logged in as admin, I cannot see the data a user has been submitted for this post.
I activated the WPUF Custom Fields Box.

However:
- When I click on a post to edit it, the "WPUF Custom Fields"-Box will be marked as selected
- But the Box is not visible below the Post itself
- I have to uncheck and check the "WPUF Custom Fields"-Checkbox again
- Then the Box will popup but without any content.

When I disable ACF for Wordpress, the WPUF-CF-Box it will be rendered properly.
But I cannot just remove ACF from my wordpress.

Could you please check first if this is caused by WPUF? I'll contact the ACF-Guys, too - but I hope you'll just check this out...

**Comment by Grauen** [comment]
`add_filter( 'wpuf_hide_meta_when_acf_active', __return_false );`
Seems to fixed this, but I think it should be fixed in the plugin itself, by adding this to the settings menue.

**Comment by mahbubme** [comment]
Hello Grauen,

After integrating WPUF with ACF we removed the WPUF custom fields section from post edit page. What you need to do now create custom fields with ACF and reference the same meta key you used in WPUF form.

Please check the following documentation: [https://wedevs.com/docs/wp-user-frontend-pro/acf-integration/](https://wedevs.com/docs/wp-user-frontend-pro/acf-integration/)

Thank you
