### ISSUE TITLE
Changing Values of Select Boxes Won't Update Existing Entries

### ISSUE THREAD

**Issue by Grauen** [weDevsOfficial/wp-user-frontend#575]
I created a Form with a select box and added multiple entries.

I created some posts and then changed the values for that select box.

Option1:option1 - > Option1:1

The existing posts still had option1 as value for that select field.

wpuf should give the opportunity to update existing values as the value for an option gets updated.

**Comment by Anticosti** [comment]
Indeed. Would also appreciate this.

**Comment by mahbubme** [comment]
Hello @Grauen & @Anticosti,

The update options for that select box will apply for the upcoming posts and the posts which will edit not the existing posts.

Thanks

**Comment by Anticosti** [comment]
@mahbubme
I understand this. Thank you.
