### ISSUE TITLE
Post Excerpt ¿Bug?

### ISSUE THREAD

**Issue by Bolohdotnet** [weDevsOfficial/wp-user-frontend#577]
Hello! Thanks for this perfect project. I am using it and it works excellently, but this feature does not work. I do not know if it's my problem or it's a bug.

Post 1 (test) with custom excerpt
post 2 (oumuamua) not custom excerpt just post content

https://screenshotscdn.firefoxusercontent.com/images/9779bd78-1b23-425a-9f6a-278897a3eba5.png

Again, thank you for this perfect project! in a future we need the premium version! ;)

**Comment by thebengalboy** [comment]
Hello @Bolohdotnet 

Post-Excerpt is not a functionality of WPUF. It's might be coming from your theme. You can try changing your theme.

Thanks

**Comment by Bolohdotnet** [comment]
Oh! so this button is from my theme and not from WPUF?
Field button : https://screenshotscdn.firefoxusercontent.com/images/5242141e-7ce2-4edf-9b9b-e1fe36aa505a.png
Field in WPUF Post Page Form : https://screenshotscdn.firefoxusercontent.com/images/6faea62c-7014-4a9b-aac8-f24499b92177.png 

Anyway, post-excerpt may be a good idea for this project, me and (i think) many others could be thakful if you add a custom post-excerpt

**Comment by Bolohdotnet** [comment]
problem solved! It was a bug of my theme. Specifically in the type of post (post-list) I am now using post-grid / standard and it works perfectly.
