### ISSUE TITLE
Missing string in the Dasboard's Payment column: "Not Applicable"

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#578]
Missing string in the Dasboard's Payment column: "Not Applicable"

Thanks ;-)

**Comment by mahbubme** [comment]
Hello @Anticosti,

"Not Applicable" string is available in the **POT** file. Are you using Loco Translate plugin to translate the strings? If so you need to update the translation files.

Thanks

**Comment by Anticosti** [comment]
@mahbubme
You are correct. My bad. I only had to "Sync" the file and... here it was.
Thank you ;-)
