### ISSUE TITLE
Please: An option to customize the default "thumb" placeholder image

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#579]
Please: Add an option to customize the default "thumb" placeholder image:
wp-user-frontend/assets/images/no-image.png
as shown in the User's Dashboard, when no Featured Image has been set.

Thanks ;-)

**Comment by mahbubme** [comment]
Hello @Anticosti,

You can easily change the default thumb image using **wpuf_no_image** filter. Here is the code example which you can use in the theme's functions.php file.

`function wpuf_default_featured_image() {
	return "https://mahbub.me/wp-content/uploads/2017/01/i.png";
}
add_filter( "wpuf_no_image", "wpuf_default_featured_image" );`

Thanks
