### ISSUE TITLE
User FrontEnd - Form Editor - Add Fields / Field Options Not Displaying

### ISSUE THREAD

**Issue by govhubs** [weDevsOfficial/wp-user-frontend#582]
Using User Front End Pro.  
FF 63.0.3 (64 bit) on Win10
When the browser window is sized to 90% all the field options disappear.
Resizing to 100% or above restores the fields.
It's a glitch (feature) that is not apparent unless someone knows to resize their browser.

![image](https://user-images.githubusercontent.com/31149796/48819334-4d758680-ed04-11e8-9837-18ff7ff2abc1.png)

**Comment by mahbubme** [comment]
Hello @govhubs, 

Please do a check for [theme or plugin conflict](https://mahbub.me/how-to-identify-a-conflicting-theme-or-plugin/). If the issue still persists then contact [here](https://wedevs.com/contact) with your site details. We will be happy to help you. 

Thanks
