### ISSUE TITLE
Add more fields to URL Field 

### ISSUE THREAD

**Issue by Bolohdotnet** [weDevsOfficial/wp-user-frontend#583]
Hi again!

I'm using URL Field in my site to let my users share his source of information. In some cases, they need to put 3/4 (or more) URL's. Its possible in a future add new URL Fields just clicking a "+" button in the URL Field?

CGI Demo in the latest and best graphic design program :rofl: : https://image.ibb.co/fMptEq/b12afe23d461ee318a58fe9e9f4da4d4.png
so , when you click the + button, it adds another field below the previus. I Think it can work with a function of maximum fields setting (1/10?)

regards and have a nice day!

**Comment by mahbubme** [comment]
Hello @Bolohdotnet,

[WPUF pro](https://wedevs.com/wp-user-frontend-pro/) has a repeat field which you can use to allow users to put 3/4 (or more) URL's.

Thanks
