### ISSUE TITLE
Add Time only to Date/Time field

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#584]
Hello,

Please Add The Option ONLY TIME so Users can easy enter their opening and colsing time.
To The Date Field The optional:

Date
Date/Time
Time

Thanks,
Denis

**Comment by VickyFadia** [comment]
Hey is there any update here on this feature:

Having option of time field or same as suggested above

Date
Date/Time
Time

Thanks,
Vicky

**Comment by DenisCGN** [comment]
Any news here? 2 years ago!

**Comment by zamandevs** [comment]
@DenisCGN  will get on coming release.

**Comment by cschot** [comment]
@zamandevs Is there any plan to implement this in the near future?

I would love to write it myself, but I would like to know what you have in mind, to ensure it meets your expectations.
Would you make it an option in the DateTime field? Or an complete seperate field?

**Comment by mmarj** [comment]
> Would you make it an option in the DateTime field? Or an complete seperate field?
→ As we have an existing date/time field so we have to keep in mind other compatibilities/consequences. So till now, we have planned to use our existing field with multiple variations instead of a separate one.
