### ISSUE TITLE
"Edit Profile" page not displaying correctly

### ISSUE THREAD

**Issue by mcmikemn** [weDevsOfficial/wp-user-frontend#591]
It looks like the Edit Profile page doesn't display the Email field correctly. The email field is beneath the First Name and Last Name fields, but the label for the Email field is between the First Name and Last Name fields. In the attached screenshot, you can see it happening and the browser inspector showing the <li> classes in, seemingly, the wrong order?

![screenshot_20181219_194911](https://user-images.githubusercontent.com/46011270/50257209-46f03280-03c8-11e9-8183-46cc85336881.png)

**Comment by thebengalboy** [comment]
Hello @mcmikemn 

Maybe a conflicting issue with the theme you are using or something. Have you tried changing the theme?

Thanks

**Comment by mcmikemn** [comment]
You're right. It took me "forever" to find it, and I still don't understand why, but I changed some styling and it displays correctly. Sorry to bother you.
