### ISSUE TITLE
Edit post from WPUF frontend dashboard, does not keep the first post revision.

### ISSUE THREAD

**Issue by rrishabhraashid** [weDevsOfficial/wp-user-frontend#594]
If a user edits the post from the WP User Frontend, on the backend, WordPress doesn't take it as  Revision. Here are the video details: https://www.youtube.com/watch?v=A-y6Z_6-ONk&feature=youtu.be

**Comment by danielwebhu** [comment]
I have the same problem. After updating a post on the frontend, I can't see Revisions on the WordPress backend. Can you suggest a solution? Thanks!
