### ISSUE TITLE
Google Map doesn't appear on the website after submitting a post

### ISSUE THREAD

**Issue by concertgoer** [weDevsOfficial/wp-user-frontend#598]
Hi,

I have been using WP User Frontend Pro for awhile. Although it mostly works fine, it seems there is an issue with Google Map integration.

I have configured it on Google and I think there is no problem with the configurations, however Google Map doesn't appear after submitting a post from the form.

Google Map DOES appear when I see it on WordPress Dashboard (by selecting WP User Frontend from the menu), but the map doesn't appear after actually submitting the post and the area becomes blank.

I couldn't figure our what the root cause was, however I see the following error message on the dashboard after updating WordPress to the version 5, and I'm guessing that this might be the bug.

Warning: explode() expects parameter 2 to be string, array given in /home/xxxx.com/public_html/wp-content/plugins/wp-user-frontend-pro/includes/render-form.php on line 231

**Comment by emazharulislam** [comment]
Hello @concertgoer, 

first of all sorry for the inconvenience but while I tried to reproduce the scenario locally it seems like everything works smoothly. Could you please contact [here](https://wedevs.com/contact/) with the website details so that we can check the scenario deeply? 

Thanks.
