### ISSUE TITLE
error from wp-login

### ISSUE THREAD

**Issue by marco520** [weDevsOfficial/wp-user-frontend#607]
https://snag.gy/aOCxQX.jpg;
shop2?

**Comment by emazharulislam** [comment]
Hello @marco520,

After getting your issue, I did a fresh installation of WordPress and tried to reproduce your issue but failed. That’s why It needs to debug the issue on your site then. I’d recommend you to [get in touch](https://wedevs.com/contact/) with our technical team with the website details for further assistance.

Thanks.
