### ISSUE TITLE
Filter User By Status not working

### ISSUE THREAD

**Issue by pankaj91as** [weDevsOfficial/wp-user-frontend#608]
Filter User by Status not working which is under Users tab.

**Filter building wrong query**
`FROM wp_users INNER JOIN wp_usermeta ON ( wp_users.ID = wp_usermeta.user_id ) INNER JOIN wp_usermeta ON ( wp_users.ID = wp_usermeta.user_id )

WHERE 1=1 AND ( wp_usermeta.meta_key = 'wp_capabilities' ) AND ( (wp_usermeta.meta_key = 'wpuf_user_status' AND CAST(wp_usermeta.meta_value AS CHAR) = 'pending') )`

**Need Correction**
`FROM wp_users INNER JOIN wp_usermeta ON ( wp_users.ID = wp_usermeta.user_id )

WHERE ( (wp_usermeta.meta_key = 'wpuf_user_status' AND CAST(wp_usermeta.meta_value AS CHAR) = 'pending') )`

Correction in **filter_by_status** function in **class-new-user-approve.php**
```
if ( $this->selected_status() != null ) {
     $filter = $this->selected_status();

     // $query->query_from .= " INNER JOIN {$wpdb->usermeta} ON ( {$wpdb->users}.ID = $wpdb->usermeta.user_id )";

     if ( 'approved' == $filter ) {
           $query->query_fields = "DISTINCT SQL_CALC_FOUND_ROWS {$wpdb->users}.ID";
           $query->query_from  .= " LEFT JOIN {$wpdb->usermeta} AS mt1 ON ({$wpdb->users}.ID = mt1.user_id AND mt1.meta_key = 'wpuf_user_status')";
           $query->query_where .= " AND ( ( $wpdb->usermeta.meta_key = 'wpuf_user_status' AND CAST($wpdb->usermeta.meta_value AS CHAR) = 'approved' ) OR mt1.user_id IS NULL )";
     } else {
            // $query->query_where .= " AND ( ($wpdb->usermeta.meta_key = 'wpuf_user_status' AND CAST($wpdb->usermeta.meta_value AS CHAR) = '{$filter}') )";
            $query->query_where = " WHERE ( ($wpdb->usermeta.meta_key = 'wpuf_user_status' AND CAST($wpdb->usermeta.meta_value AS CHAR) = '{$filter}') )";
     }
}
```

**Comment by mahbubme** [comment]
Hello @pankaj91as,

I have checked the query issue on my local side but failed to reproduce. Could you please contact [here](https://wedevs.com/contact) with your site details? I will be happy to help you.

Thanks
