### ISSUE TITLE
Subscription with no fees (Dashboard issue)

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#611]
Greetings,

I have a site where it's free to subscribe. Now, when the user goes to his Dashboard, there is this column that would be nice to hide:
Payment:	Not Applicable

Thanks,

**Comment by thebengalboy** [comment]
Hello @Anticosti 

The Payment attribute on Dashboard will be by default turned on. To turn the Payment column off, add the following shortcode to your Dashboard page: `[wpuf_dashboard payment_column="off"]`. And to turn it on again, use the following shortcode: `[wpuf_dashboard payment_column="on"]`

Thanks

**Comment by Anticosti** [comment]
@thebengalboy Thank you so much. That works perfect.
All my gratitude,
