### ISSUE TITLE
Update failed with WPUF Shortcodes

### ISSUE THREAD

**Issue by joedoeee** [weDevsOfficial/wp-user-frontend#613]
Hi,

Everytime I try to install a page with any of the WPUF shortcodes, it says "update failed" and it won't load the page, if I use WPBakery I can get it on there but this isn't ideal.

Any help would be appreciated!

Thanks!

Gabe

**Comment by mahbubme** [comment]
Hello @joedoeee,

We have fixed this issue in the development version. Please wait for the next release, you will get it fixed. 

Please note that we are going to release version 3.1.0 today. 

Thanks
