### ISSUE TITLE
Transactions listing stays empty after a live PayPal payment

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#619]
wp-admin/admin.php?page=wpuf_transaction
This page's listing stays empty after a live PayPal payment.
Nothing shows under:

ID | Status | User | Cost | Tax | Post ID | Pack ID | Gateway | Payer | Email | Trans ID | Date

**Comment by mahbubme** [comment]
Hello @Anticosti,

Could you please create a support ticket [here](https://wedevs.com/contact) with your site details? I will be happy to check your payment issue.

Thanks

**Comment by Anticosti** [comment]
Thank you @mahbubme,
I created a ticket:
#128859

**Comment by Anticosti** [comment]
This has been solved.
