### ISSUE TITLE
Missing strings for Invoices in [wpuf_account]

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#620]
I have been able to translate all tabs Titles, except for "Invoices" and it's sub titles:
"Invoice" and "Download Link"

**Comment by Anticosti** [comment]
oh! Also I wanted to bring your attention to the fact that nothing shows beneath "Invoice" and "Download Link". This, even if this user has legitimely subscribed to a package. The user should be able to download his/her Invoice from there but.... nothing

**Comment by Anticosti** [comment]
For the strings: 
Got it sorted out. I had a misconfiguration on "Loco Translate"

**Comment by mahbubme** [comment]
Hello @Anticosti, 

Excellent! nice to hear that you were able to get that sorted out.

Thanks
