### ISSUE TITLE
Suddenly: When editing a CPT Post Form, Categories get scrambled up

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#624]
Greetings,
A screenshot to show the problem:

**Comment by Anticosti** [comment]
It has to do with ACF

**Comment by thebengalboy** [comment]
Hello @Anticosti 

Did you mean, the category could not be edited when a post editing from the frontend?

We have already fixed this #625 

Thanks

**Comment by Anticosti** [comment]
Hello @thebengalboy,
Hope this screenshot will help you understand what I mean:
https://www.dropbox.com/s/trex2nz9a6dtd99/S%C3%A9lection_011.png?dl=0

Regards,

**Comment by mahbubme** [comment]
Hello @Anticosti,

I understand what you mean. As you are editing a custom post type form, the taxonomy fields will refer to the related post type taxonomies and the post type name will add as a prefix. Also, default post type taxonomies are related to CPT taxonomies.

Thanks for your understanding.
