### ISSUE TITLE
Unable to edit CPT posts from dashboard

### ISSUE THREAD

**Issue by weblad** [weDevsOfficial/wp-user-frontend#626]
Hi,

When I'm using the form to create standard posts I can see and edit my posts in the dashboard - but when I'm creating posts in a CPT (Spaces) I cant see any of the posts I've created. My dashboard it says I have 0 posts.

<img width="652" alt="screenshot_26" src="https://user-images.githubusercontent.com/45124105/52489784-11dbb180-2bbb-11e9-9bdd-d043b40542da.png">
<img width="805" alt="screenshot_27" src="https://user-images.githubusercontent.com/45124105/52489785-12744800-2bbb-11e9-9923-d1f2ec8ad2d8.png">
<img width="772" alt="screenshot_28" src="https://user-images.githubusercontent.com/45124105/52489853-3a63ab80-2bbb-11e9-80e7-a1739b6c75bc.png">

**Comment by thebengalboy** [comment]
Hello @weblad 

To allow multiple post types on the dashboard, simply insert this shortcode: `[wpuf_dashboard post_type="post_type_name, custom_post_type_name"]`

There have a few more options as well. Follow this documentation-> https://wedevs.com/docs/wp-user-frontend-pro/getting-started/user-dashboard/

Thanks
