### ISSUE TITLE
Date field autofill covers the datepicker

### ISSUE THREAD

**Issue by Wp-business** [weDevsOfficial/wp-user-frontend#627]
In chrome, and maybe other browsers to the autocomplete on the date input covers the datepicker.

I placed some code in the input field to fix this:
autocomplete="off"

Though after an update it will be gone.
It might be good to insert the code in the plugin as default on the date/datepickers field.

**Comment by mahbubme** [comment]
Hello @Wp-business,

Turned off autocomplete for the date field. You will get it from the next release. 

Thanks
