### ISSUE TITLE
form keeps resetting to "send notifications" every time it is edited.

### ISSUE THREAD

**Issue by donwinchell** [weDevsOfficial/wp-user-frontend#628]
unlike #395,  I am able to turn off notifications, but every time I go back and edit the form (in form creation, not editing a post created by a form), the "send notifications" checkbox is checked again.  I uncheck it, and no notifications are sent,  but the next time I edit, the box gets checked again.

**Comment by mahbubme** [comment]
Hello @donwinchell,

There might be a theme or plugin conflict, please check and let me know the updates. If you are unable to find the reason then create a support ticket [here](https://wedevs.com/contact) with your site details. I will be happy to help you.

Thanks
