### ISSUE TITLE
Upgrade to 3.1.0 causes fatal error

### ISSUE THREAD

**Issue by richardtvaughan** [weDevsOfficial/wp-user-frontend#629]
Once updated to 3.1.0 we get a fatal errer:
`Fatal error: Class 'WPUF_Frontend_Render_Form' not found in /var/www/html/wp-content/plugins/wp-user-frontend-pro/includes/frontend-form-profile.php on line 7`

**Comment by Anticosti** [comment]
I would try re-uploading the plugin.

**Comment by mahbubme** [comment]
Hello @richardtvaughan,

Have you resolved the issue? If not please contact [here](https://wedevs.com/contact) with your site details. I will be happy to help you.

Thanks
