### ISSUE TITLE
Email notification show attachment path instead number!

### ISSUE THREAD

**Issue by lorenzo-liquid** [weDevsOfficial/wp-user-frontend#630]
Hello everyone!

If I add a custom field in the email notification like:
Price: %custom_pricefield%
It turns the price number es 1200,00 into an image path that has the ID set to 1200 for example!

It's very weird, it's like it turns numbers into media path that has the same value as ID.

Please help!

**Comment by mahbubme** [comment]
Hello @lorenzo-liquid, 

I am unable to reproduce this issue on our side. There might be a theme or plugin conflict. Could you please send your site details [here](https://wedevs.com/contact/)? We will be happy to help you.

Thanks
