### ISSUE TITLE
Redirect to specific Page after Email-Verification

### ISSUE THREAD

**Issue by MPHood** [weDevsOfficial/wp-user-frontend#632]
Hey guys! Right now after the Email-Verification the "logged in User" will be redireted to the Login Page. 

How can i redirect the user to a specific page after Email Activation?

**Comment by emazharulislam** [comment]
Hello @MPHood,

Although you can control the login/registration form the WPUF settings, I am afraid at this moment WP User Frontend doesn't have such an option by default which will allow you to achieve your requirements. Still, check more details about the Login/Registration settings from here: https://wedevs.com/docs/wp-user-frontend-pro/settings/login-registration-settings/

Regards.
