### ISSUE TITLE
Shortcode [wpuf-edit] resizes whole page in Elementor Pro

### ISSUE THREAD

**Issue by CarDesignPro** [weDevsOfficial/wp-user-frontend#635]
Hi,

I've got technical problem with WP User Frontend Pro. I think there is a little conflict with Elementor Pro plugin, because when I want to place [wpuf-edit] shortcode in a column then it resizes whole page. I don't know what's the reason exactly, but before everything was fine. Please help

Best Regards
Marcin Wasilewski
https://cardesignpro.net

![wpuf-issue-1](https://user-images.githubusercontent.com/47713894/52912859-577d3600-32af-11e9-929e-367d4d8a0978.jpg)
![wpuf-issue-2](https://user-images.githubusercontent.com/47713894/52912860-5815cc80-32af-11e9-8dac-69d4260d5cda.jpg)

**Comment by emazharulislam** [comment]
Hello,

[wpuf_edit] shortcode has nothing to do in the frontend. It just renders the post form to edit a certain post that was used to create the post. IF you like to enable that, the user can edit/delete posts from the frontend just create a page with that shortcode and configure it form the WPUF settings. Check this [video.](https://drive.google.com/file/d/17PT8m8TB8G4KLnV6tptABfhBwVbVaRbd/view) 

Thanks.

**Comment by mahbubme** [comment]
Hello @CarDesignPro,

It can be fixed by using custom CSS. Can you do it? or you can share your site details [here](https://wedevs.com/contact). We will be happy to provide you the custom CSS. 

Thanks

**Comment by OverSysDev** [comment]
Hi,

I have exactly the same problem. Inserting the short code [wpuf-edit] into the "shortcode widget" of Elementor Pro, the page layout is broken. But, if I use [wpuf_form id = "X"] or [wpuf_dashboard post_type = "your_post_type"] these work perfectly.

Have any idea how to solve it?
Thanks.

**Comment by OverSysDev** [comment]
More info, when trying to save the page (edited with Elementor Pro) the following message appears:
The update failed. Error message: The response is not a valid JSON response.
If I remove the short code [wpuf-edit] the error disappears.

If I put the short code [wpuf-edit] directly on the page (without using Elementor Pro), the page is saved correctly. Obviously there is a conflict between both plugins. But I don't know how to solve it.
