### ISSUE TITLE
Multistep progressbar styles doesn't show correctly (screenshot)

### ISSUE THREAD

**Issue by CarDesignPro** [weDevsOfficial/wp-user-frontend#636]
Multistep progressbar doesn't show correctly on my page:

![wpuf-issue-3](https://user-images.githubusercontent.com/47713894/52913125-ad9fa880-32b2-11e9-89a8-5b576446d339.jpg)

**Comment by emazharulislam** [comment]
Hello,

Actually, the Multistep progress bar is showing correctly but it seems like your theme's CSS is overriding the WPUF forms style CSS. For testing purpose Switch to the default WordPress theme and check the form.

Thanks.
