### ISSUE TITLE
Please allow us to use only a few countries of our choice

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#638]
Hi,

When you go to:
/myaccount/?section=billing-address
the country dropdown at the bottom carries too many countries.
For our needs, we need to concentrate on North America only.

Thanks,

**Comment by mahbubme** [comment]
Hello @Anticosti,

You can do it by customizing the following file location.

**wp-user-frontend/includes/countries-state.php**
Line: 12

Thanks

**Comment by Anticosti** [comment]
Thank you mahbubme ;-)
