### ISSUE TITLE
YouTube video preview is not generating

### ISSUE THREAD

**Issue by hirushacooray** [weDevsOfficial/wp-user-frontend#642]
Hi,

When I copy and paste a video URL (eg: YouTube) it doesn’t display the preview of the video in the front-end form like WP back-end editor. Is there a fix for this issue?

Thanks
Cooray

**Comment by emazharulislam** [comment]
Hello,

First of all, it's not an issue. Actually, at this moment, WP User Frontend doesn't have any integration/default option, which will display the preview of the video in the front-end form while using the embed/paste the URL. The video will appear on the post after the post is submitted.

Thanks.
