### ISSUE TITLE
The item in ajax taxonomy field is not selected

### ISSUE THREAD

**Issue by pm-yosuke** [weDevsOfficial/wp-user-frontend#644]
The item in ajax taxonomy field is not selected when parent's term_id > child's term_id.

[includes/fields/class-field-post-taxonomy.php  L.184](https://github.com/weDevsOfficial/wp-user-frontend/blob/develop/includes/fields/class-field-post-taxonomy.php#L184)

```php
                asort( $this->terms );
```

**Comment by mahbubme** [comment]
Hello @pm-yosuke,

I have tried to reproduce this issue on my side but failed. Could you please give me the instructions so that I can reproduce it and help you to fix the issue?

Thanks

**Comment by pm-yosuke** [comment]
Hi @mahbubme ,

Here is what I did:

## Step 1. Create categories
First, create a child category (ex: term_id#2, Tokyo).
Next, create a parent category (ex: term_id#3, Asia).
Then, set the parent category (Asia > Tokyo).

![Screenshot_2019-03-28 Categories ‹ For Develop Plugin — WordPress](https://user-images.githubusercontent.com/36524683/55147529-e708e500-5189-11e9-85de-cd1cf29a665a.png)

## Step 2. Edit post form using WPUF
Add a category field and set Advanced Options:
* Type: Ajax
* Selection Type: Child of

![Screenshot_2019-03-28 Post Forms ‹ For Develop Plugin — WordPress](https://user-images.githubusercontent.com/36524683/55147547-f12ae380-5189-11e9-8702-928f8fbb1d86.png)

## Step 3. Create post
Create a post with category Asia > Tokyo.

![Screenshot_2019-03-28 Posts ‹ For Develop Plugin — WordPress](https://user-images.githubusercontent.com/36524683/55147694-318a6180-518a-11e9-9d60-169ec701bd50.png)

## Step 4. Edit post in WPUF form

![Screenshot_2019-03-28 Edit – For Develop Plugin(1)](https://user-images.githubusercontent.com/36524683/55147801-6696b400-518a-11e9-9f20-09cf414794d6.png)

Thanks

**Comment by mahbubme** [comment]
Hello @pm-yosuke,

Thanks for your explanation. We are checking the issue.
