### ISSUE TITLE
Unable to render the events on the front-end.

### ISSUE THREAD

**Issue by emazharulislam** [weDevsOfficial/wp-user-frontend#645]
While using [The Event Calendar Integration](https://wedevs.com/docs/wp-user-frontend-pro/posting-forms/the-events-calendar-integration-template/) with WPUF I am able to create the events but unable to render the event on any page by using the shortcode like this [[wpuf_dashboard post_type="tribe_events"]](https://wedevs.com/docs/wp-user-frontend-pro/getting-started/user-dashboard/), although I am able to render the WooCommerce products.

**Comment by galvanos28** [comment]
Thank you for looking into this. the shortcut [wpuf_dashboard post_type="tribe_events"] does not work unless post type 'posts' is also included in the shortcut, so i'm unable to just view the events in a dashboard page. Any ideas if this could make it in the next release and by when the release should happen?
