### ISSUE TITLE
Conflicts with a third-party plugin.

### ISSUE THREAD

**Issue by emazharulislam** [weDevsOfficial/wp-user-frontend#646]
If I activated the '[WooCommerce Multivendor Marketplace](https://wordpress.org/plugins/wc-multivendor-marketplace/)' plugin, the User Frontend menu disappeared from the admin menu bar in the WordPress admin area.

**Comment by mahbubme** [comment]
Change the priority from 55 to 99. Here is the file location: 

**/wp-user-frontend/admin/class-admin-settings.php**

Line: 87
