### ISSUE TITLE
Settings Panel Not Showing Up on Edit Screen

### ISSUE THREAD

**Issue by classiccity** [weDevsOfficial/wp-user-frontend#655]
I am trying to adjust the settings of a form, however, the Settings panels don't show up.

You can see it in action here: https://youtu.be/iDVlKH4yu1s

I checked the Console as well and didn't have any JS errors.

Thanks!

**Comment by emazharulislam** [comment]
Hello @classiccity 

I have checked your provided video and I can see that you are using a way older version of WP User Frontend. The latest version of [WP User Frontend is 3.1.3](https://wordpress.org/plugins/wp-user-frontend/). Update your WP User Frontend into the latest version, after doing that please check the full scenario again.

Best regards.
