### ISSUE TITLE
Missing International phone Fields like acf have

### ISSUE THREAD

**Issue by fracii** [weDevsOfficial/wp-user-frontend#658]
Hi,

Im missing this field type for international phone number: https://github.com/squarecandy/acf-intl-tel-input

Can we code this in to wpuf?

**Comment by fracii** [comment]
Anyone?

**Comment by fracii** [comment]
@tareq1988 @squarecandy

**Comment by sapayth** [comment]
Added in version 3.4.11 of WP User Frontend Pro
