### ISSUE TITLE
WPUF user posts not Pending Review

### ISSUE THREAD

**Issue by dennisgaya** [weDevsOfficial/wp-user-frontend#666]
![Untitled](https://user-images.githubusercontent.com/6926791/57901360-18f41900-78a8-11e9-87a1-ff391ef80898.png)
I've set new user submissions/posts to come in as 'Pending review' under WPUF settings, but i'm still getting new unapproved posts being published directly on my website.... What could the problem be?

**Comment by mahbubme** [comment]
Hello @dennisgaya,

I did try to reproduce this issue on my side but failed. Could you please [contact](https://wedevs.com/contact/) our support team with your site details? 

Thanks
