### ISSUE TITLE
WPUF frontend pages responsiveness improvement.

### ISSUE THREAD

**Issue by emazharulislam** [weDevsOfficial/wp-user-frontend#667]
When viewing the Account Dashboard the page doesn't seem fully responsive. Although it's ok on most of the big screens ( Desktop/Laptop/Ipad ), on the mobile screens it's really hard to read the Account Dashboard's menu. As the mobile users are growing it's really important that all the WPUF frontend page will appear properly.

**Comment by mahbubme** [comment]
https://github.com/weDevsOfficial/wp-user-frontend/commit/41f38378c3f05d394a3a800527b3fc269e506f77
