### ISSUE TITLE
Need hide the first Country choice and put a "Please Select"

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#671]
In the Dashboard: Billing Address, I need to hide "**Afghanistan**".
My project is _North American_ only. With the code below, I found the way to just keep "**Canada**" and "**United States**" for "Country" choices. I need to find a way to also hide "Afghanistan".
Notice in the code below: 
`option[value="AF"] {
	display:none;
	visibility:hidden;
}`

`option[value="AF"],option[value="AX"],option[value="AL"],option[value="DZ"],option[value="AS"],option[value="AD"],option[value="AO"],option[value="AI"],option[value="AQ"],option[value="AG"],option[value="AR"],option[value="AM"],option[value="AW"],option[value="AU"],option[value="AT"],option[value="AZ"],option[value="BS"],option[value="BH"],option[value="BD"],option[value="BB"],option[value="BY"],option[value="BE"],option[value="BZ"],option[value="BJ"],option[value="BM"],option[value="BT"],option[value="BO"],option[value="BQ"],option[value="BA"],option[value="BW"],option[value="BV"],option[value="BR"],option[value="IO"],option[value="BN"],option[value="BG"],option[value="BF"],option[value="BI"],option[value="KH"],option[value="CM"],option[value="CV"],option[value="KY"],option[value="CF"],option[value="TD"],option[value="CL"],option[value="CN"],option[value="CX"],option[value="CC"],option[value="CO"],option[value="KM"],option[value="CG"],option[value="CD"],option[value="CK"],option[value="CR"],option[value="CI"],option[value="HR"],option[value="CU"],option[value="CW"],option[value="CY"],option[value="CZ"],option[value="DK"],option[value="DJ"],option[value="DM"],option[value="DO"],option[value="EC"],option[value="EG"],option[value="SV"],option[value="GQ"],option[value="ER"],option[value="EE"],option[value="ET"],option[value="FK"],option[value="FO"],option[value="FJ"],option[value="FI"],option[value="FR"],option[value="GF"],option[value="PF"],option[value="TF"],option[value="GA"],option[value="GM"],option[value="GE"],option[value="DE"],option[value="GH"],option[value="GI"],option[value="GR"],option[value="GL"],option[value="GD"],option[value="GP"],option[value="GU"],option[value="GT"],option[value="GG"],option[value="GN"],option[value="GW"],option[value="GY"],option[value="HT"],option[value="HM"],option[value="VA"],option[value="HN"],option[value="HK"],option[value="HU"],option[value="IS"],option[value="IN"],option[value="ID"],option[value="IR"],option[value="IQ"],option[value="IE"],option[value="IM"],option[value="IL"],option[value="IT"],option[value="JM"],option[value="JP"],option[value="JE"],option[value="JO"],option[value="KZ"],option[value="KE"],option[value="KI"],option[value="KP"],option[value="KR"],option[value="KW"],option[value="KG"],option[value="LA"],option[value="LV"],option[value="LB"],option[value="LS"],option[value="LR"],option[value="LY"],option[value="LI"],option[value="LT"],option[value="LU"],option[value="MO"],option[value="MK"],option[value="MG"],option[value="MW"],option[value="MY"],option[value="MV"],option[value="ML"],option[value="MT"],option[value="MH"],option[value="MQ"],option[value="MR"],option[value="MU"],option[value="YT"],option[value="MX"],option[value="FM"],option[value="MD"],option[value="MC"],option[value="MN"],option[value="ME"],option[value="MS"],option[value="MA"],option[value="MZ"],option[value="MM"],option[value="NA"],option[value="NR"],option[value="NP"],option[value="NL"],option[value="NC"],option[value="NZ"],option[value="NI"],option[value="NE"],option[value="NG"],option[value="NU"],option[value="NF"],option[value="MP"],option[value="NO"],option[value="OM"],option[value="PK"],option[value="PW"],option[value="PS"],option[value="PA"],option[value="PG"],option[value="PY"],option[value="PE"],option[value="PH"],option[value="PN"],option[value="PL"],option[value="PT"],option[value="PR"],option[value="QA"],option[value="RE"],option[value="RO"],option[value="RU"],option[value="RW"],option[value="BL"],option[value="SH"],option[value="KN"],option[value="LC"],option[value="MF"],option[value="PM"],option[value="VC"],option[value="WS"],option[value="SM"],option[value="ST"],option[value="SA"],option[value="SN"],option[value="RS"],option[value="SC"],option[value="SL"],option[value="SG"],option[value="SX"],option[value="SK"],option[value="SI"],option[value="SB"],option[value="SO"],option[value="ZA"],option[value="GS"],option[value="SS"],option[value="ES"],option[value="LK"],option[value="SD"],option[value="SR"],option[value="SJ"],option[value="SZ"],option[value="SE"],option[value="CH"],option[value="SY"],option[value="TW"],option[value="TJ"],option[value="TZ"],option[value="TH"],option[value="TL"],option[value="TG"],option[value="TK"],option[value="TO"],option[value="TT"],option[value="TN"],option[value="TR"],option[value="TM"],option[value="TC"],option[value="TV"],option[value="UG"],option[value="UA"],option[value="AE"],option[value="GB"],option[value="UM"],option[value="UY"],option[value="UZ"],option[value="VU"],option[value="VE"],option[value="VN"],option[value="VG"],option[value="VI"],option[value="WF"],option[value="EH"],option[value="YE"],option[value="ZM"],option[value="ZW"] {
	display:none;
	visibility:hidden;
}`

Wish there would be a way to put a "**Please Select**" as first choice, if nothing is yet enetered?
This way, I think my CSS above would work.

Thank you.

**Comment by Anticosti** [comment]
Is this solved?

**Comment by mahbubme** [comment]
Hello @Anticosti,

Yes, the issue has been solved. Added `select country` text as the first option.

**Comment by Anticosti** [comment]
Thank you @mahbubme
Much appreciated.
