### ISSUE TITLE
Plugin causes fatal error on site with oceanwp theme

### ISSUE THREAD

**Issue by birdbrainsolutions** [weDevsOfficial/wp-user-frontend#676]
Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, WP User Frontend.

First, visit your website (https://5x55method.com/) and check for any visible issues. Next, visit the page where the error was caught (https://5x55method.com/wp-admin/options-general.php?page=my-custom-functions&settings-updated=true) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

**Comment by mahbubme** [comment]
Hello @birdbrainsolutions,

Could you please [contact](https://wedevs.com/contact/) our support team? We may need your site details for debugging.

Thank you
