### ISSUE TITLE
Error message: "User already verified" shows, instead of Success message

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#677]
**01.** User register himself from Frontend;
**02.** User then receives this email message:
Congrats! You are Successfully registered to my site.
To activate your account, please click the link below:<br>
<a href="https://omitted-domainname.com/connexion-login?wpuf_registration_activation=194777a1c611647e22ce443eddbf1c3b31bb9a11&id=21">Activate your account</a>
Thanks!
**03.** User click on the link in the email;
**04.** The user is brought to this URL:
/connexion-login/?wpuf_registration_activation=194777a1c611647e22ce443eddbf1c3b31bb9a11&id=21
and it shows an Error message:
`<div class="**wpuf-error**">User already verified</div>`

This is misleading. The message should be a Success message:
`<div class="**wpuf-success**">Congrats! You are Successfully registered.</div>`
like in the next email he receives:
_Congrats! Your account has been activated. You can now login..._

**Comment by mahbubme** [comment]
Hello @Anticosti,

Please add the following code in the theme's functions.php file.

`add_filter('redirect_canonical', '__return_false');`

Please note that this problem is site-specific not plugin issue, so you have to use this code.

Thanks

**Comment by Anticosti** [comment]
Greetings @mahbubme 
Thank you for your suggestion. Although, I use **Oxygen Builder** which does not have any physical theme as we know. So no function.php file to put your code in.
I am using  **[Code Snippets](https://wordpress.org/plugins/code-snippets/)** plugin.
So I just copied/paste your above code into a new snippet and... no change to this issue.
Any suggestion?

**Comment by mahbubme** [comment]
Please contact [here](https://wedevs.com/contact/) with your site details. We will be happy to help you.

**Comment by Anticosti** [comment]
Done. Thanks!

**Comment by Anticosti** [comment]
You received my two emails?

**Comment by mahbubme** [comment]
Please wait for the response from our support team. 

Thank you
