### ISSUE TITLE
Issue with billing address

### ISSUE THREAD

**Issue by thebengalboy** [weDevsOfficial/wp-user-frontend#678]
I have enabled the billing address when payment from the customizer. Users inputting their billing address when they are purchasing the subscription. But, the billing address doesn't save to their profile. Neither it comes with the invoice.

Thanks

**Comment by Anticosti** [comment]
Thanks for posting this very important issue.

**Comment by Anticosti** [comment]
@thebengalboy
By the way: Is there a way to move the "Country*" and "State/Province/Region*" fields at the bottom?
Like in this logical order:
...
State/Province/Region
Postal code/Zip
Country
![Sélection_189](https://user-images.githubusercontent.com/5446224/58656370-2b2f7780-82ea-11e9-928d-4192896e2a92.png)

**Comment by Anticosti** [comment]
Is there a fix coming for this issue?

**Comment by Anticosti** [comment]
I also have enabled the billing address when payment from the customizer. Users inputting their billing address when they are purchasing the subscription. PayPal payment is not working.

**Comment by Anticosti** [comment]
Still not working in this version

**Comment by mahbubme** [comment]
Hello @Anticosti,

Is it the saving issue or you get an error message?

**Comment by Anticosti** [comment]
I fill all the required fields and click on "Proceed" button and then get this Popup error message:
"www.mysite.com says
Some Required Fields are not filled!"

**Comment by mahbubme** [comment]
@Anticosti,  I think this is a site specific issue. Could you please [contact](https://wedevs.com/contact/) our support team with your site details?

**Comment by Anticosti** [comment]
Check support ticket ##167054
all the details are in there since June

**Comment by Anticosti** [comment]
I did all the necessary tests: no other plugin; swithed theme; 
Always the same behavior

**Comment by mahbubme** [comment]
We have already checked this scenario on our local development server but no error after submitting the `Proceed` button. So, it's not possible to guide you without checking the site.

Thank you

**Comment by Anticosti** [comment]
Do you have access to my support ticket?

**Comment by mahbubme** [comment]
No, the support team will forward your case, so no worries.

**Comment by Anticosti** [comment]
I start thinking that I have putted a bit too much faith in you guys.
I feel really bad right now. All these efforts for nothing at the end...

**Comment by mahbubme** [comment]
@Anticosti, I just checked your support ticket. It seems there is a misunderstanding about the issue. The issue you have right now and the issue we fixed is totally different. We have fixed the saving issue, but the error after submitting the button not exist. However, I apologise on behalf of my support team, they were unable to understand the issue.  

You already provided the site details, so please give me 2/3 hours. I will update you soon regarding the error. 

Thanks for your understanding.

**Comment by Anticosti** [comment]
Oufff!!! Thanks for taking the time. 
Will check back in the middle of the night here (Toronto America Time).
Big hopes...

**Comment by mahbubme** [comment]
@Anticosti, The login credentials you provided is not working. Can you send the right credentials in that support ticket?

**Comment by Anticosti** [comment]
Sure. In five minutes...

**Comment by Anticosti** [comment]
Sent as a reply to the ticket #167054

**Comment by mahbubme** [comment]
@Anticosti, Still not working. 

Reference: https://www.loom.com/share/793d46202cfa4123a43799c517e529ae?focus_title=1&muted=1

**Comment by Anticosti** [comment]
Two minutes. I'll create new password for you...

**Comment by Anticosti** [comment]
Sent. Is it working now?

**Comment by Anticosti** [comment]
Oh! Sorry. My bad. Will unlock it.

**Comment by Anticosti** [comment]
Should be good now...
Really sorry to have forgotten to unlock

**Comment by mahbubme** [comment]
Perfect, I will update you soon.

Thanks

**Comment by mahbubme** [comment]
@Anticosti, I have fixed the issue. Please check your site now. 

Thanks

**Comment by Anticosti** [comment]
@mahbubme
Checking now....

**Comment by Anticosti** [comment]
That seems to work now. Cool.
Now... while at it, would it be too much asked to move these two fields: 
Country*
State/Province/Region* 

In between:
City* and Postal Code/ZIP*

?

**Comment by Anticosti** [comment]
This would give as final result:

Address Line 1 *
Address Line 2 
City*
State/Province/Region*
Postal Code/ZIP*
Country*

**Comment by Anticosti** [comment]
Greetings @mahbubme 
After your fix and intervention from last night, should I now download and install the latest **WP User Frontend Pro - Personal v3.1.7**
Thank you for your quick reply.

**Comment by mahbubme** [comment]
Hello @Anticosti,

I have uploaded the WP User Frontend develop version. So, you just need to use WPUF Pro latest version. 

Also, it's not possible to keep the Country & State fields at the bottom, because after selecting the country the state loads based on coutry name selection. 

Thanks for your understanding.

**Comment by Anticosti** [comment]
Thank you @mahbubme !
Thank you for the info. Very well explained. I understand. 
Take care!
See you :)
