### ISSUE TITLE
Subscription Upgrade Procedure

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#679]
Greetings,

I have this very important questioning **before launching**.
**Here is the scenario**:
**01.** July 1st 2019: A new customer Buys/Sign Up a subcription pack named: **Bronze** Pack
**02.** October 15th 2019: Same customer wants to upgrade to a superior pack: **Silver** Pack

How would this be handled by **WP Frontend User Pro** and **PayPal**?
Or which operations would be needed to operate this goal **seamlesly**?

Thank you in  advance,

**Comment by mahbubme** [comment]
The user needs to cancel the current pack from WPUF frontend account page, then purchase a new pack, in your case, this is "Silver Pack".

Thank you

**Comment by Anticosti** [comment]
Thank you @mahbubme
