### ISSUE TITLE
Billing Address from the Customizer: Not Working!

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#681]
**01**. Activate Billing Address from the Customizer;
**02**. Click on a Pack you want to buy;
**03**. Fill all the required fields;
**04**. You'll get a **Popup Error Message**: 
**_"Some Required Fields are not filled!"_**

**Comment by Anticosti** [comment]
In my **php_errorlog**:
[01-Jun-2019 04:15:44 UTC] PHP Warning:  Illegal string offset 'expire' in /hiddenpath/wp-content/plugins/wp-user-frontend-pro/includes/class-subscription.php on line 187

**Comment by Anticosti** [comment]
line 187:
`                $exp_time  = date_create( $sub['expire'] );`

**Comment by mahbubme** [comment]
Hello @Anticosti,

I think this is your site-specific issue as I cannot reproduce the same scenario on my local development server. Please [contact](https://wedevs.com/contact/) our support team with your site details, we will be happy to help you.

Thank you
