### ISSUE TITLE
Account page: Option(s) to set which tab shows as active

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#683]
/account/
should by default lead to: 
/account/?section=dashboard

This way, the Dashboard tab would carry the ".active" class by default

Would be nice if we could choose in the "My Account" settings, which tab should be set as active by default when opening the page...

**Comment by mahbubme** [comment]
@Anticosti 

An option has been added to set which tab shows as active on the front-end account page. You will get it in the next release. 

![1](https://user-images.githubusercontent.com/10685760/64666837-7fb1c980-d479-11e9-9f96-7029e3d7acd0.png)

Thanks

**Comment by Anticosti** [comment]
Thank you @mahbubme
Much appreciated.
