### ISSUE TITLE
Invoice - PDFs - Needs some tweaks

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#684]
![Sélection_206](https://user-images.githubusercontent.com/5446224/59149880-6831f300-89e9-11e9-82f1-4e2db2ddcb2c.png)

**Comment by Anticosti** [comment]
Will this be addressed soon?

**Comment by mahbubme** [comment]
Hello @Anticosti,

We are not thinking to change the current design of PDF invoice. Hopefully, we will consider in future. 

Thanks
