### ISSUE TITLE
Social Login & Registration - Styling issue and Error

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#685]
01. Activate Module: Social Login & Registration
02. Configure Facebook App Settings
03. Visit your **Log In** page
04. You will have this:
![Sélection_208](https://user-images.githubusercontent.com/5446224/59160864-0042e180-8aa9-11e9-9452-c8ba621e3c70.png)

05. Visit your **Register** page
06. You will have this:
![Sélection_207](https://user-images.githubusercontent.com/5446224/59160877-31bbad00-8aa9-11e9-9d0b-26c19dab16a7.png)

07. Also when you click on the Facebook button, it shows this error:
**URL Blocked**
This redirect failed beocumentation to make surecause the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.

I think you need to add some more infos in the documentation...

**Comment by shabnam611** [comment]
Hello @Anticosti,

Please email us at support@wedevs.com. In order to fix the issue, we need to check the settings of your FaceBook app. 

Also, we will update our documentation for social login with WPUF as well. 

Thank you!
