### ISSUE TITLE
POST wp-admin/admin-ajax.php 500 (Internal Server Error)

### ISSUE THREAD

**Issue by hirushacooray** [weDevsOfficial/wp-user-frontend#696]
I always get POST wp-admin/admin-ajax.php 500 (Internal Server Error) when try to update the user profile via front-end. I disabled all plugins, switched to default theme, increased memory limit and deleted the htaccess file but none of them were worked. I contacted the hosting as well. Is anyone experienced this issue?

Thanks

**Comment by shabnam611** [comment]
Hello @hirushacooray,

Thank you for your issue. 

Usually, the internal server error is server or site-specific. Therefore please email us at support@wedevs.com so that we can help you to get it fixed. 

Regards,
