### ISSUE TITLE
Missing string for "Select Country" (in many files)

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#697]
These are missing the "<?php _e  .. " part
wp-user-frontend-pro/includes/fields/class-field-country.php | 58
wp-user-frontend-pro/includes/fields/class-field-address.php | 106
wp-user-frontend-pro/includes/render-form.php | 560
wp-user-frontend-pro/includes/render-form.php | 745
wp-user-frontend-pro/includes/form-element.php | 993
wp-user-frontend-pro/includes/form-element.php | 1339

**Comment by Anticosti** [comment]
While at it, if tou could also verify for Strings: "State" and "Zip Code".
These two are missing and should also be located in the same files, around "Select Country".

Thank you.

**Comment by shabnam611** [comment]
Hello @Anticosti,

Thank you for writing to us. We are checking. 

Thanks again!

**Comment by mahbubme** [comment]
@Anticosti 

Fixed in the pro version.

Thanks

**Comment by Anticosti** [comment]
Thank you @mahbubme
Much appreciated.
