### ISSUE TITLE
Missing string for "Post Limit Exceeded for your purchased subscription pack."

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#698]
Just noticed this missing string for translation, in these two files:

wp-content/plugins/wp-user-frontend/includes/class-form.php | 235
wp-content/plugins/wp-user-frontend/class/frontend-form-post.php | 235

Thanks

**Comment by shabnam611** [comment]
Hello @Anticosti,

Thanks, we will check and will work on this.

Regards,

**Comment by Anticosti** [comment]
Thank you @mahbubme, @shabnam611
Much appreciated.
