### ISSUE TITLE
Incompatibility with ACF date/time & WPUF date/time

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#700]
ACF date/time field doesn't work with WPUF date/time (always exist the date of the current day in the post's backend custom field). It's still not working if I set-up the ACF format as like WPUF default format or vice-versa.

**Comment by Girdharcoder** [comment]
WPUF conflict with ACF .  kindly suggest

**Comment by mahbubme** [comment]
@mmarj, Use the following date format in the WPUF date field. 

**yy/mm/dd**

It should work now. 

Thanks

**Comment by mahbubme** [comment]
@Girdharcoder, 

What is the issue? Please let us know the details. We will be happy to help you.

Thanks

**Comment by Girdharcoder** [comment]
If i select custom post type. Taxnomy not showing in post form

**Comment by mahbubme** [comment]
Hello @Girdharcoder 

Please contact our [support](https://wedevs.com/contact) team with your site details. We will be happy to help you.

Thanks
