### ISSUE TITLE
Missing String for "You may also connect with"

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#702]
When you activate the "Social Login" Module 
This string is missing for translation: "You may also connect with"

Thanks

**Comment by shabnam611** [comment]
Hello @Anticosti,

Social login is a paid package feature of WPUF. So we are keeping the issue and fix logged in a separate platform. 

We have found the issue and will be fixed on our next official release of the plugin. 

Thank you for finding the issue.

**Comment by Anticosti** [comment]
Thanks and welcome!
