### ISSUE TITLE
Post Owner problem

### ISSUE THREAD

**Issue by Dextrolain** [weDevsOfficial/wp-user-frontend#703]
Hi.
For some reason posts are not assigned to selected user. They aren’t assigned to any user actually.
“Guest Post” is enabled. “Require Name” is disabled.

Am I missing something required for this option to work?

**Comment by thebengalboy** [comment]
Hello @Dextrolain 

If 'required name and email' is not enabled on the post form, then the post will be assigned to the default post owner. You need to have defined the **default post owner** from the settings. Reference screenshot: https://prnt.sc/onkbvu

I hope this will help :)

Thanks

**Comment by Dextrolain** [comment]
Thanks for the response.

The Default Owner is set. It doesn't matter what role the default owner has (subscriber, author, admin etc). 
I just get a blank space in the "Author" field.

I thought it could be some conflict with other plugins/themes, so I tested this on a fresh Wordpress install - same problem.
Screenshot: http://prnt.sc/onkxk0

**Comment by thebengalboy** [comment]
Hello @Dextrolain 

That can be an issue with the plugin. Please allow us some time, we'll investigate and fix it as early as possible.

Thanks

**Comment by mahbubme** [comment]
Hello @Dextrolain,

I have fixed the issue. To get the fix, [download](https://github.com/weDevsOfficial/wp-user-frontend/archive/develop.zip) the develop version and install it on your site. 

We will include the fix in the next update of WPUF plugin.

Thanks

**Comment by Dextrolain** [comment]
Thank you @mahbubme, @thebengalboy 
Everything works perfectly.
Thanks for all the work!
