### ISSUE TITLE
Google reCaptcha is not working properly with WPUF post form

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#705]
By using the WPUF ReCaptcha field it's not properly working during inserting the forms data!
Mainly with reCaptcha V2 if I didn't check the captcha, it's still submitting the data.

[Reference video](https://drive.google.com/open?id=1OBsJw2qPf6eUKkYpzrEmKxQnkaFkcqFp).

**Comment by Fendt1** [comment]
So, is there a solution? I have the same bug?
