### ISSUE TITLE
time-out error

### ISSUE THREAD

**Issue by gigsoup** [weDevsOfficial/wp-user-frontend#706]
Good morning. Downloaded the free version of WP User Frontend to test. Great product and really looking forward to purchasing the full package. However, I've noticed an issue and wondered if you've seen this before (or if this is specific to free version). Basically when the plugin is activated my whole site slows down to the point where 504 Gateway Timeout errors occur. If I deactivate the plugin then the site works perfectly again. 

The errors tend to occur more in the Wordpress backup end (dashboard) but the slowness is felt on the frontend as well. Any ideas as really want to use this product as it offers so much more than AccessPress

**Comment by mahbubme** [comment]
Hi @gigsoup 

There might be a theme or plugin conflict. Can you please check? If you are still unable to sort out the issue then please contact our [support](https://wedevs.com/contact) team with your site details. We will be happy to help you.

Thanks
