### ISSUE TITLE
Post is not created

### ISSUE THREAD

**Issue by deepanchakravarthi** [weDevsOfficial/wp-user-frontend#707]
I used the following shortcode to display the same form in two pages. 

[wpuf_form id="22"]

I didn't get response in post form submission. Kindly please assist me.

EDIT: I got an error in console. 
ReferenceError: WP_User_Frontend is not defined

Thank you!

**Comment by mahbubme** [comment]
Hi @deepanchakravarthi,

Please contact our [support](https://wedevs.com/contact) team with your site details. We will be happy to help you.

Thanks
