### ISSUE TITLE
Payment column on the posts table configuration from the backend is not respecting the frontend dashboard appearance.

### ISSUE THREAD

**Issue by emazharulislam** [weDevsOfficial/wp-user-frontend#708]
Although from the backend ( User Frontend->Settings->Dashboard ) this ( Enable if you want show payment column on posts table ) checkbox is marked as unchecked, still the payment column is showing on the frontend dashboard.

**Comment by mahbubme** [comment]
Hi @emazharulislam 

The global payment column option is for account page posts table not for [wpuf_dashboard] page. If you don't want to display payment column in dashboard page then use this sample shortcode [wpuf_dashboard payment_column="off"].

Thanks for your understanding
