### ISSUE TITLE
Guest post verification does not work

### ISSUE THREAD

**Issue by forkless** [weDevsOfficial/wp-user-frontend#710]
I am not able to get the free plugin to send a validation email on submit when the form is configured for guest posting. I have the following set up:

- A form with the Name and Email fields in them with identical labels as shown in the Detail settings
- Guest posting is enabled
- User details are disabled
- Guest validation is enabled

No mails will be sent, when I enable the user details it will create two additional form fields and when I fill out those the validation mail will get sent out and I receive it, However I do not want to register guests on my site. I just want the validation mail.

I am running on a Debian box with Apache2 configured running PHP7.3 and WP5.2.2

Ps. I found some information about updating the theme to support a trigger, which I have done but doesn't seem to make any difference. 

Also how does the guest email template know which form labels to use on my form if I use arbitrary label names?

**Comment by mahbubme** [comment]
Hello @forkless,

When user verification is required with guest posting, WPUF creates a new user if user not exist with the same email. This is useful for the user who wants to post again & don't want to verify his email multiple times. The user then understand that there is an account and verification is not required. Just login and submit the post. 

Thanks for your understanding.
