### ISSUE TITLE
Compound Taxes

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#711]
Would be really awesome if you could make WP User Frontend Pro to support *compound* taxes.

Example:
Amount: 100 $
Tax 1 name:  (5%): 5 $
Tax 2 name: (9,975%): 9,98 $
Total Taxes: 14,98 $
Total: 114,98 $

**Comment by mahbubme** [comment]
Hello @Anticosti 

While there’s currently no way to do that, we appreciate you taking the time to let us know what you’re looking for — most of the improvements we make come from ideas and suggestions like yours, so we may consider compound taxes in future.

Thanks
