### ISSUE TITLE
Integretion with Oxygen Builder (conditions)  #51861

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#712]
Greetings, Per issue #51861 at WeDevs
Per Mushrit demand: "I have discussed this with our developer and they will be able to access the code and check if you can send this in GitHub. Our developers can check the code from there."

So here is the code:
`<?php

global $post;

$args = array(
	'post_type' => 'memberpressproduct',
	'posts_per_page' => -1,
	'orderby' => 'title',
	'order' => 'ASC'
);

$myposts = get_posts( $args );

$post_titles = array();

foreach ( $myposts as $post ) {
	setup_postdata( $post );

	$post_titles[] = get_the_title();	
}

wp_reset_postdata();

if ( function_exists( 'oxygen_vsb_register_condition' ) ) {

	oxygen_vsb_register_condition(
		// Condition Name
		'Has Access To MemberPress Membership',

		// Values: The array of pre-set values the user can choose from.
		// Set the custom key's value to true to allow users to input custom values.
		array( 
			'options' => $post_titles,
			'custom' => false
		),

		// Operators
		array( '==', '!==' ),
		
		// Callback Function: Name of function that will be used to handle the condition
		'wpdd_memberpress_membership_callback',

		// Condition Category: Default ones are Archive, Author, Other, Post, User
		'User'
	);

}

/**
 * Callback function to handle the condition.
 * @param  mixed 	$value    	Input value - in this case, the name of membership.
 * @param  string 	$operator 	Comparison operator selected by the user.
 *
 * @return boolean 				true or false.
 */
function wpdd_memberpress_membership_callback( $value, $operator ) {

	$memberpressproduct_object = get_page_by_title( $value, OBJECT, 'memberpressproduct' );

	$id = $memberpressproduct_object->ID;

	if ( $operator == "==" ) {
		// return ( current_user_can( 'memberpress_product_authorized_' . $id . '' ) ) ? true : false;
		return ( current_user_can( 'mepr-active', 'membership:' . $id . '' ) ) ? true : false;
	} else {
		// return ( current_user_can( 'memberpress_product_authorized_' . $id . '' ) ) ? false : true;
		return ( current_user_can( 'mepr-active', 'membership:' . $id . '' ) ) ? false : true;
	}

}`

Thank you in advance!

**Comment by Anticosti** [comment]
[code.zip](https://github.com/weDevsOfficial/wp-user-frontend/files/3520852/code.zip)

**Comment by mahbubme** [comment]
Hello @Anticosti 

Can you discuss the use case? I mean what do you want to do by WPUF with Oxygen Builder?

Thanks

**Comment by Anticosti** [comment]
Hello Mahbubme,
The idea is to be able to add my WPUF subscriptions (AKA: memberships) to my Oxygen Site Builder framework, as here:
https://wpdevdesign.com/condition-has-access-to-memberpress-membership/

The idea is:
to register a custom condition using which elements can be output conditionally based on whether the user has purchased/subscribed to a pack using WPUF Pro in Oxygen.

See screenshots at:
https://wpdevdesign.com/condition-has-access-to-memberpress-membership/

Thank you Mahbubme !

**Comment by mahbubme** [comment]
Hello @Anticosti 

User who purchased subscription pack has **_wpuf_subscription_pack** meta. The meta returns all the details of purchased subscription pack. So, you can use to check conditionally whether a user assigned to WPUF subscription pack or not. 

reference: 

`$user_pack_meta = '_wpuf_subscription_pack';
 $pack_details   = get_user_meta( $user_id, $user_pack_meta, true);`

Thanks

**Comment by Anticosti** [comment]
**Thank you so much @mahbubme** for your great collaboration on this.
This is **sincerly very much appreciated**.
Your help has been rapidly adapted here:
to [Oxygen Builder](https://oxygenbuilder.com/) through this tutorial authored by **Sridhar Katakam**,
[https://wpdevdesign.com/condition-wp-user-frontend-pro-subscription/](https://wpdevdesign.com/condition-wp-user-frontend-pro-subscription/)
