### ISSUE TITLE
Subscription-page stuck after expiration of subscription

### ISSUE THREAD

**Issue by wish86** [weDevsOfficial/wp-user-frontend#713]
Hi,

I'm new to this addon and I'm testing left and right.
When letting a subscription expire once you go tot he account page and want to see the active subscriptions the screen goes on loading. If I view the source I see the following:
            
Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /customers/b/7/7/website/httpd.www/wp-content/plugins/wp-user-frontend/templates/dashboard/subscription.php:14
Stack trace:
#0 /customers/b/7/7/website/httpd.www/wp-content/plugins/wp-user-frontend/wpuf-functions.php(1324): include()
#1 /customers/b/7/7/website/httpd.www/wp-content/plugins/wp-user-frontend/class/frontend-account.php(259): wpuf_load_template('dashboard/subsc...', Array)
#2 /customers/b/7/7/website/httpd.www/wp-includes/class-wp-hook.php(286): WPUF_Frontend_Account->subscription_section(Array, Array)
#3 /customers/b/7/7/website/httpd.www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 /customers/b/7/7/website/httpd.www/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#5 /customers/b/7/7/website/httpd.www/wp-content/plugins/wp-user-frontend/templates/account.php(33): do_action('wpuf_account_co...', Array, Array)
# in /customers/b/7/7/website/httpd.www/wp-content/plugins/wp-user-frontend/templates/dashboard/subscription.php on line 14

is this supposed to be the case?
is there a solution? is this an issue from my end?

**Comment by mahbubme** [comment]
Hello @wish86 

There might be a conflict issue. Can you please create a support ticket [here](https://wedevs.com/contact) with your site details? We will be happy to help you.

Thanks
