### ISSUE TITLE
Login Out generates 2 extra "You are now logged out." instead of just 1

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#715]
Just noticed that when a user log out it generates 2 extra "You are now logged out." instead of just 1
`<div class="wpuf-message">You are now logged out.</div><div class="wpuf-message">You are now logged out.</div><div class="wpuf-message">You are now logged out.</div>`

Thanks!

**Comment by Anticosti** [comment]
I had to intercept these extras with:
`div.wpuf-message:nth-child(1),
div.wpuf-message:nth-child(2){
	display:none;
	visibility:hidden;
}`

**Comment by mahbubme** [comment]
Hello @Anticosti 

There might be a conflict with another plugin or the theme you are using. Can you please check that? If there is not conflict then contact our [support](https://wedevs.com/contact) team with your site details. 

Thanks
