### ISSUE TITLE
Missing string for "Post Limit Exceeded for your purchased subscription pack."

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#716]
Missing string for "Post Limit Exceeded for your purchased subscription pack."
Thank you for fixing this.

**Comment by shabnam611** [comment]
Hello @Anticosti,

You have already mentioned this once here. We have replied on the previous issue opened on the same topic. 

Thank you!

**Comment by Anticosti** [comment]
Sorry about the duplicate.
Thanks.
