### ISSUE TITLE
Unable to duplicate field in Post Form editor

### ISSUE THREAD

**Issue by joegrantstn** [weDevsOfficial/wp-user-frontend#718]
When I try to duplicate a field within the Post Form editor...
![](https://i.imgur.com/KK6ylnY.png)

It warns me that I already have this field in the form...
![](https://i.imgur.com/MwW0lN9.png)

But the whole point of a Duplicate button is to make another copy of the field, right?

**Comment by mahbubme** [comment]
Hello @joegrantstn 

You can duplicate the custom fields & other fields. Post fields & Taxonomy fields for single use only, so it's not possible to duplicate them. 

Thanks
