### ISSUE TITLE
Urgent: Set Invoice Mail Body - Can't add line breaks to message

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#721]
If you go to:
wp-admin/admin.php?page=wpuf-settings&settings
Invoices Set Invoice Mail Body
You can't add line breaks to your custom message.
As suggested here:
https://stackoverflow.com/questions/16063312/new-lines-r-n-are-not-working-in-email-body
I tried adding: `<br> <br /> </BR> \r\n`
No success. Text doesn't get wrap.

**Comment by mahbubme** [comment]
Hi @Anticosti 

This issue has been fixed in the pro version. Please wait for the next release.

Thanks
