### ISSUE TITLE
Missing string to translate: "You must be logged in to view the content."

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#722]
Missing string to translate: "You must be logged in to view the content."

**Comment by mahbubme** [comment]
Hello @Anticosti 

The string exists in the WPUF free & pro pot file. So, please make sure that you translated the string in both plugins.

Thanks

**Comment by Anticosti** [comment]
Dear mahbubme, I sure don't want to argue with you, but...
Using **Loco Translate** 
01. In: Plugins  WP User Frontend Pro - personal  **wpuf-pro-fr_FR.po** 
Loco Translate can't find any string
02. In: Plugins  WP User Frontend  **wp-user-frontend-fr_FR.po** 
Loco Translate can't find this string. It only finds:
You must be logged in to **preview this form**.
which is not:
You must be logged in to **view the content**.

Thanks!

**Comment by mahbubme** [comment]
No worries :) can you create a support ticket here with your site details? Our support team will help you to solve this issue.

Thanks
