### ISSUE TITLE
Billing Address issue

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#723]
Hello,
Just realized this urgent issue to solve:

**Scenario 01:**
**01.** A new customer buys a Pack by **PayPal**;
**02.** His address he entered at checkout on my site is **not kept** at:
account/?section=billing-address  (**Bad!**)
**03.** His address he entered at checkout on my site is **not kept** in the Invoice PDF, under the "BILLING TO" column.  (**Bad!**)

**Scenario 02:**
**01.** A new customer buys a Pack by **Bank Payment**;
**02.** His address he entered at checkout on my site is **not kept** at:
account/?section=billing-address  (**Bad!**)
**03.** His address he entered at checkout on my site is **kept** in the Invoice PDF, under the "BILLING TO" column.  (**Good!**)

Thank you for your attention!

**Comment by mahbubme** [comment]
Hi @Anticosti 

I am looking into this issue. 

Thanks

**Comment by Anticosti** [comment]
Thank you for your attention on this issue.
Much appreciated.

**Comment by mahbubme** [comment]
Hello @Anticosti 

Fixed in pro version. Thanks for figuring out the issue.
