### ISSUE TITLE
Confusing for the customer : Invoice email receipt is sent twice

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#724]
This behavior is confusing for the customer : Invoice email receipt is **sent twice** (same exact date stamp)
Customer wonders if he has been charged twice?
In ref. to:
wp-admin/admin.php?page=wpuf-settings
**Set Invoice Mail Body**

Thank you for your attention to this issue.

**Comment by mahbubme** [comment]
Hi @Anticosti 

It should not send invoice email twice. There might be another issue. Can you please check theme/plugin conflict?

Let me know the updates.

Thanks

**Comment by Anticosti** [comment]
testing on a staging environnement... 
I kept only these plugins:

1. Email Tracker	
2. Oxygen	
3. Pods - Custom Content Types and Fields
4. Responsive Menu
5. Responsive Pricing Table PRO
6. Shortcodes Ultimate
7. Tabs Pro wpshopmart
8. The Hack Repair Guy's Plugin Archiver
9. WooSidebars
10. WP Multilang
11. WP User Frontend
12. WP User Frontend Pro - personal

I made a test purchase. Did not modified my PayPal returning page "after purchase page".
So this took me back to my main site with double emails for these two emails:
- Invoice (PDF attached)
- Payment received

**Comment by mahbubme** [comment]
Hello @Anticosti 

Yes, these two emails are not the same. One for payment received notification to the user and another for invoice. We don't attach invoice with payment received notification.

Thanks

**Comment by Anticosti** [comment]
Hi again mahbubme,
Maybe you will better understand with a screenshot...?
[Screenshot](https://www.dropbox.com/s/zr7dsbjakejhxbi/S%C3%A9lection_288.png?dl=0)

**Comment by mahbubme** [comment]
Hello @Anticosti 

Got it. It can be a site specific issue. Please contact our [support](https://wedevs.com/contact)

Thanks

**Comment by mahbubme** [comment]
Hi @Anticosti 

I have fixed the issue. Please wait for the next release.

Thanks

**Comment by Anticosti** [comment]
Good news!
Any idea when next release will be available...?

Kindly,

**Comment by mahbubme** [comment]
I will release v3.1.11 today :)

Thanks
