### ISSUE TITLE
Susbcription Missing in Admin after Updating

### ISSUE THREAD

**Issue by LoveBexa** [weDevsOfficial/wp-user-frontend#727]
After updating the WP user plugin the Subscription option in the admin panel has now disappeared. How do i access it?

**Comment by mahbubme** [comment]
Hello @LoveBexa 

Can you please [contact](https://wedevs.com/contact) our support team with your site details? We need to check your site. 

Thanks

**Comment by LoveBexa** [comment]
It's okay now :) I deactivate and reactivated it @mahbubme

**Comment by mahbubme** [comment]
Thank you for the updates.
