### ISSUE TITLE
Please offer an option to let a new term entered by a frontend user, being auto-activated

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#729]
Greetings,
Please offer an option to let a new term entered by a frontend user, being auto-activated, without having to go each time, in Subscription / Taxonomy Restriction.

PHP Code that works:
`Your City does not appear? 
Please add it here:

// Check to see if correct form is being submitted, if so continue to process
if( 'POST' == $_SERVER['REQUEST_METHOD'] && !empty( $_POST['action'] ) &&  $_POST['action'] == "new_term") {

    // Check to see if input field for new term is set 
    if (isset ($_POST['term'])) {

        // If set, stores user input in variable
        $new_term =  $_POST['term'];

        // Function to handle inserting of new term into taxonomy
        wp_insert_term(

          // The term (user input)
          $new_term,

          // The city taxonomy
          'city'        
        );
    } else { 
        // Else throw an error message
        echo 'Please enter a city name!';     
    }
}

Followed by the Form:
```
<form id="insert_term" name="insert_term" method="post" action=""> 
    <input type="text" value="" name="term" id="term" /> 
    <input type="submit" value="Add City" id="submit" name="submit" />
    <input type="hidden" name="action" value="new_term" />
</form>
```

Thank you!

**Comment by Anticosti** [comment]
Followed by the Form:
<form id="insert_term" name="insert_term" method="post" action=""> 
    <input type="text" value="" name="term" id="term" /> 
    <input type="submit" value="Add City" id="submit" name="submit" />
    <input type="hidden" name="action" value="new_term" />
</form>

**Comment by itowhid06** [comment]
Hello @Anticosti , 

I do not think it will be wise to let users add taxonomy terms. If you allow them to enter their own terms, definitely there will be duplicates and misspelled terms all over the place.  Soon it will be a mess and unmanageable. Hope you understand the problem with adding this feature.

Regards

**Comment by Anticosti** [comment]
@itowhid06 Thank you for your input.That makes sense. I'll forget a
