### ISSUE TITLE
Numeric options are always arranged in ascending order in the radio field

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#731]
Whatever the sequence is, the numeric options of the form automatically rearrange themselves in ascending order depending on the value

Video: https://www.loom.com/share/fe911f8925ba4a01b2eb3174b84b4c23

**Comment by karltdev** [comment]
This also affects the final sequence after hitting save. It affects the frontend output sequence as a result.

**Comment by zamandevs** [comment]
We are using JS object literal for options data i.e radio, checkbox, etc. So currently it is not possible to tweak.
If the user needs to use a numeric label he can add it by prefix or append some character with it & can set a different value for that label.
