### ISSUE TITLE
Custom post type

### ISSUE THREAD

**Issue by jessemarco** [weDevsOfficial/wp-user-frontend#732]
Categories, Tags are not submitted to custom post type. Title, description, feature image is working fine.

**Comment by shabnam611** [comment]
Hello @jessemarco,

Please email us at support@wedevs.com so that we can get this resolved for you :) 

Thanks for your understanding!

**Comment by jessemarco** [comment]
Hello @shabnam611,
Thank you for support. 

I sent e-mail, they replied that it is supported only WP CORE TAGS, CATEGORIES, not custom TAXONOMIES registered with Custom Post Types.

**Comment by shabnam611** [comment]
Hello @jessemarco,

Can you please share with me the email address which you used to contact our support team?

Regards,
