### ISSUE TITLE
Subscription package issue

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#735]
When a user purchases a subscription package during registration, the package is assigned on the backend from WP-admin > User section but it remains unavailable for the user in the frontend. 

Because the free subscription package is already assigned in the backend, even if user tries to purchase it again, he is stopped by the notice "You already have activated a free package previously."

video: https://www.loom.com/share/937c023c0ba347168556856ebd2e5716
video: https://www.loom.com/share/d35711948563480db6bef40db9f58a67

**Comment by itowhid06** [comment]
Closed via https://github.com/weDevsOfficial/wp-user-frontend/commit/b3ec836ba61243949cbe040ed6aec772c634f1c5
