### ISSUE TITLE
Use default Theme's CSS for [wpuf-login] shortcode.

### ISSUE THREAD

**Issue by saiftheboss7** [weDevsOfficial/wp-user-frontend#736]
I tried to make a login form using the Divi theme. Found out the textbox, buttons are not inheriting from the theme. It breaks the design.

https://i.imgur.com/KQEQuLR.png

**Comment by rokibulislam** [comment]
i have tried several theme like storefront, Jupiter theme default style work properly, i think its conflict with divi theme
