### ISSUE TITLE
How to remove plugin added post edit screen meta boxs

### ISSUE THREAD

**Issue by iwillhappy1314** [weDevsOfficial/WP-User-Frontend#74]
I use other metabox builder plugin builded a metabox to show the user submition, how to remove plugin added post edit screen meta boxs?

may be add an option allow to disable the metaboxs?

**Comment by sohelamin** [comment]
@iwillhappy1314 For now there is no way to get rid the meta boxes generated by "WP User Frontend" Plugin.
If you add the post/form without the meta then it will not be shown there.
