### ISSUE TITLE
WPUF showing error message with WP Version-5.3

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#745]
**1. Bug Description:**
In the latest WordPress version 5.3, if you are going to add *a new post/pages* from the wp-admin side by keeping WPUF plugin activated it will generate an error "strlen() expects parameter 1 to be string, object given in .....wp-includes/formatting on line 3380"

 **2. How to Reproduce:**
Kept activated the WPUF plugin then try to add any posts from *Posts/Page -> Add New*. Then you will get the above error message on your header area on page load.

**3. Expected Behavior:**
It should appear the error warning message on the header. Also, it seems for the error it's slowing down the page alongside the overall site so performance should be enhanced.

**4. Additional input (Screenshot/Video):**
Please note that if you turn off the WP_DEBUG_DISPLAY or WP_DEBUG then it will not show you the error message. Screenshot of the error message http://prntscr.com/q69veo

**Comment by shabnam611** [comment]
This issue has been fixed already

**Comment by mmarj** [comment]
Acknowledged with thanks.
Commit link- 
https://github.com/weDevsOfficial/wp-user-frontend/commit/15717355874c01d492c372822533d55c9870adb9
