### ISSUE TITLE
Password reset link incomplete

### ISSUE THREAD

**Issue by reqdev** [weDevsOfficial/wp-user-frontend#746]
If a user resets their password the email they receive contains an incomplete reset link. For example it says this:

To reset your password, visit the following address: ?action=rp&key=Ewn6lHR2wmsbVmIe4F7Y&login=adminusername

but it should be this:

https://www.mywebsite.org/wp-login.php?action=rp&key=KYsmtXruCiEKkQobnMLZ&login=adminusername

**Comment by itowhid06** [comment]
Hello @reqdev,

I was unable to reproduce the issue in my end. If you are still facing the issue, can you please open a ticket [Here](https://wedevs.com/contact).

**Comment by reqdev** [comment]
Hi, I had to disable the WP User Frontend plugin in order to make the site operational for password resets. Which is why you were unable to recreate the issue. If you’re able to test it, let me know and I’ll temporarily reactivate it so you can see the issue. 

Josh

---------------------------------------------
Requested Development, LLC
josh@requesteddevelopment.com
608-556-4471
