### ISSUE TITLE
Post Content Bug

### ISSUE THREAD

**Issue by ezik009** [weDevsOfficial/wp-user-frontend#749]
![Capture](https://user-images.githubusercontent.com/29943370/70605308-3d915300-1c35-11ea-8fe5-1abec791098c.PNG)

**Comment by shabnam611** [comment]
Hello @ezik009,

Can you please provide us some description/video to reproduce the issue so that we can help you out. 

Regards,

**Comment by ezik009** [comment]
I will, can I send it here?

**Comment by ezik009** [comment]
Ok so if I continue on typing without hitting enter or spacebar in the Post Content form box this happens. It should automatically like create a new line to make a paragraph right?

**Comment by ediamin** [comment]
Hi @ezik009 We need more details to solve your issue. Please post a full screenshot of your site. If possible please create a ticket on our website https://wedevs.com/account/tickets/. We may need a testing credential for your site. Thank you very much.
