### ISSUE TITLE
Field «Custom HTML» & multiple selection of «Checkbox»

### ISSUE THREAD

**Issue by maksimtts** [weDevsOfficial/wp-user-frontend#750]
Hey there! I’ve faced with the following issues using WP User Frontend and looking for help:

1. There are no errors when I create a single form with a field «Checkbox» and paste this form on a page. But with the multiple selection of «Checkbox» items it is the completely different story. In a newly created post «Checkbox» items are displayed in a single line with a separator «|». Here is the example: Checkbox: Option | Option-2 | Option-3

2. When I am creating a new form with a field «Custom HTML» and trying to paste this form to the page, it’s displayed correctly, but it does not reflected in a newly created post.

WP User Frontend 3.1.14
WordPress 5.3.1

https://savepice.ru/full/2019/12/19/8b3a607401a1cb212789a68c7a4113c8-full.jpg.html
https://savepice.ru/full/2019/12/19/620242f82f6855abd09a0d40f8a91b29-full.jpg.html
https://savepice.ru/full/2019/12/19/977d1481483adb8e79870f922f6842f2-full.jpg.html

**Comment by itowhid06** [comment]
Hello @maksimtts, 

1. This is how the multiple checkbox data is being displayed right now.
2. Custom HTML field serves the purpose of displaying some custom HTML or rendering a shortcode in a form, not take an input from user.

I am closing this issue for now. Feel free to reopen it if you have any further query. Thanks.
