### ISSUE TITLE
The website URL field is not accepting anything after the main domain/URL.

### ISSUE THREAD

**Issue by emazharulislam** [weDevsOfficial/wp-user-frontend#751]
**Description:** At this moment WP User Frontend Website URL field works in a way that the user will only be able to submit www.example.com but users will not be able to submit www.example.com/ or www.example.com/someting.

**Steps to Reproduce:** Add a website URL field in post form and try to submit URL like www.youtube.com/ or www.youtube.com/wedevs

**Expected behavior:** The website URL field should accept all kinds of valid URLs.

**Video:** https://drive.google.com/file/d/14yjzW1n5xyTAqero_uHfuOZ-vV5yWaAu/view

**Comment by bibliothekarin** [comment]
I have the same problems. The URL field is an important feature for my website.

**Comment by fracii** [comment]
I have same issue maby after update to new version of plugin.

**Comment by shabnam611** [comment]
Hello,

We have recently found this problem and have fixed it already. The fix will be available in our next official release of WPUF.

Thank you!
