### ISSUE TITLE
Campi personalizzati non visibili sul post creato

### ISSUE THREAD

**Issue by thor262** [weDevsOfficial/wp-user-frontend#758]
I campi personalizzati non sono visibili sul post creato.
Le impostazioni di WP User Frontend non sono visibili.
Ho già disattivato i plugin per verificare se si tratta di un conflitto con altro plugin ma niente.

**Comment by itowhid06** [comment]
Hello @thor262 , From google translate what I can gather is:

> Custom fields are not visible on the created post.
> WP User Frontend settings are not visible.
> I have already disabled the plugins to check if it is a conflict with another plugin but nothing.

You should turn on WP User Frontend Settings > Frontend posting > Custom Fields in post. Then the custom fields should be displayed on post content area.
