### ISSUE TITLE
Number of rows and columns is not working

### ISSUE THREAD

**Issue by swamiv1984** [weDevsOfficial/wp-user-frontend#759]
In post forms, in text area under Advanced options, number of rows and number of columns is set but in the front end it is not working. I can enter text as many rows as possible. Word Restriction is also not properly working. When I set to 15 words, it only works in the first row. But I can enter one word per row with out any restriction. What is the use of Row, Column and Word Restrictions?. No clear documentation in WPUF website. Also, in the number field how can restrict numbers to 10 digits (ex: mobile number - 9876543210). Currently, I can enter mobile number 9876543210000000....and so on.

**Comment by itowhid06** [comment]
Hello @swamiv1984, I was unable to reproduce the row and column issue of textarea field you described. It is working properly properly at my end. If you are still facing the issue, kindly open a ticket [Here](https://wedevs.com/contact). Also currently there is no option to restict the numbers.
