### ISSUE TITLE
Notice: Undefined index: REMOTE_ADDR in wpuf-functions.php on line 1218

### ISSUE THREAD

**Issue by naeh** [weDevsOfficial/WP-User-Frontend#76]
hello,

this notice is shown when executing scripts in CLI.

could you just add
`if(!empty($_SERVER['REMOTE_ADDR']) && ...`

Thank you.

**Comment by sohelamin** [comment]
@naeh can you explain why did you need to run the script in CLI?

**Comment by naeh** [comment]
i need to run scripts that loads WP in CLI to import data.

since the WP is bootraped, you license check is fired and it causes that nitice.

**Comment by sohelamin** [comment]
@naeh Fixed at 17b0933
