### ISSUE TITLE
Auto login after registration is not working

### ISSUE THREAD

**Issue by swamiv1984** [weDevsOfficial/wp-user-frontend#761]
I enabled auto login after registration in the wpuf settings. But it is not automatically logged in. It shows the registration successful message. When refresh the page, it again shows the registration form.

**Comment by itowhid06** [comment]
@swamiv1984,

I was unable to reproduce the issue in my end. If you are you still facing the issue, can you please open a ticket [Here](https://wedevs.com/contact)
