### ISSUE TITLE
WPUF Custom HTML field is not saving the data

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#763]
**Describe the bug**: 
If you insert any HTML tag on the field's description box and save the form it will not save the data as HTML formated. It will revert as plain text.

**How to Reproduce**: 
Log in to your site wp-admin panel. Visit user frontend -> post form & edit your form then insert a Custom HTM field on your builder then write something using HTML tag and save the form. Then you will find the field reverted into plain text format instead of the HTML format.
**Note**: The same behavior will also happen for the registration form if you are using a WPUF Pro plugin.

**Expected behavior**: 
The field should save the data as an HTML format.

**Additional input (Screenshot/video)**: 
Please check the video for a clear output result.
[A quick video](https://drive.google.com/file/d/1xBIUBp3crC0kbf3T9K4JNGf-uBPTdf5l/view?usp=sharing)
Feel free to let me know if you may need further information.

Thank you.

**Comment by cmmaung** [comment]
Hi,

Same issue encountered here.

Hi,

I put simple html code on custom html but it’s not working and it revert back to plain text after saved. Sample as below.
<p style=”Color:Red; Font-Weight:Bold;”>Submission</p>
Or
<B>Submission</B>
Or
<H1>Submission</Submission>
None are working.

Thanks.

**Comment by cmmaung** [comment]
Still not fixed yet on the latest update. After saved the form has been cleared. All controls are gone even with the latest updated plugin  v 3.1.16.

**Comment by rokibulislam** [comment]
https://github.com/weDevsOfficial/wp-user-frontend/commit/61a7961352765cfc5b542e9770a73ffa784bf1bf
