### ISSUE TITLE
Upload broken on Windows hosts

### ISSUE THREAD

**Issue by mtuomiko** [weDevsOfficial/wp-user-frontend#766]
**Problem:** Any form image upload will fail on a Windows host with error `Specified file failed upload test.`

Commit d0ecab27dce05e146b1a5dc554bfdca4eda98358 adds sanitization for the uploaded file in `$_FILES` by running it through `wp_unslash`. This however results in a malformed file path in Windows environment as the directory separators are stripped away. Then the `wp_handle_upload` call fails with error message `Specified file failed upload test.` which is shown in the form.

See related issue about running `$_FILES` through `wp_unslash` on https://github.com/WordPress/WordPress-Coding-Standards/issues/1720

**Comment by itowhid06** [comment]
Fixed in https://github.com/weDevsOfficial/wp-user-frontend/commit/c9c0edd1fa3e5b0b075a1fa362965de41690ab15
