### ISSUE TITLE
Photo insert option in content editor and feature image field is not working

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#767]
**Describe the bug**: 
In the latest version, the photo insert option in the content editor is not working perfectly after submitted the post from the frontend.
- If you checked the scenario on the Localhost/Windows(OS) then it will show an error message(Specified file failed upload test). The same error will happen for the feature image field also. [This existing open issue might be helpful to judge the issue more deeply](https://github.com/weDevsOfficial/wp-user-frontend/issues/766).

- If you test this from a live site (Linux Server). Then the photo will be uploaded from the frontend but it will not populate int the backend post area nor in the output published post. 

**How to Reproduce**: 
Log in to your site wp-admin panel. Visit user frontend  - post form then create a field with Post description and published the form. Afterwhich try to upload any image in the content editor it will show you that the image uploaded but once you publish the post on the post preview it will not show you the content's inside image nor in the post backend area. And for the localhost, it will not upload the images.

**Expected behavior**: 
The image inside the content area should be populated on the frontend side.

**Additional input (Screenshot/video)**: 
Please check the screencasts for clarification.

- [Test from the Localhost/Windows(OS)](https://drive.google.com/file/d/1WEj8vPowQHf727CCsqngB3o-0GwM8JL2/view?usp=sharing)
- [Test from the Live Server(Linux)](https://drive.google.com/file/d/1hmekQ-lVqraMqcwrNJQ09PtT5c6du45g/view?usp=sharing)

Feel free to let me know if you may need further information.

Thank you.

**Comment by rokibulislam** [comment]
https://github.com/weDevsOfficial/wp-user-frontend/commit/c9c0edd1fa3e5b0b075a1fa362965de41690ab15
