### ISSUE TITLE
HTML is not wrapping in the post content area after submission

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#768]
**Describe the bug**: 
In the latest version, the HTML tag, break, bold is not rendering after submitting the data from the frontend.

**How to Reproduce**: 
Log in to your site wp-admin panel. Create a post form with the Post description field. Then after publishing the form/page turn over the frontend page and insert text in the post content area with break/new line or bold text then submit the form. Once published in the post you will see the HTML is not wrapping up with the content text.

**Expected behavior**: 
The post content should be rendered with the HTML format.

**Additional input (Screenshot/video)**: 
Please check the screencast for clarification.
[Issue video](https://drive.google.com/file/d/1_9uLi63UcU2Jy68mFtzyqDrexSZXtf5u/view?usp=sharing)

Feel free to let me know if you may need further information.

Thank you.

**Comment by Anticosti** [comment]
Could it just be a CSS issue?
Curious.

**Comment by rokibulislam** [comment]
https://github.com/weDevsOfficial/wp-user-frontend/commit/c9c0edd1fa3e5b0b075a1fa362965de41690ab15
