### ISSUE TITLE
Javascript variable broken in French - wpuf.php:276

### ISSUE THREAD

**Issue by naeh** [weDevsOfficial/WP-User-Frontend#77]
Hello,

this is due to the quote (') in french translation

in wpuf.php at line 276
```javascript
        var error_str_obj = {
            'required' : '<?php _e( 'is required', 'wpuf' ); ?>',
            'mismatch' : '<?php _e( 'does not match', 'wpuf' ); ?>',
            'validation' : '<?php _e( 'is not valid', 'wpuf' ); ?>'
        }
```
"is not valid" translation in french is : "n'est pas valide" which breaks the javascript
you can use double quote (") or use `esc_attr_e` instead of `_e`

Thanks.

**Comment by sohelamin** [comment]
@naeh Will fix it on the next release
