### ISSUE TITLE
Format issue in textarea field

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#770]
Description: If we take a textarea field and post content field in WPUF post form, and enter the data in two paragraphs, the data is not formatted as provided by user.

How to Reproduce the Bug: 

Navigate through WP-admin > Post Form > Add new form > Add post title, post content and text are field. 

Next, insert two paragraphs in both fields. 

Next, if we visit the post from frontend, we will see the paragraphs are formatted properly in the post content field but not in the text area field. 

If we visit the post in backend, we can see the same issues. 

Current Behavior: Both post content and textarea field shows the issue in frontend and in backend. 

Correct Behavior: In 3.1.14 the post content field showed correct behavior in frontend and backend. But textarea showed the same issue. 

Video: https://www.loom.com/share/95801d96b371457289828e685ad73e3e

**Comment by rokibulislam** [comment]
solve
