### ISSUE TITLE
Terms & Conditions fields is not working

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#773]
**Describe the bug**: 
If you insert any T & C fields on the WPUF form builder then insert any link by replacing the # then it turning all the existing forms disappears. I tested this with the latest version of WPUF Free (3.1.16)

**How to Reproduce**: 
Log in to your site wp-admin panel. Visit user frontend -> post form & edit your form then insert a Terms & Condition field on your builder then replace the # with any URL & save. Then you will find a builder disappearing all the existing fields along with the Terms & Condition field.
**Note**: The same behavior will also happen for the registration form if you are using a WPUF Pro plugin.

**Expected behavior**: 
The field should save the data with the URL and other fields should be as it is.

**Additional input (Screenshot/video)**: 
Please check the video for a clear output result.
[Screencast](https://drive.google.com/file/d/1EvKwwX_gfQVzpIrxC18sdyiIfKs0o5PV/view?usp=sharing)
Feel free to let me know if you may need further information.

Thank you.

**Comment by rokibulislam** [comment]
https://github.com/weDevsOfficial/wp-user-frontend/commit/61a7961352765cfc5b542e9770a73ffa784bf1bf

**Comment by rokibulislam** [comment]
solve
