### ISSUE TITLE
Post Forms - Custom HTML field with image deletes entire form

### ISSUE THREAD

**Issue by traviswarrenhiggins** [weDevsOfficial/wp-user-frontend#775]
1) Custom HTML with image deletes form (similar to Terms and Conditions)

**Describe the bug:**
If you insert any custom image in the custom HTML field on the WPUF form builder - all the existing forms disappears. 

**How to Reproduce:**
Log in to your site wp-admin panel. Visit user frontend -> post form & edit your form then insert a custom HTML field on your builder then add in below code (or similar):

```
<div class="parent">
    <img src="https://www.supercastcompany.com/wp-content/uploads/2019/12/GalleryWall_w577.jpg" alt="Gallery1"></div>
```

Then you will find a builder disappearing all the existing fields in the Form.

**Expected behavior:**

The field should save the data with the custom HTML and other fields should be as it is.

Additional input (Screenshot/video): https://drive.google.com/file/d/1kD-UbZrYjrPe28iEVfF_SEhf91un63qF/view?usp=sharing

**Comment by shabnam611** [comment]
Hello @traviswarrenhiggins,

I am so sorry for the inconvenience. Yes, I have found the issue from our end and surely we will take the necessary steps to fix it. 

Please allow us a little more time.

Regards,

**Comment by rokibulislam** [comment]
https://github.com/weDevsOfficial/wp-user-frontend/commit/61a7961352765cfc5b542e9770a73ffa784bf1bf
solve

**Comment by radukam** [comment]
Hello. In the meanwhile, try to replace double quotes with single quotes. This could work for a while.
