### ISSUE TITLE
URGENT: Forms resetting to scratch and critical errors

### ISSUE THREAD

**Issue by sarahsampino** [weDevsOfficial/wp-user-frontend#777]
Hi, I am about to launch my site. I went to make a small fix on my registration form. When I went to save, the entire form was deleted and back to scratch. This happened with every single registration and post form and now none of my original forms are there. I cannot figure out what is wrong. I tried activating and deactivating plugins, but as this issue seems to turn on and off every half hour I've checked, I can't conclude anything. The only thing I did was update my PHP?

In addition, WPUF PRO is causing 2 critical errors on my site. This I know is from that specific plugin from deactivating and reactivating. These are the two errors:

"The REST API request failed due to an error."
"Your site could not complete a loopback request"

My site:

http://box5143.temp.domains/~audiobq4/

**Comment by oliosto** [comment]
Got also this critical problem!
Had to recreate all my forms from skratch and to reactivate a previous plugin version  3.1.14

**Comment by ediamin** [comment]
fixed via de80a9c2d4ea981a28930d46e3323fc43f1382d3
