### ISSUE TITLE
Category type "Ajax" is not working with the latest version

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#780]
**Describe the bug**: 
In the latest version(3.1.16), the category type "Ajax" option is not working. It's showing the result as 0 automatically on the frontend side.

**How to Reproduce**: 
Create a Post form with a category field and chose the Category type as Ajax mode form the Advanced Options area then save the form. Make sure you have multiple categories/subcategories for a better investigation. 
Then publish or preview the form and try to choose any Category to form the list you will fetch the 0 on the below of your category list.

**Expected behavior**: 
The output should be the subcategory if there is any associated Subcategory available for the selected Main category Item otherwise it should be as default -select- mode. [You can check this](https://drive.google.com/file/d/1n10y4xJBTIIjsscg1ynY7D6AxDVDoIff/view?usp=sharing) where everything is working fine with the older version 3.1.14

**Additional input (Screenshot/video)**: 
Please [check this screencast](https://drive.google.com/file/d/1g3coKM9097CLyjNVhcmatWVAINc1Elrf/view?usp=sharing) for more clarification.

Thanks

**Comment by rokibulislam** [comment]
solve
