### ISSUE TITLE
Form submission limit exceeded message not showing

### ISSUE THREAD

**Issue by FaraziF** [weDevsOfficial/wp-user-frontend#781]
**Steps**:
- Click individual post form and click settings. 
- Click submission restriction and enable form entry limit and set the number of entries 2. 
- After successfully submitted 2 posts then Form submission limit exceeded the message is showing above the posting form. 
- After that, I change the post type post to page from post settings
**Expected Result** : Form submission limit exceeded will show
**Actual Result**: Form submission limit exceeded is not showing After submit the post Post saved message is showing

**Comment by itowhid06** [comment]
![image](https://user-images.githubusercontent.com/12055657/73331586-75f4fb00-428e-11ea-8677-8fbbc20a2f78.png)
The "Form submission limit exceeded" message seems to be displaying properly.
