### ISSUE TITLE
Php warning

### ISSUE THREAD

**Issue by kiuytt** [weDevsOfficial/wp-user-frontend#787]
Warning: in_array() expects parameter 2 to be array, string given in /var/sites/p/pink.com.ng/public_html/wp-content/plugins/wp-user-frontend/wpuf.php on line 784

**Comment by oliosto** [comment]
Hi, also meeting big issues:
 
1. paypal payment works
2. then I clicked on "return to the website"
3. A critical issue here bellow
4. I receive many repeating automatic emails "payment received"
5. The creation of automatic invoice never worked until today

Warning: Division by zero in /home/u814012316/domains/myteambuilding.eu/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/invoicr.php on line 541

Warning: Division by zero in /home/u814012316/domains/myteambuilding.eu/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/invoicr.php on line 542

Fatal error: Uncaught Exception: FPDF error: Unsupported image type: svg in /home/u814012316/domains/myteambuilding.eu/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/req/fpdf/fpdf.php:271 Stack trace: #0 /home/u814012316/domains/myteambuilding.eu/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/req/fpdf/fpdf.php(884): FPDF->Error('Unsupported ima...') #1 /home/u814012316/domains/myteambuilding.eu/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/invoicr.php(189): FPDF->Image('https://myteamb...', 20, 20, NAN, NAN) #2 /home/u814012316/domains/myteambuilding.eu/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/req/fpdf/fpdf.php(334): invoicr->Header() #3 /home/u814012316/domains/myteambuilding.eu/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/invoicr.php(175): FPDF->AddPage() #4 /home/u814012316/domains/myteambuilding.eu/public_html/wp-content/plugins/wp-user-frontend-pro/includes/class-invoice.php( in /home/u814012316/domains/myteambuilding.eu/public_html/wp-content/plugins/wp-user-frontend-pro/includes/libs/invoicr/req/fpdf/fpdf.php on line 271

**Comment by itowhid06** [comment]
Hello @oliosto,
The library used for for generating an invoice pdf only supports JPEG, PNG and GIF. Please use your logo as one of the aforementioned for file formats instead of svg.

**Comment by itowhid06** [comment]
Hello @oliosto & @kiuytt, If you are still facing the issue, feel free to open a ticket [Here](https://wedevs.com/account/tickets/). I am closing the issue for now. Thanks for your understanding.
