### ISSUE TITLE
Category type as checkbox is not showing the output value as parent -> child-> sub-child wise

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#793]
**Describe the bug**: 
In the latest version(3.1.16), category as checkbox type is not showing the output values as Parent -> Child category view.

**How to Reproduce**: 
Create a form with the category field. Then change the type to Checkbox from the [Advanced Options](http://prntscr.com/qupge7). Then visit the form from the frontend side and you will see the output is displaying as all Main categories list instead of Main Category -> Sub-category.

**Expected behavior**: 
It should result in the list as parent->child listing. [Like this](http://prntscr.com/qupifw).

**Additional input (Screenshot/video)**: 

Please check the screenshot to catch the issue on the frontend. 
https://drive.google.com/file/d/1WO3KHoESFKgc3bIK-rSOmY-hkCbKPNa9/view?usp=sharing

Thanks

**Comment by rokibulislam** [comment]
https://github.com/weDevsOfficial/wp-user-frontend/commit/fcfcd72b368929e072bdcf473722fdd65cabc077
