### ISSUE TITLE
Adding Inline styles to Html element will break and clear entire fields in your form

### ISSUE THREAD

**Issue by Imageburst** [weDevsOfficial/wp-user-frontend#795]
**Describe the bug:**
I just recently tested this with your most recent update. When you try to insert any inline style to an HTML element. The contents of the forms get completely wiped out. Even when I didn't hit save and tried to refresh the form, the changes where permanent. 

All the fields I had created were cleared out/dropped and had to start over again to rebuild the form. Luckily It was a copied version I was playing with and not the original.  

This can cause some serious issues if people don't know about this. 

**How to Reproduce:**
Please try and see for yourself in any form you build. It will wipe out the contents of the form completely without a way to restore/undo those actions (of adding inline styles to an HTML field).

Add any inline styles or this one `<h3><span style="color: #ce0;">Thank you for our Form</span></h3> or  <h1 style="color: #baf500;">Thank you for our Form</h1>`

**Comment by rokibulislam** [comment]
Fixed it in develop version, we release as soon as possible

**Comment by shayanali995** [comment]
This happens with me as well my working form is completely removed after saving the form and form style aren't working as well
