### ISSUE TITLE
Edit user - 500 error wpuf_user_edit_profile_form

### ISSUE THREAD

**Issue by anointed** [weDevsOfficial/WP-User-Frontend#8]
When I click on edit for a specific user I get the following error:
( ! ) Fatal error: Call to undefined function wpuf_user_edit_profile_form() in C:\websites\zurb.dev\wp-content\plugins\wp-user-frontend\wpuf-edit-user.php on line 21

**Comment by Sk-Shaikat** [comment]
This issue has been fixed long ago. please close this.
