### ISSUE TITLE
Rich text editor incompatibility with WP block editor??

### ISSUE THREAD

**Issue by Serendipity31** [weDevsOfficial/wp-user-frontend#801]
I am using WP UserFrontend for a WP site that uses the newer WP block editor.  I am the site admin, and I have a range of users who are restricted to submitting posts using a WP UserFrontend Form (or editing them through their individual dashboards once posted). When I set the WP UserFrontend Form up such that the text input area is one of the rich text editors, it seems to work fine within the form. My users can add formatting, and line breaks, and such, but when they hit 'submit', all of that gets stripped away, and the post looks exactly like they had written it (poorly) in a plain text editor. When I go into the posts in the back end as the admin, the stuff submitted as rich text ends up in a 'WP classic editor' block.  I can change the block type in the back-end and manually add back in the formatting, but that defeats the purpose of fron-end posting entirely and isn't a real solution. 

Is there a way around this? 

I can't find anything in the documentation of the plugin that suggests it's not compatible with the new WP block editor, and I can't find any suggestions for how to fix this online, and this is definitely frustrating people. They put care into making something look nice, only for it to look terrible in practice.  Thanks for your help!

**Comment by itowhid06** [comment]
Hello @Serendipity31, I was unable to replicate the issue in my testing environment. Can you please open a ticket [Here](https://wedevs.com/contact) so that we can further assist you solving it. Thanks.

**Comment by itowhid06** [comment]
@Serendipity31, Due to lack of response I am closing the issue for now. Please feel free to reopen it if you need further assistance. Thanks.
