### ISSUE TITLE
Allow custom redirect after login

### ISSUE THREAD

**Issue by mrmadhat** [weDevsOfficial/wp-user-frontend#805]
I would like the user to be redirected to a custom post type archive upon login, the current redirects settings do not allow for this.

I would like to either the option to set an archive or the option to specify a custom redirect url.

Currently I have the archive page loading the login form when the user is not logged in but when the user logs in they are always redirected to the homepage (even if I select previous page or do not select a redirect).

**Comment by mrmadhat** [comment]
As a temporary fix I'm using the `wpuf_login_redirect` filter:

```
function apply_redirect_on_login($redirect) {
	return get_post_type_archive_link('CPT_HERE');
}

add_filter('wpuf_login_redirect', 'apply_redirect_on_login', 10,2);
```

**Comment by zamandevs** [comment]
@mrmadhat Hope [THIS](https://prnt.sc/229jqbp) will help
