### ISSUE TITLE
Category type as "Text Input" is not saving the category with the posts

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#807]
**Describe the bug**: 
With the latest version of WPUF Free(3.1.17), If you set the category type as "Text Input" from the field's additional option then it's not saving the inserted category with the post.

**How to Reproduce**: 

- Insert a post form with Category Field 
- Make sure the Category Type is selected as "Text Input" from the field's Additional settings
- Then visit the form from the frontend side.
- Insert a **Category** and submit the post form. You will notice the **Category** is not saved with the inserted post.

**Additional input (Screenshot/video)**: 
You can check [this video](https://drive.google.com/file/d/1V7SkTyoZqmTZpxmHKbysk9DQw5wKJBaK/view?usp=sharing) for further explanation.

**Comment by itowhid06** [comment]
I just tested it and it is working as expected with develop version!

**Comment by TasfiaMohtasim** [comment]
Vaiya, the issue exists in develop version: https://www.loom.com/share/11255c71e23f4818afd618014fb8a318

**Comment by itowhid06** [comment]
Sorry for the confusion! I tested with custom taxonomies and those are working as expected!. Reopening the issue.
