### ISSUE TITLE
Checkbox type in Taxonomy field is not showing data while Editing

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#808]
Description: 

If we take the taxonomy field and then set the type of the taxonomy as checkbox in the post form, after a user submits a post, the submitted category cannot be found from the account page > posts section while editing the post from the frontend. 

The category shows up in the post from frontend [from backend as well]but only missing in the edit section from the frontend. Please check out the screenshots for [frontend](https://prnt.sc/qyqvfw) and [backend](https://prnt.sc/qyqvcz) respectively.

How to Reproduce the Issue: 

Please create a post form from WP-admin > WPUF > Post form and then add some fields including the taxonomy field.

Edit the taxonomy field and select the type as "checkbox" from the advanced option. Please check out the [screenshot](https://prnt.sc/qyqui1).

Then submit a post using that form and try to edit the post from frontend account page > posts section.

Current Behavior: User's selected options are not showing while editing. [Video is here](https://www.loom.com/share/dfd53b44d1a1448caae4d08dde73002c).

Expected Behavior: The selected options should show up the post from the frontend while editing.

**Comment by itowhid06** [comment]
Related https://github.com/weDevsOfficial/wp-user-frontend/issues/802. Fixed in https://github.com/weDevsOfficial/wp-user-frontend/commit/d27cbf0bf7727ebfac3cab587597ded09c2e755a
