### ISSUE TITLE
File upload's AJAX could lead to file flooding from attack

### ISSUE THREAD

**Issue by karltdev** [weDevsOfficial/wp-user-frontend#809]
Every file upload, by file field, creates a file in Media. Attackers can send request multiple times to flood the Media with the same file. Any preventions could be done? Maybe you could implement a frontend verification and upload the file only when the form submits. A recaptcha on upload could help too.

**Comment by shabnam611** [comment]
Hello @karltdev, 

Since you have already created ticket for our support team, we will handle it from our support end. Please follow that. 

Regards,

**Comment by karltdev** [comment]
Sure thanks

**Comment by karltdev** [comment]
The patch does not fix the issue.

Steps to reproduce:
1. click upload button and choose a file
2. the file is uploaded and thumbnail is shown
3. click the remove button
4. check the old file is still remain in Media
5. repeat step 1 with the same file
6. the file is uploaded with different name, e.g. name-1.jpg.

**Comment by itowhid06** [comment]
Hello @karltdev, Can you try in a test environment within a fresh install?

Both of your suggestions were not feasible at the moment. The current solution is whenever you upload a media file with a unique file, it generates a hash and uploads the file after that whenever you try to upload another file it checks the hash and only uploads files of which hashes are not present in the database. Though I admit it will fail in certain cases(i.e. like the one you described). But a fullproof solution has a giant overhead on the system and we were reluctant to implement it. But think as an attackers point of view, and it will definitely limit the scope of attack.

Hope I was able to answer your query. Thanks.

**Comment by karltdev** [comment]
To make things clear, my suggestion is as below:
1. click on upload button and choose the file to be uploaded
2. instead of returning the image tag when the validation success, a success respond JSON is returned
3. instead of directly insert the returned image tag, turn the uploaded image to base64 string using javascript and display as thumbnail if the file is an image
4. on form submission, the file is uploaded together with other form data

I did not go through all your considerations but the above work flow sounds more reasonable to me and should be able to tackle the issue.

Besides, may I ask for the action/hook that WPUF used so that I can get and manipulate the form data on form submission, so that I can avoid using the file field from WPUF and use my own file field by using custom HTML? Every thing is working fine but just the file field is holding back my whole project. Thanks a lot for all the replies.

**Comment by itowhid06** [comment]
Hello @karltdev,

You can use `wpuf_add_post_args` & `wpuf_update_post_args` Filters to modify the post data. Thank you.
