### ISSUE TITLE
Conflict with WooCommerce plugins - Bookings & Product Addons

### ISSUE THREAD

**Issue by blues20** [weDevsOfficial/wp-user-frontend#811]
WPUF is a wonderful plugin - just noticed it is not yet compatible with WooCommerce Bookings + WooCommerce Product Addons.  Once WPUF is activated, the Add Field form on Woo product edit would not pop up any more.  The following debug info could be helpful:

[07-Feb-2020 18:35:35 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_type() on bool in /home1/.../wp-content/plugins/woocommerce-bookings/includes/integrations/class-wc-bookings-addons.php:43
Stack trace:
#0 /home1/.../wp-includes/class-wp-hook.php(288): WC_Bookings_Addons->addon_options(Object(WP_Post), Array, '{loop}')
#1 /home1/.../wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#2 /home1/.../wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home1/.../wp-content/plugins/woocommerce-product-addons/includes/admin/views/html-addon.php(154): do_action('woocommerce_pro...', Object(WP_Post), Array, '{loop}')
#4 /home1/.../wp-content/plugins/woocommerce-product-addons/includes/admin/class-wc-product-addons-admin.php(99): include('/home1/...')
#5 /home1/.../wp-includes/class-wp-hook.php(288):  in /home1/.../wp-content/plugins/woocommerce-bookings/includes/integrations/class-wc-bookings-addons.php on line 43

**Comment by itowhid06** [comment]
Hello @blues20, can you please open a ticket [Here](https://wedevs.com/contact) so that we can further assist you solving it. Thanks.
