### ISSUE TITLE
Submit button not working in front end post form

### ISSUE THREAD

**Issue by swamiv1984** [weDevsOfficial/wp-user-frontend#812]
I have created a custom fields in ACF pro and created a front end posting form in wpuf. When I test the form, the submit button is not working. After struggling several hours, I found one issue. I have a website url created in ACF pro and also created website url field in wpuf. The issue is, the form can be submitted only when I add http:// or https:// in the front end. The form cannot be submitted without http:// or https://. I even don't get any error or warning message in the wpuf front end form. This is ridiculous. How do I fix this?. This plugin lacks lot of features.

**Comment by itowhid06** [comment]
Hello @swamiv1984, The HTML5 [URL field](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url) gets automatically validated, It's not an issue of WP User Frontend. Thank you for your understanding.

**Comment by swamiv1984** [comment]
I found wpuf is not fully compatible with ACF Pro. Some fields submitted in the wpuf form in the front end do not shown in the post. Even Though, the ACF field name and field type and the wpuf field name and field type matches correctly. The only way to fix this issue is, make the field type as text. Then, there is no sense for providing different fields.
