### ISSUE TITLE
Word Restriction does not work for Japanese

### ISSUE THREAD

**Issue by mitsukura11** [weDevsOfficial/wp-user-frontend#818]
Your Word Restriction system does not work for Japanese sentences.
Because your system counts Half-width spaces as words, but Japanese sentences do not use Half-width space.
Therefore, even if I set some Word Restrictions, Japanese users can write unlimited Japanese sentences in your system.
Could you fix this problem?
I hope you to use characters or bytes, not half-wide spaces for word restriction so that we can restrict word volume on any other languages which do not use half-side space.

**Comment by minagonzalez** [comment]
hey! word restriction is not working in my form, I and write in spanish.. i need to fix it :(

**Comment by zamandevs** [comment]
@mitsukura11 Checked other langs including non-Latin lang i.e Arabic, Hebrew, etc. everything is working as expected. 
PS: there was a bug on word restriction which is not lang related. so please check on the next release. everything should work as expected.
