### ISSUE TITLE
Billing address issue

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#819]
**Description:** 

When the billing address and country field data is saved in the edit profile, these are not appearing  correctly in the billing details while purchasing the subscription pack. A default Afghanistan as the country and state Alaska is getting selected automatically.

**How to Reproduce the issue:** 

Please open the edit profile field. Save a specific address. 

Then try to purchase a subscription pack. 

Check the billing details, only country, and state field data is incorrect. 

**Expected behavior**: the billing address details should appear correctly in all the sections. 

**Current Behavior**: Country and State are selected as Afghanistan and Alaska respectively.

**Video**: https://www.loom.com/share/72c6f0f9dc7e4386ba2a14ece76657b0

**Comment by itowhid06** [comment]
`When the billing address and country field data is saved in the edit profile, these are not appearing correctly in the billing details while purchasing the subscription pack.`
Basically it is the other way around!
You can chose the billing address any address you want and the next time in the billing address section of account it will reflect.

**Comment by beesum** [comment]
Why if the address is already available would you make users enter it again?  Why not check to see if the field has a value, if it does, display that value.  If it doesn't then revert to the default.  It would make for a nicer user experience not to have to enter the same data twice when it is already available in the database.

**Comment by itowhid06** [comment]
Address section has been updated in https://github.com/weDevsOfficial/wp-user-frontend/commit/d54d25d0c81805266269fe4932c584d10723d6ea

**Comment by Anticosti** [comment]
Hi itowhid06,

I updated my files with yours:
admin/class-admin-settings.php
lib/class.settings-api.php
wpuf-functions.php

and still Afghanistan shows there, when I just want Canada and United States to appear.

...hmmm

**Comment by itowhid06** [comment]
Hello @Anticosti,

I put the wrong commit there, sorry about that. Any ways now I have updated it. Please update accordingly.

Thanks.

**Comment by Anticosti** [comment]
@itowhid06 Yep! Now this is fine. Big thanks for that quick support !!!
You guys at Wedevs really improved your response time. This is noticable. Kudos!!!
