### ISSUE TITLE
WP User Frontend Pro - business Version 3.1.13

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#820]
Greetings,

I found out that any time I need to edit a color in any of these plugins:
- GDPR Cookie Compliance Plugin
- Google Analytics Dashboard for WP (GADWP)
- Multi Rating

I have to desactivate WP User Frontend Pro - business Version 3.1.13

Screenshots before desactivating:
GDPR Cookie Compliance Plugin
https://www.dropbox.com/s/hjqwvxpagn10fdu/S%C3%A9lection_391.png?dl=0
Multi Rating
https://www.dropbox.com/s/sexl6p4v04sfm0g/S%C3%A9lection_392.png?dl=0

Screenshots after desactivating:
GDPR Cookie Compliance Plugin
https://www.dropbox.com/s/xyrsxcnk7o3b357/S%C3%A9lection_394.png?dl=0
Multi Rating
https://www.dropbox.com/s/jrk0hejwgk3q6eq/S%C3%A9lection_395.png?dl=0

**Comment by itowhid06** [comment]
Fixed in https://github.com/weDevsOfficial/wp-user-frontend/commit/d54d25d0c81805266269fe4932c584d10723d6ea
