### ISSUE TITLE
Edit Profile from Dashboard wrongly map the Email Address field

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#823]
Just noticed that if you use the tab "Edit Profile" from the Dasboard, the "Email Address *" field is wrongly mapped. It shows the user pseudo instead of he's email address.

Thanks.

**Comment by itowhid06** [comment]
Hello @Anticosti, 
In my testing the email was mapped correctly. Can you provide a screenshot or screencast about the issue you are facing?

Regards

**Comment by Anticosti** [comment]
@itowhid06 Sorry. I can't reproduce anymore. Maybe a cache issue on my side or some gremlins passing by...? Anyhow, let's close this one. Sorry again. :(
