### ISSUE TITLE
Subscription page redirect after registration is not working

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#830]
**How to reproduce the issue:**
- Navigate to WPUF- Settings -> Payments Tab
- Enable Payments and Subscription at registration options
- Make sure you have the subscription package available
- Create a registration page with the associated shortcode `[wpuf-registration]`
- Turn around to your frontend registration page & register a user
- Click on the Registration button then **you will notice it's not redirecting to the subscription page**

**Current behavior:** 
It's redirecting to a [different page instead of the subscription page](https://drive.google.com/file/d/1koXnY1DRRntL5egb-CsSFLCVkk7p-Y4J/view?usp=sharing).

**Expected behavior:** 
It should redirect to the subscription page like this [official documentation video](https://www.youtube.com/watch?v=cF_SfAgiK10).

Thanks.

**Comment by itowhid06** [comment]
You have to set the subscription page properly. You have set it to "Membership Level" page.

**Comment by mmarj** [comment]
Sorry about the subscription package page tagging.

However, still, [it's not redirecting if it's tagged on the setting page](https://drive.google.com/file/d/1koXnY1DRRntL5egb-CsSFLCVkk7p-Y4J/view?usp=sharing).
I would request you please check once again.

**Comment by ediamin** [comment]
@mmarj The current doc video need to be updated. If the settings is on, then user will be redirect to subscription page first, then go to registration page. It works on Pro and I've pushed a fix for this repo with the behavior I've just described.
