### ISSUE TITLE
New feature added: Checkbox to Custom Post Tag

### ISSUE THREAD

**Issue by bazzar701** [weDevsOfficial/wp-user-frontend#833]
Hello,

We needed a feature in our project to convert a Checkbox in the form to a Post tag.
Because it was not available, We hired a developer for this purpose and he made our custom code. We decided to share for other users that need the same feature. It is saved in functions.php so it is not deleted with WPUF updates:

You only need to change "custom_post_type_name" , "checkbox_metakey" and "Tag Name" to your need and it is ready to go.

> > add_action( 'save_post_custom_post_name', function ( $post_ID ) {
> if ( isset( $_POST['checkbox_metakey'] ) ) {
> wp_set_post_terms( $post_ID, 'Tag Name', 'custom_post_name_tags' );
> }
> } );

**Comment by Anticosti** [comment]
Thank you so much for sharing!
This is much appreciated.
Take care!

**Comment by zamandevs** [comment]
@bazzar701 Couldn't understand why you add tags this way, we already have a taxonomy field where all types of taxonomy can add including built-in categories & tags. you can let us your situation more specifically.
