### ISSUE TITLE
Action Hook wpuf_after_register

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#834]
Hello,

this action hook seems Not to work anymore. It does nothing.
Any suggestion why?

Greets,
Denis

> `function update_your_registration( $user_id, $userdata, $form_id, $form_settings ) {
               
                update_user_meta( $user_id, 'first_name', $user_id );
                update_user_meta( $user_id, 'last_name', $userdata );
                update_user_meta( $user_id, 'url', $form_id );
                update_user_meta( $user_id, 'description', $form_settings );   
               
}
add_action( 'wpuf_after_register', 'update_your_registration', 10, 4 ); `

**Comment by rokibulislam** [comment]
add_action( 'wpuf_after_register', 'update_your_registration', 10, 3 );

function update_your_registration( $user_id, $form_id, $form_setting ) {
	
}

**Comment by DenisCGN** [comment]
Thanks a lot, now it works like charme!



```
function update_your_registration( $user_id, $form_id, $form_setting ) {
	
	// check the right FORM
	if ( $form_id != 1358 ) {
	return;
	}
// make sure user ID exists.
	if ( ! $user_id ) {
	return;
	}
	
	if ( isset( $_POST['nickname'] ) ) {

	wp_update_user( array(
			'ID'            => $user_id,
			'display_name'	=> $_POST['nickname'],
			'user_nicename' => sanitize_user( $_POST['nickname'] )
		)
					  );
}	
	
}
add_action( 'wpuf_after_register', 'update_your_registration', 10, 3 );
```

**Comment by DenisCGN** [comment]
This Hook is also very nice.

> add_action( 'wpuf_update_profile', 'update_your_profile', 10, 3 );
