### ISSUE TITLE
Subscription package is not deleting from the wp-user back-end profile

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#835]
**How to reproduce:** 
- Navigate to any user's back-end profile then assign any existing subscription pack to the users or try with any users who have already any subscription pack assigned.
- Delete the existing or assigned package from the back-end and update the profile.
- Then you will notice the assigned/deleted subscription package is not deleted or re-assigned.

**Additional Screencast:** Please [check this video]() if you may need further clarification.

**Comment by bazzar701** [comment]
Not fixed. It is behaving exactly the same and it is still not possible to delete or assign subscriptions to users.

**Comment by itowhid06** [comment]
This is working as expected!
https://www.loom.com/share/5f96be0a2753476d9a9f389bdb9c0d81

**Comment by bazzar701** [comment]
Just tried on mobile and it works! 
But on desktop it was not working. I will re-check today. Thanks a lot!

**Comment by bazzar701** [comment]
All working. Might have been a cache problem.
Thanks again for the quick solution.

**Comment by Anticosti** [comment]
Curious. I updated my code with this commit:
https://github.com/weDevsOfficial/wp-user-frontend/commit/77f5d51a883ce94fbe79f4c12735fd405955eaec
Cleared all my caches;
and still having the issue on two sites

**Comment by Anticosti** [comment]
After upgrading to 3.2.0
When trying to delete this free package that I named **Out**, I get this error:
Warning: Invalid argument supplied for foreach() in /home/user/public_html/wp-content/plugins/wp-user-frontend/admin/class-admin-subscription.php on line 645
