### ISSUE TITLE
Your free package has been activated. Enjoy!

### ISSUE THREAD

**Issue by bazzar701** [weDevsOfficial/wp-user-frontend#836]
I have found that on payment gateway, if user changes the URL to a different pack id, they get a free Subscription Pack activated:

?action=wpuf_pay&type=pack&pack_id=4669126 (Correct Subscription Pack)
?action=wpuf_pay&type=pack&pack_id=4669125 or  4669124 or 4669127 (Your free package has been activated. Enjoy!)

Free Subscription Pack name: "Notify when content is published" or "Front Page"

It should deliver a 404 errors and not Free package activation with back-end labels.

**Comment by Anticosti** [comment]
Nice find

**Comment by bazzar701** [comment]
I will check if the free packages override a valid and paid subscription pack.
