### ISSUE TITLE
WPUF login page override option is not working

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#843]
**How to reproduce the issue:**
- Create a login page with the [wpuf-login] shortcode
- Make sure the Login/Registration override & Default Login Redirect option is checked
- Then select the [login page on the setting](http://prntscr.com/rrvz3m).
- Then logout and try to login again from yoursite.com/wp-admin URL 
- You will notice it's letting you access the default WordPress login form/page instead of redirecting it to the `[wpuf-login]` page.

Expected behavior: it should redirect the page to the [wpuf-login] page.

**Additional Video:** 
https://drive.google.com/file/d/1xWyxefeqp5vHC6RU0skgB67bga4oz6eB/view?usp=sharing

**Comment by DenisCGN** [comment]
Sorry but this does not work.
I set all the points.
When I enter 

https://centerstage.de/wp-login 
https://centerstage.de/wp-admin

It sende me to the standard WP pages.  not to https://centerstage.de/anmelden/

NOT WORKING

Cheers,
Denis

**Comment by DenisCGN** [comment]
Does it work now?

Von meinem iPhone gesendet

**Comment by mmarj** [comment]
Hello @DenisCGN 
You can check the output by downloading & installing the [developer version](https://github.com/weDevsOfficial/wp-user-frontend/archive/develop.zip).

However, I just checked & found the hot-fix is working fine on my testing site.
Cheers!

**Comment by DenisCGN** [comment]
Perfect, I thought there was nothing done, only closing the Threat.
Thanks a lot!
Cheers


Von meinem iPhone gesendet
