### ISSUE TITLE
Password fields in custom edit profile.

### ISSUE THREAD

**Issue by conradomd** [weDevsOfficial/wp-user-frontend#847]
Password fields should have behave like default edit profile form. In custom form, users is forced to change password.

**Comment by ediamin** [comment]
@conradomd would you please explain the issue a bit more? Any screenshot will be very helpful indicating what is in the default edit profile form and what is the problem in custom form.

**Comment by hasinur1997** [comment]
This issue is related to wp-user-frontend-pro. A pull request has been created to resolve this issue.
