### ISSUE TITLE
Passwort Reset > FATAL ERROR

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#848]
Hello,

when I use the Passwort Reset on my Website: https://centerstage.de it creates this FALTA ERROR.

> Fatal error: Uncaught TypeError: Argument 1 passed to iThemesSecurity\User_Groups\Match_Target::for_user() must be an instance of WP_User, instance of stdClass given, called in /www/htdocs/w0146/centerstage/wp-content/plugins/ithemes-security-pro/core/modules/password-requirements/class-itsec-password-requirements.php on line 251 and defined in /www/htdocs/w0146/centerstage/wp-content/plugins/ithemes-security-pro/core/modules/user-groups/Match/Match_Target.php:34 Stack trace: #0 /www/htdocs/w0146/centerstage/wp-content/plugins/ithemes-security-pro/core/modules/password-requirements/class-itsec-password-requirements.php(251): iThemesSecurity\User_Groups\Match_Target::for_user(Object(stdClass)) #1 /www/htdocs/w0146/centerstage/wp-content/plugins/ithemes-security-pro/core/modules/password-requirements/class-itsec-password-requirements.php(170): ITSEC_Password_Requirements->handle_plain_text_password_available(Object(stdClass), 'passowrd') #2 /www/htdocs/w0146/centerstage/wp-includes/class-wp-hook.php(287): ITS in /www/htdocs/w0146/centerstage/wp-content/plugins/ithemes-security-pro/core/modules/user-groups/Match/Match_Target.php on line 34

please help,
Denis

**Comment by DenisCGN** [comment]
Why!?
The error is still there!

Von meinem iPhone gesendet

**Comment by ediamin** [comment]
Did you apply the patch from commit? If not, please wait for the next release.

**Comment by DenisCGN** [comment]
What Patch?



Von meinem iPhone gesendet

**Comment by ediamin** [comment]
Hi @DenisCGN you have to apply the changes made in this commit https://github.com/weDevsOfficial/wp-user-frontend/commit/792ed76beb0874db0933ca3531d2013118a34433

If you cannot do it by yourself, please wait for the next release in wp.org

**Comment by DenisCGN** [comment]
So what for is that ISSUE field?

And my other post is also deleted.
After_register Action hook

I wanted to ask, if there is a profile hook after update the profile?

Where do I get the patch?
What is it for an error the password reset causes?

Very strage and top secret that github thing!

I go and ask the support 

Von meinem iPhone gesendet

**Comment by ediamin** [comment]
Denis we did not delete your issues from Github, we are not allowed to do that. Those are just closed since they were resolved. Here is your another issue link https://github.com/weDevsOfficial/wp-user-frontend/issues/834

You can find all closed issue if you use the `Closed` filter in issue page https://github.com/weDevsOfficial/wp-user-frontend/issues?q=is%3Aissue+is%3Aclosed

**Comment by DenisCGN** [comment]
Ok,
thanks,

I like to ask now if there is a hook after the profile is updated. Cause I need to do the same changes I did with that after_register Hook.

So may I ask that? 

Or maybe you know it!?

Denis

Von meinem iPhone gesendet

**Comment by ediamin** [comment]
You can use the core `profile_update` hook from `wp_insert_user` function
```
/**
 * Fires immediately after an existing user is updated.
 *
 * @since 2.0.0
 *
 * @param int     $user_id       User ID.
 * @param WP_User $old_user_data Object containing user's data prior to update.
 */
do_action( 'profile_update', $user_id, $old_user_data );
```

**Comment by DenisCGN** [comment]
This will work in an frontend profile I created with a registration form?

Von meinem iPhone gesendet

**Comment by DenisCGN** [comment]
Hello again,

I just Need a hook…that fires and does the same like in the wpuf_after_register:



function update_your_profile( $user_id $old_user_data,) {
	
// make sure user ID exists.
	if ( ! $user_id ) {
	return;
	}
	
	if ( isset( $_POST['nickname'] ) ) {

	wp_update_user( array(
			'ID'            => $user_id,
			'display_name'	=> $_POST['nickname'],
			'user_nicename' => sanitize_user( $_POST['nickname'] )
		)
					  );
}	
	
}
add_action( 'profile_update‘, 'update_your_profile', 10, 2 );






Gesendet von Mail für Windows 10

Von: Edi Amin
Gesendet: Mittwoch, 8. April 2020 20:43
An: weDevsOfficial/wp-user-frontend
Cc: DenisCGN; Mention
Betreff: Re: [weDevsOfficial/wp-user-frontend] Passwort Reset > FATAL ERROR(#848)

You can use the core profile_update hook from wp_insert_user function
/**
 * Fires immediately after an existing user is updated.
 *
 * @since 2.0.0
 *
 * @param int     $user_id       User ID.
 * @param WP_User $old_user_data Object containing user's data prior to update.
 */
do_action( 'profile_update', $user_id, $old_user_data );

**Comment by ediamin** [comment]
@DenisCGN Since you had asked for a hook _after the profile is updated_, I suggested the _profile_update_ hook. If you need a hook after register or create a user, you can use `user_register` hook from WP core,

```
/**
 * Fires immediately after a new user is registered.
 *
 * @since 1.5.0
 *
 * @param int $user_id User ID.
 */
do_action( 'user_register', $user_id );
```

**Comment by DenisCGN** [comment]
Hello Edi,

I already got the solution about your wpuf hook

Wpuf_update_profile

Thanks 

Von meinem iPhone gesendet
