### ISSUE TITLE
Pay Now button showing until the post status change to Published

### ISSUE THREAD

**Issue by mahbubme** [weDevsOfficial/WP-User-Frontend#85]
Regarding the payments, I'm doing some tests and, in the case of "Pay-per-post ", everything is working well, but the "status" of the payment.

When paying with Paypal, the confirmation is updated in a few seconds in the "transactions" of the WPUF menu. Until then, everything is ok. However, for the buyer, the status remains as "pay now". 

Look:
http://oi68.tinypic.com/2q064pg.jpg

**Comment by tareq1988** [comment]
Fixed in c544c3faa429d25fa8a0abe868a61936d6ea5f7e. Added payment status for pay-per-post payment.
