### ISSUE TITLE
wp user front end conflicting with woocommerce

### ISSUE THREAD

**Issue by mohsinkharwa** [weDevsOfficial/wp-user-frontend#852]
my woo commerce lost your password do not open page when clicking on it & on doing logout it shows something went wrong i search a lot for this prob and find a solution saying a plugin may cause this prob so i deactivated all the plugin and activated them one by one and checked the option the option stop working when i activated wp user front end then i activated all plugin and just deactivate wp user font end the option start working
so what i want to say that wp user front end is the plugin that is conflicting with lost your password & logout option on website – login – lost your password
and also login and lost pass option in registration form are not working
please go through the video link for better understanding 
video - https://oneking.in/aiovg_videos/wp-user-front-end/

**Comment by hasinur1997** [comment]
This is doesn't exist.
