### ISSUE TITLE
Make login page form compatible with recaptcha3

### ISSUE THREAD

**Issue by Brakkar** [weDevsOfficial/wp-user-frontend#854]
Hi,
form submission is compatible with recaptcha3 (silent).
But the login form displays an error message and seems not compatible with recaptcha3 keys (possibly affects other default forms).

How to reproduce:
- Enter recaptcha3 keys
- Enable recaptcha on login form
- Load page with login

![Capture d’écran 2020-04-13 à 23 48 22](https://user-images.githubusercontent.com/5489200/79164493-7444c900-7de1-11ea-961a-ada1bab4e294.jpg)

**Comment by Fendt1** [comment]
I have the same problem. V3 is not working. And with V2 I cannot log in. If activated or not. It states wrong captcha.

**Comment by zamandevs** [comment]
@Brakkar v3 doesn't better than v2. both serve different purposes. v2 generally uses for login/registration form etc where Recaptcha tries to validate humans and if not gives the option for another chance to validate again. so it's validated directly through boolean style. on the other hand, v3 generally gives a score that doesn't mean right or wrong. generally, other areas where the form is not present but user interact v3 uses there.

**Comment by Fendt1** [comment]
Thank you!
