### ISSUE TITLE
Login, Password-reset

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#859]
Hello,

can you please make the templates LOGIN und PASSWORD-RESET the same structur like the post and register forms (with divs insted of p tags)?
It looks totally unprofessionell to have a nice looking post and register form and the such ugly simple loveless login and password reset form.

Regsiter: https://snipboard.io/kozJM8.jpg
Login: https://snipboard.io/HIWxFQ.jpg

Cheers,
Denis

**Comment by Fendt1** [comment]
Yes, thats true!
is there a CSS trick or so?

Wishes by Josef
