### ISSUE TITLE
List of Available Template link directs to content restriction page

### ISSUE THREAD

**Issue by mainul11** [weDevsOfficial/WP-User-Frontend#86]
When i click on 'List of available templates can be found here', it takes to the content restriction page. It should direct to the Form templates page <https://docs.wedevs.com/docs/wp-user-frontend-pro/posting-forms/form-templates/> 

![wpuf template link prob](https://cloud.githubusercontent.com/assets/20102452/23983313/819bccea-0a3d-11e7-9af0-06abba8d6e8f.jpg)

**Comment by tareq1988** [comment]
Previously I created a docs page for that and linked on that footer area. But someone changed that link to the content restriction page. I've changed the URL already in the new builder branch.

**Comment by mainul11** [comment]
Thank you :)
