### ISSUE TITLE
AVATAR wrong size

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#860]
Hello,

I set the image size of the AVATAR 200x200 but the AVATAR does not show correctly :-(

Setting: https://snipboard.io/5OKMA9.jpg
Profile: https://snipboard.io/JU4rpO.jpg

Denis

**Comment by ediamin** [comment]
@DenisCGN Thank you for reporting the bug. You'll need WPUF Pro for the complete fix. We'll release both free and pro version hopefully next week. If you need the fixed Pro version urgently, please contact our support.
