### ISSUE TITLE
E-Mail activation link is to big or Template to small

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#861]
Hello,
can you please make the E-Mail Template with more width?
The link destroys always the design.
https://snipboard.io/FlOeIu.jpg
Because your link is to big! Or the Width is to small, please change this.
Thanks,
Denis

**Comment by Anticosti** [comment]
+1

**Comment by mmarj** [comment]
Hello Denis,
​
​Please make sure you are using the latest **WPUF Pro version 3.2.0** cause we already resolve the **Activation Link** text on this version. It should show you the [masked hyperlink text](http://prntscr.com/s07h19).
​​ 
​Thanks & cheers!
