### ISSUE TITLE
Word Restriction non-latin words Dosnt work!

### ISSUE THREAD

**Issue by denis012** [weDevsOfficial/wp-user-frontend#863]
Hello, im using your great plugin and i have some problem with Word Restriction.
My website is in hebrew lang (non latin characters).
When i try to using Word Restriction with the rich text editor (tinymce).
Its work great when i try write in English:
![1worderror](https://user-images.githubusercontent.com/2553083/79688363-8d70ce00-8256-11ea-9a8a-890aa00a0f22.png)
but when i try write Hebrew its show me “o” (zero) words always no metter what:
![2worderror](https://user-images.githubusercontent.com/2553083/79688368-9366af00-8256-11ea-9285-18fef9f37f54.png)
How can i make it count non latin words also?

Thanks for your help!

**Comment by zamandevs** [comment]
@denis012 Checked on my end. working as expected [HERE](https://prnt.sc/229ic3k)
