### ISSUE TITLE
Adding Featured Image Without reCAPTCHA Breaks Post Form

### ISSUE THREAD

**Issue by Web4Guru** [weDevsOfficial/wp-user-frontend#864]
I created a post form many months ago, and recently, after clicking the button to upload a featured image and selecting an image to use, the submit button at the bottom of the form is disabled and greyed out.

I’m a developer so I started looking into what could be causing the problem. Directly after picking the image, the browser console log shows an uncaught reCAPTCHA error, “No reCAPTCHA clients exist.”

We aren’t using reCAPTCHA here and do not have the reCAPTCHA keys entered into the plugin’s settings.

I set up the reCAPTCHA keys and added a reCAPTCHA field to see if that fixes things, and sure enough, the button now starts out disabled and greyed out, a featured image can be uploaded without generating an error in the console log, and checking the "I'm not a robot" box enables the submit button.  

We really don’t need reCAPTCHA for our purposes though, so it would be great if this issue could get fixed.

**Comment by hasinur1997** [comment]
Couldn't reproduce the issue.
