### ISSUE TITLE
Plugin's admin interface language is NOT matching user admin language

### ISSUE THREAD

**Issue by nash-ye** [weDevsOfficial/wp-user-frontend#865]
Hi,

Can you please check what's wrong with the plugin admin interface locale? It ignores the selected language for admin panel for the user if it's different than site language.

**Comment by zamandevs** [comment]
@nash-ye Should work as intended. please provide us some screenshots etc. which part break on your end.

**Comment by sapayth** [comment]
Hopefully, the problem is solved. Feel free to create a new issue or [contact us ](https://wedevs.com/contact)for any queries.
