### ISSUE TITLE
Custom taxonomies do NOT appear in latest 2 updates

### ISSUE THREAD

**Issue by sarahsampino** [weDevsOfficial/wp-user-frontend#866]
Hi, I had to rollback WPUF after updating it (to 3.1.17). Taxonomies entered into the frontend form for a Woocommerce product do not appear in the product page or admin dashboard. You can see the difference here with the two listings with all blank taxonomy fields.
![image](https://user-images.githubusercontent.com/55568990/80445668-da057a80-88e2-11ea-99b1-cae6f9663988.png)

**Comment by hasinur1997** [comment]
This  issue doesn't exist
