### ISSUE TITLE
With the WPUF category field, Child categories are not appearing on the frontend if you set multiple categories on selection terms

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#869]
**How to reproduce:**
- Create a category field with[ Selection Type -> Child of and with multiple categories](http://prntscr.com/scuvid) which have a sub-category
- Visit the form from the frontend area
- You will see only the first one's child-categories are appearing over there instead of alls.

**Additional Video**: Please [check this video](https://drive.google.com/file/d/1pMgtqPGJBRgn5CSqtqLFxP3v_FNP_N_X/view?usp=sharing).

**Expected Behavior**: It should output all of the predefined _selection terms_ child-categories over the frontend side

**Comment by kabirbd89** [comment]
I got this problem too... Following.

**Comment by Dumorya** [comment]
Please correct this issue, this is really important for my website...
