### ISSUE TITLE
Form Submission disabled with Featured image and Invisible Recaptcha

### ISSUE THREAD

**Issue by R2wix9mtdI** [weDevsOfficial/wp-user-frontend#870]
I have the current version of Invisible reCaptcha By Mihai Chelaru installed to protect login / resgistration / comments / forgot / password for Wordpress, WooCommerce and Contact Form 7.

As soon as I upload a featured image to this page:

https://www.coastwatchers.visitfyldecoast.info/coast-watchers-submission-form/

The Submit button becomes disabled and i can't submit the form/ I can disable the plugin and it works, but the UFE plugin doesn't give me the recaptcha protection on other areas of the site and does not seem to support Invisible Captcha v3.

I'm using UFE on two of my sites now and this is quite disruptive. No obvious errors in the browser console or the PHP Error log monitor that I have installed.

I've seen similar issues raised about reCaptcha, but specifically not about this.

**Comment by Fendt1** [comment]
Dear R2,

I had also a problem of the disabled button in compination with reCaptcha. 
The solution was: on the same page was another form on the side with a CAPTCHA. When i clicked into this second CAPTCHA, I could send the first form. 
So I moved the second form to another page and it works well now.

Hope this helps.

Bye from bavaria

**Comment by R2wix9mtdI** [comment]
Fendt1 - thanks so much for the reply. On this occassion I only have a single form on the page.

Bye from UK :-)

**Comment by zamandevs** [comment]
@R2wix9mtdI We have form builder for Reg & post submit which generally requires visible recaptcha. thus we are not considering v3/ invisible recaptcha for now. maybe in future we will support both.
