### ISSUE TITLE
Problem With Radio Button, Multiselect Button Data show

### ISSUE THREAD

**Issue by kabirbd89** [weDevsOfficial/wp-user-frontend#873]
Radio Button, Multiselect Button Issues,

1. If anyone touch any non required radio button accidentally he/she cant able to undo it. 
2. If I does not select any thing in multi select its show **-1** in post data. 
3. For both radio and multi select button when data enable to show in post it does show **value** instead of **level**. Ex. (If I Put **South Asia** in radio button level its show **south_asia** which is value. ) And make it right I need to **copy** South Asia Level and **paste** it to value field. And Its for every level. Its funny and painful.

**Comment by ediamin** [comment]
@kabirbd89 thanks for reporting the issue. I've pushed a commit with fixes for all of your issues.

To deselect a radio field, you have to double click on the radio button now.

**Comment by kabirbd89** [comment]
@ediamin  
Thank you for looking at this issue, I just update. And I think things are worst right now. 

1. The colon sign (:) disappear after update.
**2. Blank Field Level are showing after update, which is real mess.**
3. In multi select data field, shows bar (|) between two value, may be showing comma (,) will be more perfect for user experiences.

Option 3 not a big issue for me, but I expect comma to give better experience to my users, I can also add some custom css and change filed level color as there is no colon sign. But I request you to check number 2 asap, Its really mess here. Field Level without data should not show in fronted as it was.

With Love
- K

**Comment by ediamin** [comment]
@kabirbd89 as I mentioned in another comment of yours, please create a different issue for each problem you're having. 

Thank you very much.

**Comment by kabirbd89** [comment]
Okey I make another issue. thank you.

**Comment by ediamin** [comment]
By the way, the word is not level, it's "label"

**Comment by kabirbd89** [comment]
@ediamin 
I am not good at english. Think you for your reply.

Love
- K
