### ISSUE TITLE
Meta key change every time if field level change

### ISSUE THREAD

**Issue by kabirbd89** [weDevsOfficial/wp-user-frontend#874]
Meta key for Field Level change every time when Field level update. Everyone need to copy and save meta key before update field level and after that again paste meta key. 

Is not its a good practice not to update meta key with field level instantly. 

And Also custom image field are acting weird in desktop and mobile device. No padding, no margin, no space and not responsive (mobile devices) if user upload more then one photo. If even upload one photo only its look weird. its supposed to look responsive in mobile devices.

**Comment by ediamin** [comment]
@kabirbd89 Thanks for reporting the issues. I've added a new option to toggle sync values.
<img width="377" alt="Screenshot 2020-06-10 at 5 16 05 PM" src="https://user-images.githubusercontent.com/1541774/84261759-237df200-ab3e-11ea-857b-b6f6bdea8dc7.png">

Regarding the image styling issue, I've opened different issue for that #882. Please create new issue for different types of issue.

**Comment by kabirbd89** [comment]
@ediamin  I was talking about this these two field. not only for radio button or multi select label. 

![jhjh](https://user-images.githubusercontent.com/60269758/84387431-cacd5880-ac14-11ea-9cf4-d805f4dc7465.png)
