### ISSUE TITLE
Has this plugin been abandoned?

### ISSUE THREAD

**Issue by lpcollier** [weDevsOfficial/wp-user-frontend#875]
I've built a website that relies on this plugin, which is now failing to work due to a showstopper error. Most bug reports here have gone unanswered, including my own from a couple of weeks ago. I'm happy to pay for premium support etc., but I don't want to waste time and money on something that's no longer being updated or supported. Does anyone know the project status.

**Comment by ediamin** [comment]
Hi @lpcollier, we're having a number of support tickets for last few months. Many of them are from different source than GitHub. We're trying to resolve all of them including GitHub as soon as possible. Thank you very much.
