### ISSUE TITLE
2nd image upload shows 1st image upload

### ISSUE THREAD

**Issue by TheElephant1979** [weDevsOfficial/wp-user-frontend#876]
Hi,

I found an issue on WPUF which I would like to share. Can't find the same issue here yet.

Reproduction of issue:

Guest 1 (not logged in) submits a posts form including a picture directly from Iphone camera (filename automatically generated 'image.jpg'.) This is processed succesfully.

After that…

Guest 2 (not logged in) wants to submit a post form. Once guest 2 clicks on 'Add file', opens Iphone camera and takes a picture, a preview will be generated in the background and should become visible inside the post form. However Guest 2 will see the picture uploaded by Guest 1.

This happens at 'featured image' and also at 'main content'.

I did some research:
When you take a picture with an Apple device it's camera it immediately uploads it (as image'.jpg).
Problem is that all images will be uploaded as image.jpg and create a image-scaled.jpg immediately.

So when uploading another picture it will also be uploaded as image.jpg and tries to create an image-scaled.jpg. It think it would be nice to add a unique identifier (date/time) immediately after the original file. So the system creates image-20200601235902.jpg for example.
As it is now; the server will always throw back first uploaded image.jpg

Tested this with Android device also and there it is working as one should expect. Because Android camera uses unique camera picture names.

I have tested this on 2 completely different setups and both have the same behaviour.

When you think this might be an Apple issue, than you are wrong (I think 😁) as it does function on your DEMO site. On your demo site i can see that picture get image-1.jpg, image-2.jpg, image-3.jpg and so on. So probably the code is fixed there??

Hope to here from you (very!) soon! Stay save, stay healthy.

**Comment by TheElephant1979** [comment]
To reproduce:

![7DF6A3C0-B57E-4DA4-B909-1C8FB5BCCCFD](https://user-images.githubusercontent.com/13694640/83555995-74269700-a50f-11ea-9fe4-f3baff6564ff.jpeg)


![5FD13BE8-9350-475C-9B5D-DDCADE26DA5F](https://user-images.githubusercontent.com/13694640/83555998-74bf2d80-a50f-11ea-9642-8ca463d18caf.jpeg)


![ADD4B535-36AE-4EE7-94C4-5A155E698B2D](https://user-images.githubusercontent.com/13694640/83556000-7557c400-a50f-11ea-869e-bf97fbca0916.jpeg)


![8743AD93-3E15-4F34-A54D-F1F5B244FAD4](https://user-images.githubusercontent.com/13694640/83556002-7557c400-a50f-11ea-83d2-f77bdbd1cb99.png)


![0F6B3DD1-8FE2-4E3D-9D52-7A77FF53865A](https://user-images.githubusercontent.com/13694640/83556003-75f05a80-a50f-11ea-9ec1-4d4696a1e395.jpeg)


![E7C7F181-E7F9-46C9-B940-100B8DE5ECFF](https://user-images.githubusercontent.com/13694640/83556004-75f05a80-a50f-11ea-9a39-a0b01e94a6df.jpeg)


![0B62FFAF-EA41-4BE5-88DF-6E5A11E67074](https://user-images.githubusercontent.com/13694640/83556005-7688f100-a50f-11ea-8507-91b4bb4b03ce.jpeg)


![B33D95FC-D385-47CA-9601-76CB1F478ED1](https://user-images.githubusercontent.com/13694640/83556006-7688f100-a50f-11ea-8762-986d00d3380d.jpeg)


![03EA4503-F081-434A-AFC0-E1F68A4CA9D3](https://user-images.githubusercontent.com/13694640/83556008-7688f100-a50f-11ea-8899-6392e62260ab.jpeg)


![26F59CFF-B6B9-4C97-89DF-5A822F4D4AA6](https://user-images.githubusercontent.com/13694640/83556009-77218780-a50f-11ea-9cff-2734cc307025.jpeg)
![BCEDABD8-B128-4BCA-B3F5-06DC6F0621E3](https://user-images.githubusercontent.com/13694640/83556010-77218780-a50f-11ea-84f4-877c4561e2bb.jpeg)

**Comment by TheElephant1979** [comment]
Hi @hasinur1997 

in case you need more information about the bug don't hesitate to contact me.

**Comment by TheElephant1979** [comment]
Hi, @ediamin / @hasinur1997 any updates on https://github.com/weDevsOfficial/wp-user-frontend/issues/876 ?

**Comment by ediamin** [comment]
Hi @TheElephant1979, this issue should be fixed by a previous commit. Would you please try pull the latest develop branch and try again? Here is the commands you need to build the zip after cloning our Github repo(make sure you have installed grunt globally),

```
npm install && grunt && grunt zip
```
You should have a zip file in `build` directory in your `wp-user-frontend` directory.

**Comment by TheElephant1979** [comment]
Hi, i'm not that good in GitHub / development, however I have downloaded the part you mentioned.

Seems to be solved, however I do not see thumbnails popping up in the form where I am uploading. I get a http error 200 (which might be due to my server 🤪). Livesite is on a perfect server but I don't want to test it there 🥴.

In the media library I can see that different pictures do get different file names now 👍.

1 questions:

*When will this be deployed to live?

**Comment by ediamin** [comment]
I'll release this in wp.org within this week.

**Comment by TheElephant1979** [comment]
Huge 🤜🤛.
Thanks for your awesome work!

**Comment by ediamin** [comment]
@TheElephant1979 Just released the v3.3.0 in wp.org. Please try now and let us know the result.

**Comment by TheElephant1979** [comment]
Hi,

Installed and works like a charm now! Awesome plugin. Really appreciate you
take time for this and help so many people out there.

I have tested many front end forms and this is by far the best plugin with
which users don't need to login.

👍 Stay save!

Op do 11 jun. 2020 om 13:55 schreef Edi Amin <notifications@github.com>
