### ISSUE TITLE
Custom Fields on Registration/Profile Form do not show in user backend profile UI

### ISSUE THREAD

**Issue by fpert041** [weDevsOfficial/wp-user-frontend#878]
As per title

**Comment by ediamin** [comment]
Hi @fpert041 the feature you're seeking exists in WPUF Pro. If you have installed the pro plugin, then go to `User Frontend > Settings > Login / Registration` and at the bottom, you'll get options to display form fields based on individual user role.

<img width="873" alt="Screenshot 2020-06-05 at 3 25 30 PM" src="https://user-images.githubusercontent.com/1541774/83860574-3e68f480-a741-11ea-8feb-a4ca02c92797.png">

Let us know, this is what you're looking for or anything else. Thanks.

**Comment by fpert041** [comment]
Thanks that makes sense - if you wanted my 2p suggestion: share this on the
official documentation as it might help clarify the process on showing
fields up in the back end
ᐧ

**Comment by ediamin** [comment]
@fpert041 Hey, thanks for the suggestion! We are updating our doc now. 👍
