### ISSUE TITLE
several small tweaks

### ISSUE THREAD

**Issue by rananrahim** [weDevsOfficial/WP-User-Frontend#88]
1. [fix] post title text area not responsive.
2. [tweak] move the hovering edit menu to the right blank area of the form (improves usability)
3. [tweak] add dropdown menu for available meta keys in woocommerce product.
4. [tweak] remove additional + - buttons on radio buttons
5. [tweak] adding new radio button with matching name can trigger multiple choices.
6. [tweak] Align anchor for dragging and dropping form elements to the top of the element.
7. [to be cont.]
![screenshot at mar 19 14-49-56](https://cloud.githubusercontent.com/assets/12949224/24079734/4d07c4a6-0cb9-11e7-9095-fbdf714dbbbc.png)
![screenshot at mar 19 14-50-42](https://cloud.githubusercontent.com/assets/12949224/24079736/4d0deea8-0cb9-11e7-8abe-f0822148c677.png)
![screenshot at mar 19 15-15-31](https://cloud.githubusercontent.com/assets/12949224/24079735/4d0d33aa-0cb9-11e7-912e-2f96dc7d6413.png)

**Comment by Sk-Shaikat** [comment]
These are done
