### ISSUE TITLE
social login and registration not working

### ISSUE THREAD

**Issue by raybell82** [weDevsOfficial/wp-user-frontend#883]
Greetings,

After i have created the app in facebook, google and twitter, the page is redirected back to my 404 page.  the url never seems to make it to facebook, google or twitter.   When I click on the icon, it appears it is trying to go to the Account page for WPUF (I am not using that page) as I am using the My Account page.  Further, it never calls the facebook api to register when I am in a incognito page.

**Comment by ediamin** [comment]
Hi @raybell82! Social login and registration is a WPUF Pro feature and we are aware of this issue. I've released WPUF Pro v3.3.0 already with a fix for this. Please update your plugin and let's see if it is fixed or not. For any kind of issue regarding our WPUF Pro plugin, please contact our premium support. We are always ready to help you there. Thank you very much.
