### ISSUE TITLE
Radio Button, Multi-select Button Problem are pretty worst after update to v3.3.0

### ISSUE THREAD

**Issue by kabirbd89** [weDevsOfficial/wp-user-frontend#886]
First Thank you for working with button issue, some problem are fixed but the following problem are make the whole things pretty worst 

1. The colon sign (:) disappear after update.
2. **Blank Field Label are showing** now after update, which is real mess.
3. In multi select data field, shows bar (|) between two value, may be showing comma (,) will be more perfect for user experiences.

3 is not a big issue for me, but I expect comma(,) as a separator between multiple value to give better experience to my users, I can also add some custom css and change filed Label color as there is no colon sign for number 1 issue. 

**But I request you to check issue 2 asap, its really mess. Field Label without data should not show in fronted as it was before update.**

Thank You for making and updating this excellent plugin. 
With Love
- K

**Comment by ediamin** [comment]
@kabirbd89 thanks for reporting the issues. Please test again with the latest develop branch code.

I've opened a new issue regarding your third issue. You can see it here #890.

**Comment by kabirbd89** [comment]
I was busy and roll backed to previous version. And waiting for a updated. Now its seems okey, but colon are still missing for multiselect, dropdown and radio button. I am going to open another issue for that. Thankyou.
