### ISSUE TITLE
Terms and conditions in version 3.3.30 pro added wont save

### ISSUE THREAD

**Issue by pvtano** [weDevsOfficial/wp-user-frontend#889]
working registration form when modified to add terms and conditions cannot be saved.  the registration form contains username,email, password and recaptcha.  if TAC is deleted i can add website and save ok and add lastname and save ok

**Comment by ediamin** [comment]
@pvtano this issue is related to our Pro version and we've release both free and pro plugins v3.3.1. Please update both and see if this issue is fixed or not. Don't forget to report your findings here.

Thank you very much.
