### ISSUE TITLE
Bug: Profile Pictures disappeared and new uploads don't work

### ISSUE THREAD

**Issue by mappersacademy** [weDevsOfficial/wp-user-frontend#892]
Hi,
Since the update of the plugin last Thursday, the profile pictures of our users have disappeared. When you look at the profile editing form of WPFU, there is a picture (placeholder?) there. When people try to upload their picture again, it doesn't work.

**Comment by mappersacademy** [comment]
Despite the fact that our PRO plugin had not updated, which we have rectified. It appears we have lost all our profile/Avatar pictures. But perhaps they are there, but not showing?

When I upload a new Avatar successfully, it still shows the placeholder photo...

**Comment by Fendt1** [comment]
I have the same problem.
I must exchange all the pictures from new in every account!

Am So., 14. Juni 2020 um 10:24 Uhr schrieb mappersacademy <
notifications@github.com>:
