### ISSUE TITLE
No longer access to WP back-end (dashboard)

### ISSUE THREAD

**Issue by mappersacademy** [weDevsOfficial/wp-user-frontend#893]
Since the update last Thursday, people with access to the WP dashboard (Admins included) can once they have logged out and log in again, no longer get into the dashboard.

Every time, it would take you to the page that is set in our WPUF configuration as our login-page. Yet, we were logged in.

I had to go to the MySQL to deactivate all plugins to be able to get back in.

Since WPUF also manages our access control to pages that should not be public, and since I had to deactivate the plugin, our site is currently offline. 

I am new here, so I hope to find a way to go back to the version before last Thursday, so we can go online with our site again...

**Comment by mappersacademy** [comment]
It turned out that this issue was caused by the paid version of the plugin not having updated to 3.3.0
I do ask though, that after talking via chat and email with the helpdesk, that nobody checked if that was the case. Rather than looking for a solution here...

**Comment by Fendt1** [comment]
I updated both to 3.3.0 but i cannot login. What is the solution?

**Comment by mappersacademy** [comment]
You may have to create your own ticket, as this one is closed and your problem with the login is not exactly the same what we experienced.

However, when I was locked out from the dashboard. I went to our hosting server, entered the MySQL database related to our WP installation and deactivated ALL plugins under WP-Options.
Once back in, one by one, I activated all plugins again, except WPUF...
