### ISSUE TITLE
[pro] Registration form : Display Custom Fields in Admin Email notification 

### ISSUE THREAD

**Issue by lmoncany** [weDevsOfficial/wp-user-frontend#894]
Hi, can you help me with the Wp user frontend pro. 

I created a custom registration form. I would like to display all the fields in the email notifications sent to the user and to the admin. For example : You may use:   %username% %user_email% %display_name% %user_status% %pending_users%   %approved_users% nied_users% But i would like : to show all the fields which  are in my registration form. Can you help with that?

Support told me this : 
You have to add proper customization in this file WP-content/plugins/wp-user-frontend-pro/includes/profile-form.php, find line number 317 and there you will find a function form_settings_notification(). You need to introduce the custom fields here to make them available in the registration notification email.

But i'm struggeling, is it possible to get a bit of help from someone ?
--

**Comment by zamandevs** [comment]
@lmoncany Please check on the future release. enhanced
