### ISSUE TITLE
Can not Login since Update to 3.3.0

### ISSUE THREAD

**Issue by Fendt1** [weDevsOfficial/wp-user-frontend#896]
If I will log in as admin, I am not able to come into my admin?

What to do?

As I will be drawn, as every member to the account-page in frontend.

Best
Josef

**Comment by ediamin** [comment]
@Fendt1 please take a look at this issue #887, if you think it is related to yours then download the develop branch from github and try again.

If it doesn't help, please comment here again.

**Comment by lmoncany** [comment]
Same issue here since the update. 

had to uncheck the option "override wordpress default login" in order to get it working. and avoid 2 clients website being blocked.

**Comment by Fendt1** [comment]
Good idea with “override WordPress default login“:
But how to come to this point, as I cannot come into the admin-area?
