### ISSUE TITLE
Form Builder's validate_form_before_submit breaks ability to use WPUF with custom post types solely consisting of custom fields

### ISSUE THREAD

**Issue by mudtar** [weDevsOfficial/wp-user-frontend#90]
I sometimes use WP-User-Frontend to collect user input and save it in custom fields to posts of a custom post type. In many of these cases, I do not pipe any of this data to `post_title`, `post_content`, or `post_excerpt`, as I am entirely served by the specific custom fields I have created. The release of [v2.5](https://github.com/weDevsOfficial/WP-User-Frontend/releases/tag/v2.5) introduces a feature that requires a post form to have one of its fields piped into either `post_title`, `post_content`, or `post_excerpt`. I don't want to have to do this, and I don't see a reason that it should necessarily be the case.

My current solution is to downgrade to [v2.4.4](https://github.com/weDevsOfficial/WP-User-Frontend/releases/tag/v2.4.4) when I want to create or update a form that doesn't pipe into any of these fields.

The regressive functionality in question is introduced in 8242822, specifically [here](https://github.com/weDevsOfficial/WP-User-Frontend/commit/8242822e0a537c1515ee756931dfdb02e2a91e2c#diff-7d0af0f89f6bb3241005ec60b296fc1fR240).

**Comment by tareq1988** [comment]
The `wp_insert_post` function [expects you](https://core.trac.wordpress.org/browser/tags/4.7/src/wp-includes/post.php#L3057) to submit at least a post title, content, or excerpt. For most of the post types, those are required and we get a lots of support tickets for that. 

But based on the post type requirement those restriction changes and right now our logic isn't flexible enough to support that. Will fix the issue in a next release.
