### ISSUE TITLE
Cannot Login to ADMIN-Area sind 3.3.1

### ISSUE THREAD

**Issue by Fendt1** [weDevsOfficial/wp-user-frontend#900]
Since 3.3.1 i cannot login.

If i go to WP-ADMIN: i am rederected to account in frontend.
If i go to WP-LOGIN: i am rederected to account in frontend.

But if i log-in with the login-widget in the sidebar, i come in to the frontend and can see the black bar on top of the ADMIN-Area. 

BUT I can NOT come into the ADMIN-Area.

What to do?

**Comment by ediamin** [comment]
<img width="837" alt="Screenshot 2020-06-17 at 3 55 17 PM" src="https://user-images.githubusercontent.com/1541774/84884246-4ca90000-b0b3-11ea-8f12-8557052ff11d.png">

@Fendt1 Take a look at the screenshot of my settings above. Those two checkbox is checked and Login Page is set to "Login". So, I'll be redirect to my "Login" page every time I try to access wp-admin or wp-login pages.

Have you set your "Account" page in Login Page settings? Please share your settings screenshot, it'll be very helpful.

**Comment by Fendt1** [comment]
Thank you for the prompt answer!

Unfortunately I cannot come into the ADMIN-area.
How to come into this area?
It is a circle.

Am Mi., 17. Juni 2020 um 12:00 Uhr schrieb Edi Amin <
notifications@github.com>:

**Comment by ediamin** [comment]
Please contact our support at wedevs.com and share your site and ftp credentials . I think it'll be better if I just debug the issue on your site.

**Comment by ediamin** [comment]
@Fendt1 please read my previous comment here. I need your site credentials to debug. Please contact our support at wedevs.com and share your credentials there. You don't need to post multiple issues regarding login problem. I'll definitely look into it.

**Comment by ediamin** [comment]
I’m closing this issue because it has been inactive for a few months. Feel free to open at anytime again.
