### ISSUE TITLE
Cannot delete or change featured image on edit post form

### ISSUE THREAD

**Issue by fredricq** [weDevsOfficial/wp-user-frontend#906]
Users can create posts from front end using post form with standard fields and featured image field.
After  publishing they can edit all fields of their posts except the featured image field.
The delete icon pops up and can be clicked, but nothing happens.  
Know bug?

**Comment by kabirbd89** [comment]
Its not working with admin privilege user too.

**Comment by hasinur1997** [comment]
This issue doesn't exit.
