### ISSUE TITLE
Feature Request: Disable dashboard tab or add option to disable it in profile. 

### ISSUE THREAD

**Issue by kabirbd89** [weDevsOfficial/wp-user-frontend#908]
Its little bit weird to show these two line in profile dashboard in this wonderful plugin 

> Hello User, (not User? Sign out)
> From your account dashboard you can view your dashboard, manage your Posts, edit your password and profile

The dashboard literally empty, I would love to hide this dashboard tab, can dev team add a option in settings to hide this tab.

**Comment by zamandevs** [comment]
@kabirbd89 We had revised it. will be on a future release.
