### ISSUE TITLE
Feature image can't be replaced/deleted from the front-end

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#909]
**How to reproduce:**
1. Create a post form with a featured image
2. Published the form/page
3. Submit a post by attaching a featured image 
4. Now after post submission, navigate to your frontend My Account post-section and edit the post. You will notice an admin-ajax call error with 422 status & Uncaught error.

**Additional screenshots - Console error log:** 
https://prnt.sc/t2w92t
https://prnt.sc/t2w78n

**Expected behavior:** It should let the users replace/delete the feature image from the frontend as like the previous version.
**Note**: The result is the same for both version 3.3.0 & 3.3.1 but with the V-3.2.0 the behavior is okay.

**Comment by luoskrad** [comment]
I have the same issue, Is there a function we can use while they fix this?
