### ISSUE TITLE
Featured image or insert photo option not inserting photo from iPhone

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#910]
**How to reproduce:**
- Create a post form with a featured image, enabling the insert photo option of the post content field.
- Try to upload a photo from your iPhone, you will notice it's not opening the file manager/gallery to choose the photos/media

**Additional screencast:** 
Please [check this quick video](https://d.pr/v/hNN5Ku). 

Expected behavior: 
It should let the users choose media from the file manager/gallery to upload files.

Thanks

**Comment by mmarj** [comment]
@hasinur1997 Bhai, would you please check this issue once again. We got multiple complaints regarding this iPhone image/file upload issue mainly with iPhone 7, 8, and XS.
Thanks.

**Comment by mmarj** [comment]
@hasinur1997 Bhai, would you please check this issue once again. We got multiple complaints regarding this iPhone image/file upload issue mainly with iPhone 7, 8, and XS (please check [this ref screencast](https://drive.google.com/file/d/1AkWfafXl-p_KlF6nFudEZcVSGvuQYjKF/view?usp=sharing)).
Thanks.

**Comment by FaraziF** [comment]
@mmarj We can not reproduce this issue from **iOS 14.0.1, iPhone11**
[Video Reference](https://drive.google.com/file/d/1-AliK3Y5Yo83PeDTGaJtd2TllqfP9CWx/view?usp=sharing)

**Comment by mmarj** [comment]
Sorry for the late reply.
@FaraziF Bhai, (if possible) please test with the iPhone 7, 8 :( 
Thanks.

**Comment by mmarj** [comment]
Intermittent issue.
