### ISSUE TITLE
Can Not Upload Image With Same Filename

### ISSUE THREAD

**Issue by Sarkham** [weDevsOfficial/wp-user-frontend#913]
When you try to set the image using the WPUF form, it appears to upload but then displays an image from a previous post that has the same filename. Checking the media library shows the new image was never uploaded.

This doesn’t happen when setting the featured image in the regular WordPress backend editor – it has no problem uploading a file with the same filename as a previously uploaded file, and it correctly sets the featured image on the post.

any user can edit their post and delete the images from the gallery uploaded by other users to other posts, previous versions solve that by adding -1, -2 … to the end of the image url.

This way any user can delete the entire WordPress upload folder.

**Comment by ediamin** [comment]
Fixed via #919
