### ISSUE TITLE
Issues in Lock User From Editing After Feature In Form Setting

### ISSUE THREAD

**Issue by kabirbd89** [weDevsOfficial/wp-user-frontend#922]
Hey,
If a user post in **Lock User From Editing After** setting enable with a certain period of time.  That specific post completely locks after that time. It's supposed to work that way, but when **Lock User From Editing** time changes to disable means unlimited. The specific post which was posted with a certain time period cant be edited. Both by the user and also admin. 

Secondly, 
If I enable "Lock User From Editing After" for a certain time this it also impacts the user with administrative privilege. I think it's supposed to make the user lock but not the admin or editor.

**Comment by hasinur1997** [comment]
This issue doesn't exist.
