### ISSUE TITLE
Members gets mails, that their contract is running out - but they are unlimited members

### ISSUE THREAD

**Issue by Fendt1** [weDevsOfficial/wp-user-frontend#926]
This happens again and again. But not to all members. 
The point is, that on some members, the date is set on 1. Januar 1970.

If I write at the end of the free subscription 1. April 2030 it works again. (sometimes - because it is not always written into the database directly, so have to write it again).

The stupid thing: the member gets a lot of mail, to renew his status. 

Is there a solution or a hack for this?

**Comment by zamandevs** [comment]
@Fendt1 Sorry for your inconvenience. fixed. will be on the next release.
