### ISSUE TITLE
Post content format is not getting saved correctly

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#930]
**Description:** 

When a user submits post and then edit the post, the format of the post content is not saved correctly. 

**How to Reproduce the issue:** 

1. First create a post form in WPUF, take a textarea field and then set as Teeny Rich textarea from [here](https://prnt.sc/tmzhu6).

2. Next create a group field in ACF and then set the textarea Wysiwyg editor.

3. Submit a post using that WPUF post form, then edit it from the frontend. Save the post. The paragraph content format is not saved. 

**Expected result**: In any case, the format of the paragraph should be saved saved correctly.  

Video: https://www.loom.com/share/92669da79c0e4aa885103c1d12d7c686

Same happens for any custom post type post. Formatting doesn't get saved and all the content shows as one block on content without any formatting.

**Comment by hasinur1997** [comment]
I tested it and couldn't find problem from my end.
