### ISSUE TITLE
Bulk image upload issue: Enhancement

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#931]
Description: Selecting and uploading multiple images in single attempt. Previously this was possible and our users loved that. 

When multiple images needs to be uploaded, uploading each one individually takes a lot of time. This can be more user friendly if multiple images can be uploaded in single attempt.

**Comment by ediamin** [comment]
We are currently working on refactoring uploading image/files system and trying to upload them with WP Media Manager.

**Comment by RUST13** [comment]
why is it taking so long to fix this..

**Comment by zamandevs** [comment]
@RUST13 fixed [HERE](https://github.com/weDevsOfficial/wp-user-frontend/pull/1007) .
