### ISSUE TITLE
Inconsistency with the Post Count option for the CPT dashboard

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#932]
**How to reproduce:**
- Make sure you have the Show post count option is enable- https://prnt.sc/tng4rg
- Create a custom dashboard with shortcode like [wpuf_dashboard post_type="product"]
- Roll-over the frontend then you will see above the dashboard table it's written as "You have created 1 ()" instead of You have created 1 (Products)

Current behavior:
Without the (CPT Name) - https://prnt.sc/tng5w1
Expected behavior: You have created 1 (Products _'CPT Name'_) as like the default post section- https://prnt.sc/tng5av

Thanks

**Comment by hasinur1997** [comment]
I tested it and works properly.   Please take a look -  https://prnt.sc/tnrtcl
