### ISSUE TITLE
No edit possibility when a post type post is drafted 

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#935]
**Description:** Whan a default post type post is saved as draft, once the post is left by the author, he is unable to edit the draft anymore from the account > posts section or from dashboard > posts section. 

**How to Reproduce the Issue:** 

1. Create a post form, enable save as draft from the form settings. 
2. Create a post using that form as a user and then save it as draft. 
3. Visit the account page and then try to edit the post which was drafted. 

**This doesn't happen for product type posts and the author can edit the product type post from the dashboard page.** 

**Video:** https://www.loom.com/share/c71119e4d83f43f2bed3ee92c2eeeba9

**Expected scenario:** All the posts should be available for editing after saving as draft.

**Comment by hasinur1997** [comment]
Couldn't find any problem with that, it works properly.
