### ISSUE TITLE
Image uploaded on post content area is appearing very small though the size of actual image is big

### ISSUE THREAD

**Issue by jaydeepqa** [weDevsOfficial/wp-user-frontend#937]
When I upload image in post content area using "Insert Photo" option then the image size is appearing very small, however when i do the same from Wordpress default post submission page then it appears big as per the original size.
Not sure if it is a bug or there is some settings which needs to be configured.

**Comment by hasinur1997** [comment]
@jaydeepqa You can choose photo size from wp-admin > user frontend > settings > Frontend Posting > Insert Photo Image Size.
