### ISSUE TITLE
Inconsistency with the WPUF login page Lost Password functionality

### ISSUE THREAD

**Issue by mmarj** [weDevsOfficial/wp-user-frontend#938]
**How to reproduce:**
1. Visit login page [wpuf-login] and choose the [Lost Password](https://prnt.sc/tq32b4) option.
2. You will notice the site/page URL is changing after submission of the email/username but it's not showing any visible message so that the user can at least acknowledged that the email notification is sent to the user's email.
3. The same thing is happening for the [WPUF Login Widget](https://prnt.sc/tq33w8) 

Additional Screencast:
Please [check out this video](https://drive.google.com/file/d/1pco8PuzfvQVXejeUEYfG88PuB14ODxHF/view?usp=sharing) to know more details.

**Comment by Anticosti** [comment]
+1 Same issue here

**Comment by Anticosti** [comment]
Would be nice if we could get "**_soon_**" these two messages:

**Before** (?action=lostpassword):
If you forgot your login information, your username and instructions on how to reset your password can be sent to you by email. Please enter your profile email address and submit the request.

**After clicking "Get New Password"** (?checkemail=confirm):
Instructions on how to reset your password have been sent to your email address, you should receive it shortly.

Thank you!
