### ISSUE TITLE
Out of 61 plugins I use, only WP User Frontend Pro - business conflicts with Full Screen Background Images Pro

### ISSUE THREAD

**Issue by Anticosti** [weDevsOfficial/wp-user-frontend#939]

**Comment by sapayth** [comment]
Hello @Anticosti,
Can you please provide us with some more details so that we can check the issue properly? A step-by-step process of how reproduce the problem would be much helpful.

**Comment by Anticosti** [comment]
Thank you @sapayth for the follow up.
It's been a while since this issue, and after a while, I decided to let down this "Full Screen Background Images Pro" plugin.
Sorry. Wish I could... but I can't remember exactly what was the issue? 
Closing this issue for now.
Kind Regards,
