### ISSUE TITLE
Not working together with PublishPress Revisions

### ISSUE THREAD

**Issue by Tsjippy** [weDevsOfficial/wp-user-frontend#941]
I have the free version of user frontend and also the [PublishPress Revisions](https://nl.wordpress.org/plugins/revisionary/) plugin.
Posting from the frontend goes fine, but editing not.  Can someone help to resolve this issue? If I click on "Update" the spinner just keeps spinning and never stops, no errors in the console.

Steps to reproduce:

1. Install wp user frontend
2. Create a form to create a post from front end and publish it on a page
3. Create a post from the frontend
4. Edit the post and update it-> works.
5. Install PublishPress Revisions plugin
6. Try to edit the post from front end -> does not work, unless you have administrator rights.

**Comment by sapayth** [comment]
Hello @Tsjippy,
Sorry to hear about your problem. As we checked, it seems working on our end. Please try again with the updated versions.

If you're still getting that problem, please contact our [support](https://wedevs.com/contact) so that we can check it in every possible way.
