### ISSUE TITLE
Submitting product attribute from frontend

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#946]
Description: 

If users insert product attribute value like this $500000 from the frontend, the value doesn't appear in the product page. 

How to Reproduce the Issue:

Create an attribute from WooCommerce > Product > Attribute section.

Take a WPUF product type form. Then take the custom attribute field from the taxonomy field area. 

Make the field a text input field. Now if we submit the product type post, the value doesn't appear as a newly created term in the attribute. 

Video: https://www.loom.com/share/5846a749ed55434c8e97c247b25ded6d

**Comment by camilolunacom** [comment]
@shabnam611 thanks for reporting this on our behalf.

I would like to add that this was working on version 3.1.9 of the plugin. It's when updating to version 3.3.1 that we found the issue.
