### ISSUE TITLE
Submitting taxonomy in text input field

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#948]
Description: If I submit a taxonomy in text input field, it doesn't appear in the backend of the post

How to Reproduce the Issue: 

Create a custom taxonomy for default WP post type.

Create a post form and insert the taxonomy field and the tag field. Set text input for the custom taxonomy field. Save the form. Then paste the form shortcode in a page. 

Submit the form from the frontend. Insert data in the taxonomy field by typing the input. 

If we check the post from the frontend, we do not find the data of the custom taxonomy in the backend and in the frontend. Also the data is not submitted under the custom taxonomy. 

Video: https://www.loom.com/share/f53b0985394a4de8b035a5e754770bbd

**Comment by hasinur1997** [comment]
I tested, this issue  doesn't exist now.
