### ISSUE TITLE
Image upload issue in mobile

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#950]
Description: When an image is uploaded and then the phone is rotated into horizontal and then rotate again into verticle, the image doesn't exist. 

How to reproduce the issue: 

Take a post form with image upload field, view the form in frontend and then rotate the phone into horizontal and then verticle again. 

Check if the uploaded image exists after rotating back into verticle. 

This is before submission. 

Expected behavior: The uploaded images should stay uploaded.

**Comment by zamandevs** [comment]
Although it shouldn't happen checked again, not produced what is stated above.
