### ISSUE TITLE
Issue with LightSpeed Cache

### ISSUE THREAD

**Issue by mtdas99** [weDevsOfficial/wp-user-frontend#951]
The WP User Frontend plugin have complexity with Newspaper X theme and Lightspeed Cache plugin. User Frontend plugin is not working with Newspaper Themes AMP and also conflicting with LightSpeed cache plugin. The issues I have found: 
1. Separate Wordpress login for admin is not available. 
2. Post submit form is not loading due to conflict with LightSpeed cache plugin. 

Regarding Lightspeed Cache, I have used all possible methods such as clearing cache, clearing minified CSS JS and combined css js, clearing Cloudflare cache etc. But no luck.

Although I have temporarily deactivated the plugin, my website reference is [Cbshop.in](https://news.cbshop.in)

**Comment by Anticosti** [comment]
I am also using Litespeed cache, coupled with QuikCloud CDN and I don't have this issue.

**Comment by mtdas99** [comment]
May be you don't have that issue but I am using Newspaper theme with LightSpeed cache and Newspaper theme also have issue with User Frontend plugin. Don't know whats causing this issue.

**Comment by zamandevs** [comment]
@mtdas99 Insight/further info requires for look into the issue. you can provide A to Z step whats you've done and what happened. or you can contact our support thus we can directly see investigate why this happening.
Thanks.
