### ISSUE TITLE
Problem With Taxonomy Input field v3.4.0

### ISSUE THREAD

**Issue by kabirbd89** [weDevsOfficial/wp-user-frontend#954]
I am getting unexpected behavior in the taxonomy input field in post form. I used to use the following combinations which are not working as expected after updating to v3.4.0 

1. Input Type "Ajax" but its work like select. and Selection Type "Exclude" does not work. 
1. Input type "Select" and selection type "Child of" but only parent taxonomies are showing not any child.

**Comment by hasinur1997** [comment]
This issue doesn't exist.
