### ISSUE TITLE
Add post edit link

### ISSUE THREAD

**Issue by DenisCGN** [weDevsOfficial/wp-user-frontend#956]
Hello,

### v3.4.0 (24 August, 2020) ### * New - Add post edit link for post authors in single or archive pages.
What is so magic with that link? Ain't it standard in WP?
Or didn't I understand why you put it in an Changelog now?

Cheers,
Denis

**Comment by ediamin** [comment]
Hi @DenisCGN thank you for asking. By default post edit link shows to those users who have edit_post capability. Admin, Editor, Contributors have them. But with WPUF you can register users with any kind of role. These "other" kind of users usually do not have the edit_post capability. So, they can not see the "Edit" link in blog/archive or single post pages that we usually see right after post content. This new feature solves that problem. If user is the post author, then s/he will see the Edit post link that redirects to WPUF frontend edit page.

Although it is not perfect yet. We see that we're getting issue for Editor or Contributors type users. So, we'll soon push a fix for this also.

**Comment by DenisCGN** [comment]
Hello @ediamin 
Thanks a lot.
Now it’s clear.
Cheers,
Denis
