### ISSUE TITLE
Image field issue with ACF

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#957]
Description: When Image field is used in WPUF post form, it is not mapped correctly in the backend post. 

How to reproduce: 

Take a WPUF post form, add image upload field as a custom field along with fields like post title, content etc. 

Next create a field group in ACF with Image field. 

Then submit the post and then visit the post from backend, the image field is blank. 

Video: https://www.loom.com/share/89b455b5ecf24fea9fd0e2a7f9688648

Expected result: The image should be available in backend when ACF is enabled. 

Additional tip: Such issue doesn't exist when ACF is not activated and all the fields appear correctly in the backend WPUF custom field area.

**Comment by hasinur1997** [comment]
I tested this issue and it worked properly.
