### ISSUE TITLE
Post form - Galery Images dont transfer to the product

### ISSUE THREAD

**Issue by lnAdimals** [weDevsOfficial/wp-user-frontend#958]
Hi, I have a problem with the post form. I have set up the form and set the appropriate options for saving the gallery images and transferring them to the product created by the form. The whole thing just doesn’t work and I don’t know what to do next. Is this a known problem? Wordpress version is 5.5
Site: http://castingprojekt.adimals.rocks

**Comment by zamandevs** [comment]
@lnAdimals Tested again throughly. couldn't find anything wrong. please check and let us know if anything wrong on your end and don't hesitate to reach us.
