### ISSUE TITLE
Checkbox displays value on frontend and not the checkbox

### ISSUE THREAD

**Issue by soumaan** [weDevsOfficial/wp-user-frontend#965]
I've tried several options and created different forms but the checkbox won't display in both the form preview and page integration
![Checkbox](https://user-images.githubusercontent.com/25481378/92332665-71d85980-f077-11ea-9caa-0919e282a4c3.png)

This is an image of the problem, there's no way to choose the options

**Comment by hasinur1997** [comment]
@soumaan I have tested this issue, couldn't find any problem. Please create a ticket to our support with your site credentials.

**Comment by soumaan** [comment]
okay. Thanks, I already solved the problem.. The issue was from the theme they set the checkboxes to display: none.

Thanks
