### ISSUE TITLE
3 problems for image upload field 

### ISSUE THREAD

**Issue by freelylw** [weDevsOfficial/wp-user-frontend#966]
I have added a “image upload” field into my post form. I am getting 3 problems with this field now which makes the whole things doesn’t work at all.

1: I have set the field “Required” to “no”, but when guest posting, the field still showing “required”

2: after user upload 1 image, the “Create Post” button turning grey, please see screenshot here https://ibb.co/PmHfc3D

3: when user start to upload the second image, the uploading process is hanging forever.

Please advise for how to solve the problems, at the moment, it stops us to use the plugin. Thank you

( when the image uploading hanging, “create post” button freeze, there is no error showing on the page console, I don’t have any page builder installed, no recaptcha installed )

**Comment by hasinur1997** [comment]
This is doesn't exist.
