### ISSUE TITLE
Enabled Payment Field Broke Redirect

### ISSUE THREAD

**Issue by devonhg** [weDevsOfficial/wp-user-frontend#968]
![brokenform](https://user-images.githubusercontent.com/10793021/92635954-9f561a80-f2a4-11ea-87a6-ffac8d3f6439.png)
![workingsite](https://user-images.githubusercontent.com/10793021/92635957-9feeb100-f2a4-11ea-999f-95a4bd681f5a.png)
[workingform.txt](https://github.com/weDevsOfficial/wp-user-frontend/files/5197101/workingform.txt)
[brokenform.txt](https://github.com/weDevsOfficial/wp-user-frontend/files/5197103/brokenform.txt)
![unnamed](https://user-images.githubusercontent.com/10793021/92635990-ac730980-f2a4-11ea-8dc0-600e70a348c3.png)

I just got done working with your support staff on issue number 413516. The cause of the issue was that even though the general payment options were disabled, some other checkboxes relating to payment were enabled, and this caused the redirect functionality of the form to break. Attached are all the files relating to this issue. 

Probably not a high priority, as fixing it was simply checking enable payments in the form settings, unchecking the options, and then unchecking payments again. Ideally I would think that if payments are completely disabled then all other payment options would be disabled as well. Otherwise, it shouldn't affect the functionality of the form.

**Comment by zamandevs** [comment]
@devonhg Fixed on the release.
