### ISSUE TITLE
Backend editing is unavailable for users other than admin

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#972]
Description: If a user tries to edit a post from backend, they are unable to do that. 

How to Reproduce the issue: 

First from WP-admin > WPUF > Settings > Dashboard > Edit post set to no. 

Make sure the users can access backend from WP-admin > WPUF > Settings > Genral section. 

Then as a user [edit/subscriber] try to edit the post from backend. You will see the post editing option is unavailable. 

However, if it is set to yes from WP-admin > WPUF > Settings > Dashboard > Edit post , then the edit button appears. But the user is redirected to frontend. 

Video: https://www.loom.com/share/0b9e1b558f9d4b619a7efa6554b57db4

Expected behavior: Since the settings doesn't specify whether it is from frontend or backend, while trying to edit from backend, users should stay in backend to edit the post.

**Comment by ediamin** [comment]
@shabnam611 @FaraziF please pull the latest develop branch and test in your localhost. This issue should be fixed in f1a1c042501f1dc0ec183da6dade67b777b80fac and 1be9bb9655828cccd95c9e652e61fe2c239315cf.

**Comment by mmarj** [comment]
According to my last testing with the latest development version, this issue is fixed.

**Comment by FaraziF** [comment]
This issue fix with the latest version

**Comment by ediamin** [comment]
Fixed via f1a1c04 and 1be9bb9.
