### ISSUE TITLE
Featured Image is not shown in Form

### ISSUE THREAD

**Issue by deeprojects** [weDevsOfficial/wp-user-frontend#973]
Hello, 

i have a Problem with the Featured Image Field of the post form. 

Every field is working fine. Only the featured image field is not shown anymore in the frontend. 

Can you please help me? 

Best Regards
Dennis Drzosga

**Comment by hasinur1997** [comment]
@deeprojects Tested the issue but couldn't reproduce that. Please contact to our support team.

**Comment by dsamg** [comment]
@hasinur1997 we have the same issue, think it started to appear post since the previous update. The featured image field does not show up. Can you re-look at it?
