### ISSUE TITLE
Inconsistency with Frontend Edit button appearance

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#975]
Description: In the account page, the edit button appears and when we click on it, we see a notice "I don't know how to edit the post. I don't have the valid form ID"

How to Reproduce the Issue: 

Just visit the account page and look for the edit button. Click on it. 

This happens if we click on edit while editing the post from frontend

Both of the above points are the result of wrong usage. Since they should not be used, I believe, they should not be there. 

Video: https://www.loom.com/share/dc3d8009b09243368b4e99f9e56c1444

Expected Behavior: The edit button should only be available inside the post

**Comment by hasinur1997** [comment]
@shabnam611 I have tested the issue and couldn't find the problem. Please pull latest develop branch and test again.

Thanks.
