### ISSUE TITLE
Modular loading: turn on/off parts of the plugin

### ISSUE THREAD

**Issue by tareq1988** [weDevsOfficial/wp-user-frontend#99]
With the new **Contact Form** feature coming, we should be able to turn on/off parts of the plugin we don't need.

**Use case:** if I want to use the plugin as a contact form only, I don't need posting and registration field builder. So I could turn those features off.

**Example UI:** jetpack
![image](https://cloud.githubusercontent.com/assets/153669/24644475/8dc55dea-1935-11e7-8689-6b0a8acf76b6.png)

**Comment by Sk-Shaikat** [comment]
https://bitbucket.org/wedevs/wpuf-pro/commits/0ff70d98579b90bae1040384dd69d09533dfb08e
