### ISSUE TITLE
ACF with WPUF problem

### ISSUE THREAD

**Issue by aureliopons** [weDevsOfficial/wp-user-frontend#991]
Hi I have a problem combining Advanced Custom Fields and WPUF PRO In my type of post I have created a group of fields with ACF among which is a gallery type field. In the frontend form for WPUF I have created the equivalent image type field, indicating that up to 10 can be uploaded. I have a total of 18 fields of this type in the form I find two serious problems 

1. When I create a post from the backend and enter the frontend, the image fields already appear with a default image (/wp-includes/images/media/default.png), instead of empty. This image cannot be removed or replaced, and it disables the button to upload new images. 

2. If in this state I save the form from frontend, the next time I edit it, everything works normal, the fields have been regenerated. However, incredibly, I created an equivalent number of posts of type "wpuf-post-forms", one for each image field that was in the form. This doesn't make sense, saving a form with 18 gallery-type fields creates 18 wpuf-post-forms posts. We await your indications as this is a serious problem in our project, which is already out of date. 

Thank you

**Comment by aureliopons** [comment]
More info: I have tested the fields are correctly named as in the demo video, field names are equal.

I will try to explain what happens in the database, for example, a field called "image1" in WPUF and ACF that has the 1234 ACF field identifier code.

When I create a new post with WPUF from frontend, what I get in the database is a record like this:

[ meta_key=_image1, meta_value=field_1234 ]

When I create the post with ACF from wordpress dashboard, what I get are two records:

[ meta_key=_image1, meta_value=field_1234 ]

[ meta_key=image1, meta_value="" ] (the value is void, null or not exists, but record exists)

So, in this second case, the "image1" meta_key record exists but is void. As a result, WPUF is showing a void image in the frontend, as it believes there is an image. Then I cant upload anything to this field, and I cant delete the void image.

Then I save the ACF created post in frontend and problem is solved. All fields appear correct in frontend and can continue working. Then I can see the uploaded images in ACF backend, but If I save from backend, void image fields come back to the same problem.

Also when saving from frontend, a post of type wpuf-post-forms is created automatically !!!

**Comment by zamandevs** [comment]
@aureliopons if you please check on the current version this shouldn't happen. we have fixed ACF-related issues a few releases ago. Still, if you find anything wrong don't forget to reach us with more detail.
