### ISSUE TITLE
Pay per Post: Edit post is asking for payment

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/wp-user-frontend#994]
**Description:** 

When a post form has "pay per post" enabled and the users pay for submitting each post, when they try to edit the post from the account page, they are asked to pay again for updating. 

This is incorrect behavior. 

**How to Reproduce the Issue:** 

1. Please navigate through WP-admin > WPUF > post form. Create a post form. 

2. Visit the Post form > Settings > Payment Settings and then enable payment first. Next, you will be able to select pay per post and the amount users will have to pay for submitting the post. Screenshot of the settings: https://prnt.sc/uzltog

3. Next try to submit a post using the post form where you have enabled pay per post. While submitting, you will be asked to pay. Complete the process. 

4. Next, visit the account page built with the shortcode [wpuf_account] and try to edit the post. Edit and click on Update. You will see the payment page asks the user to pay again just like the post was submitted first time. 

**Video:**https://www.loom.com/share/acf593e3d98e49e7bb10c0c47f0bdcc9

**WordPress Settings:** 

WordPress version 5.5.1

Activated Plugin: WPUF free 3.5.2

WordPress address (URL): |   | http://localhost/wpuf
-- | -- | --
Site address (URL): |   | http://localhost/wpuf
WooCommerce version: |   | 4.5.2
WooCommerce REST API package: |   | 4.5.2 /Users/wedevs/Documents/www/wpuf/wp-content/plugins/woocommerce/includes
WooCommerce Blocks package: |   | 3.1.0 /Users/wedevs/Documents/www/wpuf/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Action Scheduler package: |   | 3.1.6 /Users/wedevs/Documents/www/wpuf/wp-content/plugins/woocommerce/packages/action-scheduler
WooCommerce Admin package: |   | 1.5.0 /Users/wedevs/Documents/www/wpuf/wp-content/plugins/woocommerce/packages/woocommerce-admin
Log directory writable: |   | /Users/wedevs/Documents/www/wpuf/wp-content/uploads/wc-logs/
WordPress version: |   | 5.5.1
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

Server environment
--
Server info: |   | Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.20 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.9 Perl/v5.24.0
PHP version: |   | 7.1.20 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP post max size: |   | 32 MB
PHP time limit: |   | 30
PHP max input vars: |   | 1000
cURL version: |   | 7.60.0, OpenSSL/1.0.2o
SUHOSIN installed: |   | –
MySQL version: |   | 5.7.23
Max upload size: |   | 32 MB
Default timezone is UTC: |   |  
fsockopen/cURL: |   |  
SoapClient: |   |  
DOMDocument: |   |  
GZip: |   |  
Multibyte string: |   |  
Remote post: |   |  
Remote get: |   |

**Comment by hasinur1997** [comment]
This is issue has been resolved by this pull request  https://github.com/weDevsOfficial/wp-user-frontend/pull/961
